// pass_by_value-referenceCPP.c
// Generated by decompiling pass_by_value-referenceCPP.exe
// using Reko decompiler version 0.6.2.0.

#include "pass_by_value-referenceCPP.h"

void fn00401180(word32 ecx, word32 ebx)
{
	ptr32 ebp_152 = fp - 0x04;
	LPTOP_LEVEL_EXCEPTION_FILTER * esp_163 = fp - 0x1C;
	<anonymous> * eax_11 = globals->ptr40A0D4;
	if (eax_11 != null)
	{
		word32 esp_151;
		byte SCZO_154;
		word32 eax_155;
		byte SZO_156;
		byte C_157;
		byte Z_158;
		word32 edx_159;
		word32 esi_161;
		word32 edi_162;
		eax_11();
		esp_163 = esp_151 - 0x0C;
	}
	*esp_163 = (LPTOP_LEVEL_EXCEPTION_FILTER *) &globals->t401000;
	SetUnhandledExceptionFilter(*esp_163);
	fn004017D0(ecx, ebx);
	fn004018B0();
	word32 ecx_37 = fn004014C0(ebp_152);
	union Eq_43 * esp_34 = esp_163;
	Eq_43 eax_38 = globals->t40D020;
	if (eax_38 != 0x00)
	{
		globals->t409004 = eax_38;
		*esp_34 = (union Eq_43 *) eax_38;
		word32 eax_98 = iob->dw0010;
		*(esp_34 - 0x04) = eax_98;
		struct Eq_178 * esp_100;
		word32 ebp_101;
		struct Eq_180 * ebx_102;
		byte SCZO_103;
		word32 eax_104;
		byte SZO_105;
		byte C_106;
		byte Z_107;
		word32 edx_108;
		word32 ecx_109;
		word32 esi_110;
		word32 edi_111;
		setmode();
		esp_100->t0000 = globals->t40D020;
		word32 eax_115 = ebx_102->dw0030;
		esp_100->dwFFFFFFFC = eax_115;
		struct Eq_204 * esp_117;
		word32 ebp_118;
		struct Eq_206 * ebx_119;
		byte SCZO_120;
		word32 eax_121;
		byte SZO_122;
		byte C_123;
		byte Z_124;
		word32 edx_125;
		word32 ecx_126;
		word32 esi_127;
		word32 edi_128;
		setmode();
		esp_117->t0000 = globals->t40D020;
		word32 eax_132 = ebx_119->dw0050;
		esp_117->dwFFFFFFFC = eax_132;
		word32 esp_134;
		word32 ebp_135;
		word32 ebx_136;
		byte SCZO_137;
		word32 eax_138;
		byte SZO_139;
		byte C_140;
		byte Z_141;
		word32 edx_142;
		word32 ecx_143;
		word32 esi_144;
		word32 edi_145;
		setmode();
	}
	word32 esp_42;
	word32 ebp_43;
	word32 ebx_44;
	byte SCZO_45;
	union Eq_43 * eax_46;
	byte SZO_47;
	byte C_48;
	byte Z_49;
	word32 edx_50;
	Eq_43 ecx_51;
	word32 esi_52;
	word32 edi_53;
	_p__fmode();
	Eq_43 edx_55 = globals->t409004;
	*eax_46 = (union Eq_43 *) edx_55;
	word32 edx_57;
	word32 ebp_58;
	Eq_43 ecx_59 = fn00401DD0(ecx_51, edx_55, esi_52, edi_53, out edx_57, out ebp_58);
	__align(esp_42 + ~0x03);
	word32 eax_60 = fn00401940(esi_52);
	struct Eq_102 * esp_61;
	word32 ebp_62;
	word32 ebx_63;
	byte SCZO_64;
	word32 * eax_65;
	byte SZO_66;
	byte C_67;
	byte Z_68;
	word32 edx_69;
	word32 ecx_70;
	word32 esi_71;
	word32 edi_72;
	_p__environ();
	esp_61->dw0004 = *eax_65;
	esp_61->dw0000 = globals->dw40D000;
	word32 eax_78 = globals->dw40D004;
	esp_61->dwFFFFFFFC = eax_78;
	fn00401433(ebp_62, esi_71);
	struct Eq_138 * esp_81;
	word32 ebp_82;
	word32 ebx_83;
	byte SCZO_84;
	word32 eax_85;
	byte SZO_86;
	byte C_87;
	byte Z_88;
	word32 edx_89;
	word32 ecx_90;
	word32 esi_91;
	word32 edi_92;
	cexit();
	esp_81->tFFFFFFFC = 0x00;
	ExitProcess(esp_81->tFFFFFFFC);
}

void fn00401260()
{
	word32 esp_16;
	byte SCZO_17;
	word32 eax_18;
	byte SZO_19;
	byte C_20;
	_getmainargs();
	return;
}

Eq_43 Win32CrtStartup()
{
	word32 esp_5;
	byte SCZO_6;
	word32 esi_7;
	word32 edi_8;
	word32 eax_9;
	word32 ecx_10;
	word32 ebx_11;
	_set_app_type();
	fn00401180(ecx_10, ebx_11);
	word32 esp_18;
	byte SCZO_19;
	word32 esi_20;
	word32 edi_21;
	word32 eax_22;
	word32 ecx_23;
	word32 ebx_24;
	_set_app_type();
	fn00401180(ecx_23, ebx_24);
	return fn004012E0();
}

int32 fn004012E0()
{
	return atexit(*esp_1);
}

word32 fn00401410(word32 dwArg04)
{
	return dwArg04 + 0x0A;
}

void fn00401433(word32 ebp, word32 esi)
{
	__align(fp - 0x04);
	fn00401940(esi);
	*(fp - 44) = fp - 0x14;
	*(fp - 0x30) = fp - 0x10;
	*(fp - 0x34) = 0x0040A0C0;
	struct Eq_319 * esp_15;
	word32 ebp_16;
	byte SCZO_17;
	word32 eax_18;
	word32 edx_19;
	word32 ecx_20;
	word32 esi_21;
	msvcrt.dll!scanf();
	esp_15->dw0000 = esp_15->dw0024;
	esp_15->dw002C = fn00401410(dwArg00);
	esp_15->dw0000 = esp_15->dw0020;
	esp_15->dw0028 = fn00401410(dwArg00);
	word32 edx_31 = esp_15->dw0020;
	word32 eax_32 = esp_15->dw0024;
	esp_15->dw0010 = esp_15->dw0028;
	esp_15->dw000C = esp_15->dw002C;
	esp_15->dw0008 = edx_31;
	esp_15->dw0004 = eax_32;
	esp_15->dw0000 = 0x0040A0C6;
	fn004081E8(dwArg00);
	return;
}

int32 fn004014C0(ptr32 ebp)
{
	if ((globals->b409000 & 0x02) == 0x00)
	{
		fn00401260();
		return ecx;
	}
	Eq_43 eax_43 = GetCommandLineA();
	Eq_43 eax_47 = strlen(eax_43);
	word32 eax_48 = eax_47 + 0x11 + eax_47;
	fn00401FC0(eax_48 & ~0x0F);
	Eq_43 esi_163 = eax_43;
	struct Eq_415 * esp_52 = fp - 0x5C - (eax_48 & ~0x0F);
	int32 eax_161 = 0x00;
	byte al_157 = 0x00;
l00401537:
	esi_163 = esi_163 + 0x01 + 0x01;
	ci8 bl_156 = (byte) (word32) *(esi_163 - 0x01);
	int32 ecx_112 = (int32) bl_156;
	if (ecx_112 == 0x00)
	{
l004015C0:
		byte * eax_104;
		byte * edx_148 = *(fp - 0x30);
		if (eax_161 != 0x00)
		{
			eax_104 = edx_148 + eax_161;
			do
			{
				edx_148 = edx_148 + 0x01;
				*(edx_148 - 0x01) = 0x5C;
			} while (edx_148 != eax_104);
		}
		else
			eax_104 = edx_148;
		if (*(fp - 0x38) != 0x00 || *(fp - 0x40) < eax_104)
		{
			*eax_104 = 0x00;
			esp_52->ptr000C = fp - 44;
			esp_52->dw0008 = 0x00;
			esp_52->dw0004 = *(fp - 0x3C);
			esp_52->dw0000 = *(fp - 0x40);
			ecx_112 = fn00402C30(dwArg00, dwArg04, dwArg08, dwArg0C);
		}
		globals->dw40D004 = *(fp - 0x28);
		globals->dw40D000 = *(fp - 0x24);
		return ecx_112;
	}
l00401545:
	word32 edi_171;
	if (bl_156 != 0x3F)
	{
		if (bl_156 <= 0x3F)
		{
			byte * ebx_291;
			if (bl_156 == 0x27)
			{
				if ((globals->b409000 & 0x10) != 0x00)
				{
					int32 ebx_353 = eax_161 >> 0x01;
					if (ebx_353 != 0x00)
					{
						byte * edx_377 = *(fp - 0x30);
						ebx_291 = edx_377 + ebx_353;
						do
						{
							edx_377 = edx_377 + 0x01;
							*(edx_377 - 0x01) = 0x5C;
						} while (edx_377 != ebx_291);
					}
					else
						ebx_291 = (byte *) *(fp - 0x30);
					if ((al_157 & 0x01) != 0x00 || *(fp - 0x34) == 0x22)
					{
						*(fp - 0x30) = ebx_291 + 0x01;
						*ebx_291 = 0x27;
						*(fp - 0x38) = 0x01;
						eax_161 = 0x00;
						al_157 = 0x00;
						goto l00401537;
					}
l0040159D:
					*(fp - 0x30) = (byte **) ebx_291;
					esi_163 = esi_163 + 0x00;
					bl_156 = (byte) (word32) *(esi_163 - 0x01);
					*(fp - 0x34) = *(fp - 0x34) ^ ecx_112;
					*(fp - 0x38) = 0x01;
					eax_161 = 0x00;
					al_157 = 0x00;
					ecx_112 = (int32) bl_156;
					if (ecx_112 != 0x00)
						goto l00401545;
					goto l004015C0;
				}
				goto l004016A5;
			}
			if (bl_156 != 0x2A)
			{
				if (bl_156 == 0x22)
				{
					int32 ebx_312 = eax_161 >> 0x01;
					if (ebx_312 != 0x00)
					{
						byte * edx_336 = *(fp - 0x30);
						ebx_291 = edx_336 + ebx_312;
						do
						{
							edx_336 = edx_336 + 0x01;
							*(edx_336 - 0x01) = 0x5C;
						} while (edx_336 != ebx_291);
					}
					else
						ebx_291 = (byte *) *(fp - 0x30);
					if ((al_157 & 0x01) != 0x00 || *(fp - 0x34) == 0x27)
					{
						*(fp - 0x30) = ebx_291 + 0x01;
						*ebx_291 = 0x22;
						*(fp - 0x38) = 0x01;
						eax_161 = 0x00;
						al_157 = 0x00;
						goto l00401537;
					}
					goto l0040159D;
				}
				goto l004016A5;
			}
		}
		else
		{
			if (bl_156 == 0x5C)
			{
				eax_161 = eax_161 + 0x01;
				al_157 = (byte) eax_161;
				goto l00401537;
			}
			if (bl_156 != 0x7F)
			{
				if (bl_156 != 0x5B)
				{
l004016A5:
					ci8 * edx_223 = *(fp - 0x30);
					ci8 * edi_225 = *(fp - 0x30) + eax_161;
					if (eax_161 != 0x00)
					{
						do
						{
							edx_223 = edx_223 + 0x01;
							*(edx_223 - 0x01) = 0x5C;
						} while (edx_223 != edi_225);
					}
					else
						edi_225 = (ci8 *) *(fp - 0x30);
					if (*(fp - 0x34) == 0x00)
					{
						esp_52->dw0000 = ecx_112;
						if (isspace(esp_52->dw0000) != 0x00)
						{
							if (*(fp - 0x38) == 0x00 && *(fp - 0x40) >= edi_225)
							{
								*(fp - 0x30) = (ci8 **) edi_225;
								eax_161 = 0x00;
								al_157 = 0x00;
							}
							else
							{
								*edi_225 = 0x00;
								esp_52->ptr000C = fp - 44;
								esp_52->dw0008 = 0x00;
								esp_52->dw0004 = *(fp - 0x3C);
								int32 edi_261 = *(fp - 0x40);
								esp_52->dw0000 = edi_261;
								fn00402C30(dwArg00, dwArg04, dwArg08, dwArg0C);
								*(fp - 0x3C) = *(fp - 0x3C) | 0x01;
								*(fp - 0x30) = edi_261;
								*(fp - 0x38) = 0x00;
								eax_161 = 0x00;
								al_157 = 0x00;
							}
							goto l00401537;
						}
					}
					*(fp - 0x30) = edi_225 + 0x01;
					*edi_225 = bl_156;
					eax_161 = 0x00;
					al_157 = 0x00;
					goto l00401537;
				}
				edi_171 = 0x01;
				if ((globals->b409000 & 0x20) == 0x00)
				{
l0040166B:
					ci8 * eax_177;
					if (eax_161 != 0x00)
					{
						ci8 * edx_200 = *(fp - 0x30);
						eax_177 = edx_200 + eax_161;
						do
						{
							edx_200 = edx_200 + 0x01;
							*(edx_200 - 0x01) = 0x5C;
						} while (edx_200 != eax_177);
					}
					else
						eax_177 = (ci8 *) *(fp - 0x30);
					if ((byte) edi_171 != 0x00 || ecx_112 == 0x7F)
					{
						*eax_177 = 0x7F;
						eax_177 = eax_177 + 0x01;
					}
					*eax_177 = bl_156;
					*(fp - 0x30) = eax_177 + 0x01;
					eax_161 = 0x00;
					al_157 = 0x00;
					goto l00401537;
				}
			}
		}
	}
	word32 edx_214 = *(fp - 0x34);
	edi_171 = DPB(edx_214, edx_214 != 0x00, 0);
	goto l0040166B;
}

void fn004017D0(word32 ecx, word32 ebx)
{
	byte dh_10 = SLICE(SCZDOP, byte, 8);
	if (((SCZDOP ^ 0x00200000 ^ SCZDOP) & 0x00200000) != 0x00)
	{
		word32 eax_49;
		word32 ebx_50;
		word32 ecx_51;
		word32 edx_52;
		__cpuid(0x00, ecx, &eax_49, &ebx_50, &ecx_51, &edx_52);
		if (eax_49 != 0x00)
		{
			word32 eax_70;
			word32 ebx_71;
			word32 ecx_72;
			ui32 edx_73;
			__cpuid(0x01, ecx_51, &eax_70, &ebx_71, &ecx_72, &edx_73);
			if ((dh_10 & 0x01) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x01;
			if ((dh_10 & 0x80) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x02;
			if ((edx_73 & 0x00800000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x04;
			if ((edx_73 & 0x01000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x08;
			if ((edx_73 & 0x02000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x10;
			if ((edx_73 & 0x04000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x20;
			if ((cl & 0x01) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x40;
			word32 ecx_99 = DPB(ecx_72, ch & 0x20, 8);
			if ((ch & 0x20) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x80;
			uint32 eax_106;
			word32 ebx_107;
			word32 ecx_108;
			word32 edx_109;
			__cpuid(0x80000000, ecx_99, &eax_106, &ebx_107, &ecx_108, &edx_109);
			if (eax_106 > 0x80000000)
			{
				word32 eax_113;
				word32 ebx_114;
				word32 ecx_115;
				int32 edx_116;
				__cpuid(0x80000001, ecx_108, &eax_113, &ebx_114, &ecx_115, &edx_116);
				if (edx_116 < 0x00)
					globals->dw40D024 = globals->dw40D024 | 0x0100;
				if ((edx_116 & 0x40000000) != 0x00)
					globals->dw40D024 = globals->dw40D024 | 0x0200;
			}
		}
	}
	return;
}

void fn004018B0()
{
fn004018B0_entry:
l004018B0:
fn004018B0_exit:
}

word32 fn004018F0(word32 esi)
{
	word32 * esp_24 = fp - 0x1C;
	ui32 ebx_14 = globals->dw408240;
	if (ebx_14 == ~0x00)
	{
		ebx_14 = 0x00;
		while (true)
		{
			ui32 eax_48 = ebx_14 + 0x01;
			if ((&globals->dw408240)[eax_48] == 0x00)
				break;
			ebx_14 = eax_48;
		}
	}
	if (ebx_14 != 0x00)
	{
		do
		{
			word32 ebx_32;
			byte SCZO_33;
			byte Z_34;
			byte SZO_35;
			byte C_36;
			word32 esi_37;
			word32 eax_38;
			word32 edx_39;
			(&globals->dw408240)[ebx_14]();
		} while (ebx_32 != 0x01);
	}
	*esp_24 = 4200640;
	return fn004012E0();
}

word32 fn00401940(word32 esi)
{
	if (globals->dw40D028 == 0x00)
	{
		globals->dw40D028 = 0x01;
		return fn004018F0(esi);
	}
	else
		return eax;
}

Eq_43 fn00401C90(Eq_43 ecx, Eq_43 edx, word32 dwArg04, ptr32 & edxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	word32 esp_17;
	word32 esi_18;
	word32 ebx_19;
	byte SCZO_20;
	word32 eax_21;
	word32 ebp_22;
	word32 edi_23;
	word32 ecx_24;
	word32 edx_25;
	byte SZO_26;
	byte C_27;
	byte Z_28;
	msvcrt.dll!fwrite();
	word32 esp_34;
	word32 esi_35;
	word32 ebx_36;
	byte SCZO_37;
	Eq_43 eax_38;
	word32 ebp_39;
	word32 edi_40;
	Eq_43 ecx_41;
	Eq_43 edx_42;
	byte SZO_43;
	byte C_44;
	byte Z_45;
	msvcrt.dll!vfprintf();
	abort();
	word32 edi_52;
	*ediOut = ecx_41;
	word32 esi_55;
	*esiOut = edx_42;
	if (VirtualQuery(eax_38, fp - 0x54, 0x1C) == 0x00)
	{
		word32 edx_86;
		word32 ebx_87;
		word32 ebp_88;
		return fn00401DAB(ecx_41, edx_42, eax_38, out edx_86, out ebx_87, out ebp_88);
	}
	else
	{
		word32 edx_80;
		word32 ebx_81;
		word32 ebp_82;
		word32 esi_83;
		word32 edi_84;
		return fn00401D11(eax_38, fp - 0x20, edx_42, ecx_41, out edx_80, out ebx_81, out ebp_82, out esi_83, out edi_84);
	}
}

Eq_43 fn00401CE0(Eq_43 eax, Eq_43 ecx, Eq_43 edx, ptr32 & edxOut, Eq_1201 * & ebxOut, ptr32 & ebpOut)
{
	if (VirtualQuery(eax, fp - 0x38, 0x1C) == 0x00)
	{
		word32 edx_53;
		word32 ebx_54;
		word32 ebp_55;
		return fn00401DAB(ecx, edx, eax, out edx_53, out ebx_54, out ebp_55);
	}
	else
	{
		word32 edx_41;
		Eq_43 ebx_42;
		word32 * ebp_43;
		Eq_43 esi_44;
		Eq_43 edi_45;
		return fn00401D11(eax, fp - 0x04, edx, ecx, out edx_41, out ebx_42, out ebp_43, out esi_44, out edi_45);
	}
}

word32 fn00401D11(Eq_43 ebx, word32 * ebp, Eq_43 esi, Eq_43 edi, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	*edxOut = edx;
	word32 eax_4 = *(ebp - 0x20);
	if (eax_4 == 0x04 || eax_4 == 0x40)
	{
		v3->t0008 = edi;
		v3->t0004 = esi;
		v3->t0000 = ebx;
		memcpy(v3->t0000, v3->t0004, v3->t0008);
	}
	else
	{
		Eq_43 eax_49 = *(ebp - 0x28);
		v3->t000C = ebp - 0x38;
		v3->t0008.u0 = 0x40;
		*(ebp - 0x3C) = ebp - 0x38;
		v3->t0004 = eax_49;
		v3->t0000 = *(ebp - 0x34);
		VirtualProtect(v3->t0000, v3->t0004, v3->t0008, v3->t000C);
		*(ebp - 0x40) = *(ebp - 0x20);
		v3->t0008 = edi;
		v3->t0004 = esi;
		v3->t0000 = ebx;
		memcpy(v3->t0000, v3->t0004, v3->t0008);
		word32 edx_50;
		*edxOut = ebp - 0x38;
		ecx = *(ebp - 0x40);
		if (ecx != 0x04 && ecx != 0x40)
		{
			Eq_1316 edx_72 = *(ebp - 0x3C);
			*edxOut = edx_72;
			v3->t0008 = *(ebp - 0x38);
			Eq_43 eax_74 = *(ebp - 0x28);
			v3->t000C = edx_72;
			v3->t0004 = eax_74;
			v3->t0000 = *(ebp - 0x34);
			VirtualProtect(v3->t0000, v3->t0004, v3->t0008, v3->t000C);
			word32 ebx_84;
			*ebxOut = *(ebp - 0x0C);
			word32 esi_86;
			*esiOut = *(ebp - 0x08);
			word32 edi_88;
			*ediOut = *(ebp - 0x04);
			word32 ebp_90;
			*ebpOut = *ebp;
			return ecx;
		}
	}
	word32 ebx_28;
	*ebxOut = *(ebp - 0x0C);
	word32 esi_30;
	*esiOut = *(ebp - 0x08);
	word32 edi_32;
	*ediOut = *(ebp - 0x04);
	word32 ebp_34;
	*ebpOut = *ebp;
	return ecx;
}

Eq_43 fn00401DAB(Eq_43 ecx, Eq_43 edx, Eq_43 ebx, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut)
{
	*ebxOut = ebx;
	v3->t0008 = ebx;
	v3->dw0004 = 0x1C;
	v3->dw0000 = 0x0040A0F0;
	Eq_43 edx_9;
	word32 ebp_10;
	word32 esi_11;
	word32 edi_12;
	Eq_43 ecx_13 = fn00401C90(ecx, edx, dwArg00, out edx_9, out ebp_10, out esi_11, out edi_12);
	word32 edx_16;
	word32 ebp_17;
	return fn00401DD0(ecx_13, edx_9, esi_11, edi_12, out edx_16, out ebp_17);
}

Eq_43 fn00401DD0(Eq_43 ecx, Eq_43 edx, word32 esi, word32 edi, ptr32 & edxOut, ptr32 & ebpOut)
{
	*edxOut = edx;
	*ebpOut = ebp;
	if (globals->dw40D05C != 0x00)
		return ecx;
	globals->dw40D05C = 0x01;
	if (true)
		return ecx;
	struct Eq_1520 * ebx_106;
	if (false)
	{
		if ((word32 *) 4237288 != 0x00 || (word32 *) 4237292 != 0x00)
		{
l00401EA0:
			ebx_106 = (struct Eq_1520 *) 4237288;
			goto l00401EA5;
		}
		ecx = (union Eq_43 *) 0x0040A7F0;
		ebx_106 = (struct Eq_1520 *) 0x0040A7F4;
		if (ecx != 0x00)
		{
			ebx_106 = (struct Eq_1520 *) 4237288;
			goto l00401E3C;
		}
	}
	else
		ebx_106 = (struct Eq_1520 *) 4237288;
	edx = ebx_106->dw0000;
	*edxOut = edx;
	if (edx == 0x00)
	{
		if (ebx_106->dw0004 == 0x00)
		{
l00401E3C:
			word32 eax_133 = ebx_106->dw0008;
			if (eax_133 != 0x01)
			{
				word32 edx_241;
				word32 ebp_242;
				word32 esi_243;
				word32 edi_244;
				Eq_43 ecx_245 = fn00401C90(ecx, edx, 4235556, out edx_241, out ebp_242, out esi_243, out edi_244);
				word32 esp_246;
				word32 eax_247;
				byte SZO_248;
				byte C_249;
				byte Z_250;
				byte SCZO_251;
				word32 edi_252;
				word32 esi_253;
				word32 ebx_254;
				word32 ecx_255;
				word32 edx_256;
				byte dl_257;
				byte S_258;
				word16 si_259;
				word32 ebp_260;
				_register_frame_info();
				return ecx_255;
			}
			else
			{
				while (true)
				{
					struct Eq_1573 * ebx_148 = ebx_106 + 0x01;
					if (ebx_148 >= (struct Eq_1573 *) 4237288)
						return ecx;
					Eq_43 ecx_155 = ebx_148->t0000;
					Eq_43 edx_151 = (word32) ebx_148->b0008;
					struct Eq_1587 * esi_153 = ebx_148->ptr0004;
					Eq_1591 edi_159 = *ecx_155;
					if (edx_151 == 0x10)
					{
						ci16 si_214 = (word16) (word32) esi_153->w400000;
						ui32 edx_218 = (word32) si_214;
						if (si_214 < 0x00)
							edx_218 = edx_218 | 0xFFFF0000;
						*(fp - 0x10) = (word32) edi_159;
						word32 edx_231;
						word32 ebp_233;
						ecx = fn00401CE0(&esi_153->w400000, 0x02, fp - 0x10, out edx_231, out ebx_106, out ebp_233);
						continue;
					}
					if (edx_151 != 0x20)
						break;
					*(fp - 0x10) = (union Eq_1615 *) (edi_159 - ecx_155);
					word32 edx_209;
					word32 ebp_211;
					ecx = fn00401CE0(&esi_153->w400000, 0x04, fp - 0x10, out edx_209, out ebx_106, out ebp_211);
				}
				if (edx_151 == 0x08)
				{
					ci8 dl_174 = (byte) (word32) esi_153->w400000;
					ui32 esi_178 = (word32) dl_174;
					if (dl_174 < 0x00)
						esi_178 = esi_178 | ~0xFF;
					*(fp - 0x10) = (word32) edi_159;
					word32 edx_193;
					word32 ebp_195;
					ecx = fn00401CE0(&esi_153->w400000, 0x01, fp - 0x10, out edx_193, out ebx_106, out ebp_195);
					continue;
				}
				else
				{
					*(fp - 0x28) = (union Eq_43 *) edx_151;
					*(fp - 44) = 0x0040A158;
					*(fp - 0x10) = 0x00;
					word32 edx_168;
					word32 ebp_169;
					word32 esi_170;
					word32 edi_171;
					ecx = fn00401C90(ecx_155, edx_151, dwArg00, out edx_168, out ebp_169, out esi_170, out edi_171);
					goto l00401EA0;
				}
			}
		}
	}
l00401EA5:
	if (ebx_106 < (struct Eq_1520 *) 4237288)
	{
		do
		{
			struct Eq_1708 * edx_95 = ebx_106->dw0004;
			*(fp - 0x10) = edx_95->dw400000 + ebx_106->dw0000;
			word32 edx_105;
			word32 ebp_107;
			ecx = fn00401CE0(&edx_95->dw400000, 0x04, fp - 0x10, out edx_105, out ebx_106, out ebp_107);
		} while (ebx_106 < (struct Eq_1520 *) 4237288);
	}
	return ecx;
}

void fn00401FC0(uint32 eax)
{
	struct Eq_1760 * ecx_10 = fp + 0x04;
	if (eax >= 0x1000)
	{
		do
		{
			ecx_10 = ecx_10 - 0x1000;
			ecx_10->dw0000 = ecx_10->dw0000;
			eax = eax - 0x1000;
		} while (eax > 0x1000);
	}
	word32 * ecx_16 = ecx_10 - eax;
	*ecx_16 = *ecx_16;
	return;
}

void fn00401FF0(word32 dwArg04, ptr32 dwArg08)
{
	word32 ebx_15;
	word32 ebp_16;
	word32 esi_17;
	fn00404B80(0x3000, iob + 0x20, 0x00, dwArg04, dwArg08, out ebx_15, out ebp_16, out esi_17);
	return;
}

Eq_43 fn00402030(Eq_43 eax, word32 edx, ptr32 dwArg00, word32 dwArg04, word32 dwArg08)
{
	struct Eq_1818 * ebx_15 = eax;
	if (eax == 0x00)
		return 0x00;
	int32 ecx_62 = (int32) *eax;
	Eq_43 eax_129 = 0x00;
	struct Eq_1818 * edx_148 = eax;
	if (ecx_62 == 0x00)
		return 0x00;
l00402050:
	if (true && ecx_62 == 0x7F)
	{
		edx_148 = ebx_15 + 0x01;
		if (ebx_15->b0000 == 0x00)
			return 0x00;
	}
	if (eax_129 == 0x00)
	{
		if (ecx_62 != 0x3F && ecx_62 != 0x2A)
		{
			eax_129 = (word32) (ecx_62 == 0x5B);
			goto l00402073;
		}
	}
	else if (ecx_62 != 0x5D || eax_129 <= 0x01)
	{
		eax_129 = eax_129;
l00402073:
		ebx_15 = edx_148;
		ecx_62 = (int32) edx_148->b0000;
		edx_148 = edx_148->b0000 + 0x01;
		if (ecx_62 != 0x00)
			goto l00402050;
		return 0x00;
	}
	return eax_129;
	return 0x01;
}

Eq_1872 * fn004020C0(Eq_1872 * eax, ui32 ecx, int32 edx, byte * esi)
{
fn004020C0_entry:
	byte cl_116
	word32 ebx_17 = (word32) eax->b0000
	int32 edi_192 = (int32) (byte) ebx_17
	branch edi_192 == 0x5D l004021B0
	goto l004020D9
l004020C0:
l004020D9:
	cl_116 = (byte) ebx_17
	branch edi_192 != 0x2D l0040210E
	goto l004021B0
l004020E5:
	branch ebx_100 == 0x00 l004021A0
l004020ED:
	branch ebx_100 == 0x5C l004021A0
	branch ebx_100 == 0x5C l004021A0
l004020F6:
	branch ebx_100 == 0x2F l004021A0
	branch ebx_100 == 0x2F l004021A0
l004020FF:
	branch ebx_100 == edx l004021D8
	edi_192 = ebx_100
	cl_116 = (byte) (word32) esi_104->b0000
	eax = esi_104
	branch ebx_100 == edx l004021D8
l0040210E:
	branch (int32) cl_116 == 0x5D l004021A0
	branch (int32) cl_116 == 0x5D l004021A0
	int32 ebx_100 = (int32) cl_116
	struct Eq_1872 * esi_104 = eax + 0x01
	branch ebx_100 == 0x5D l004021A0
l0040211D:
	branch ebx_100 != 0x2D l004020E5
	branch ebx_100 != 0x2D l004020E5
	branch ebx_100 != 0x2D l004020E5
l00402122:
	branch (byte) (word32) eax[0x01] == 0x5D l004021C4
	branch (byte) (word32) eax[0x01] == 0x5D l004021C4
	byte bl_208 = (byte) (word32) eax[0x01]
	branch bl_208 == 0x5D l004021C4
l0040212F:
	int32 ebp_211 = (int32) bl_208
	byte bl_215 = (byte) ebp_211
	branch ebp_211 == 0x00 l004021A0
	int32 ebp_216 = (int32) bl_215
	byte bl_220 = (byte) ebp_216
	branch ebp_216 == 0x00 l004021A0
	int32 ebp_221 = (int32) bl_220
	ebx_100 = ebp_221
	branch ebp_221 == 0x00 l004021A0
l00402138:
	int32 eax_255
	branch edi_192 >= ebp_221 l004022C8
	branch edi_192 >= ebp_221 l004022C8
	esi_104 = eax + 0x02
	branch edi_192 >= ebp_221 l004022C8
l00402143:
	branch edi_192 != edx l0040215E
	branch edi_192 != edx l0040215E
	eax_255 = edi_192 + 0x01
	branch edi_192 != edx l0040215E
	goto l00402210
l00402150:
	eax_255 = eax_255 + 0x01
	branch edx == eax_255 - 0x01 l00402210
l0040215E:
	branch ebp_221 > eax_255 l00402150
	branch ebp_221 > eax_255 l00402150
l00402162:
	branch ebp_221 >= eax_255 l004020ED
	branch ebp_221 >= eax_255 l004020ED
l00402166:
	branch edx == eax_255 l0040217F
	branch edx == eax_255 l0040217F
l00402170:
	branch eax_255 == ebp_221 + 0x02 l004020ED
l00402178:
	eax_255 = eax_255 - 0x01
	branch edx != eax_255 l00402170
l0040217F:
l00402185:
	byte al_281 = (byte) (word32) esi_104->b0000
	branch al_281 == 0x5D l00402233
l00402190:
	branch al_281 == 0x7F l00402255
l00402198:
	esi_104 = esi_104 + 0x01
	branch al_281 != 0x00 l00402185
l004021A0:
	return null
l004021B0:
	branch edi_192 == edx l00402270
l004021B8:
	cl_116 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l0040210E
l004021C4:
	edi_192 = 0x2D
	eax = esi_104
	cl_116 = 0x5D
	branch 0x2D != edx l0040210E
l004021D8:
	goto l004021EA
l004021E0:
	eax = eax + 0x01
	branch cl_116 == 0x00 l004021A0
l004021E7:
	cl_116 = (byte) (word32) eax->b0000
l004021EA:
	branch cl_116 == 0x5D l004022B5
l004021F3:
	branch cl_116 != 0x7F l004021E0
l004021F8:
	branch (ecx & 0x20) != 0x00 l004022C0
l00402200:
	cl_116 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l004021E0
l00402210:
l00402216:
	byte al_338 = (byte) (word32) esi_104->b0000
	branch al_338 == 0x5D l00402233
l0040221D:
	branch al_338 == 0x7F l00402240
l00402221:
	esi_104 = esi_104 + 0x01
	branch al_338 == 0x00 l004021A0
l0040222C:
	al_338 = (byte) (word32) esi_104->b0000
	branch al_338 != 0x5D l0040221D
l00402233:
	return esi_104 + 0x01
l00402240:
	branch (ecx & 0x20) != 0x00 l00402250
l00402244:
	al_338 = (byte) (word32) esi_104[0x01]
	esi_104 = esi_104 + 0x01
	goto l00402221
l00402250:
	esi_104 = esi_104 + 0x01
	goto l00402216
l00402255:
	branch (ecx & 0x20) != 0x00 l00402265
l00402259:
	al_281 = (byte) (word32) esi_104[0x01]
	esi_104 = esi_104 + 0x01
	goto l00402198
l00402265:
	esi_104 = esi_104 + 0x01
	goto l00402185
l00402270:
	eax = eax + 0x01
l00402280:
	byte dl_419 = (byte) (word32) eax->b0000
	branch dl_419 == 0x5D l004022B5
l00402288:
	branch dl_419 == 0x7F l004022A0
l0040228D:
	eax = eax + 0x01
	branch dl_419 != 0x00 l00402280
	goto l004021A0
l004022A0:
	branch (ecx & 0x20) != 0x00 l004022B0
l004022A4:
	dl_419 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l0040228D
l004022B0:
	eax = eax + 0x01
	goto l00402280
l004022B5:
	return eax + 0x01
l004022C0:
	eax = eax + 0x01
	goto l004021E7
l004022C8:
	eax_255 = edi_192
	goto l00402162
fn004020C0_exit:
}

Eq_2125 * fn004022D0(Eq_2125 * eax)
{
	struct Eq_2125 * eax_28;
	if (eax != null)
	{
		int32 eax_54 = eax->dw000C;
		Eq_43 ebp_56 = (eax_54 + 0x01) * 0x04;
		Eq_43 eax_58 = malloc(ebp_56);
		eax->t0008 = eax_58;
		Eq_43 ebx_59 = eax_58;
		eax_28 = (struct Eq_2125 *) 0x03;
		if (eax_58 == 0x00)
			return eax_28;
		eax->dw0004 = 0x00;
		ui32 edx_67 = eax_54 + 0x01;
		if (eax_54 > 0x01)
		{
			Eq_2159 ecx_69 = ebp_56 - 0x04;
			while (true)
			{
				Mem73[ebx_59 + ecx_69:word32] = 0x00;
				ecx_69 = ecx_69 - 0x04;
				edx_67 = edx_67 - 0x01;
				if (edx_67 == 0x00)
					break;
				ebx_59 = eax->t0008;
			}
		}
	}
	eax_28 = null;
	return eax_28;
}

Eq_1872 * fn00402330(Eq_1872 * eax, ui32 ecx, byte * edx)
{
	byte cl_120;
	struct Eq_1872 * eax_151;
	struct Eq_1872 * edi_116 = eax;
	if (*edx != 0x2E)
		cl_120 = (byte) (word32) eax->b0000;
	else
	{
		int32 eax_376 = (int32) eax->b0000;
		if ((byte) eax_376 != 0x2E)
		{
			cl_120 = (byte) eax_376;
			eax_151 = eax_376 - 0x2E;
			if ((ecx & 0x00010000) == 0x00)
				return eax_151;
		}
		else
			cl_120 = 0x2E;
	}
	ptr32 ebp_121 = edx[0x01];
l00402364:
	int32 edx_131 = (int32) cl_120;
	byte * esi_222 = ebp_121 - 0x01;
	struct Eq_1872 * eax_100 = edi_116[0x01];
	if (edx_131 != 0x00)
	{
		if (cl_120 == 0x3F)
		{
			if (*(ebp_121 - 0x01) == 0x00)
			{
				eax_151 = (struct Eq_1872 *) 0x3F;
				return eax_151;
			}
			edi_116 = eax_100;
			goto l00402457;
		}
		if (cl_120 != 0x5B)
		{
			if (cl_120 == 0x2A)
			{
				byte dl_202 = (byte) (word32) edi_116[0x01];
				struct Eq_1872 * ebx_203 = eax_100;
				if (dl_202 == 0x2A)
				{
					do
					{
						ebx_203 = (struct Eq_1872 *) ebx_203[0x01];
						dl_202 = (byte) (word32) ebx_203->b0000;
					} while (dl_202 == 0x2A);
				}
				eax_151 = null;
				if (dl_202 == 0x00)
					return eax_151;
l00402419:
				eax_151 = fn00402330(ebx_203, ecx | 0x00010000, esi_222);
				if (eax_151 != null)
				{
					esi_222 = (byte *) esi_222[0x01];
					if (*(esi_222 - 0x01) != 0x00)
						goto l00402419;
					return eax_151;
				}
				else
				{
					return null;
					return null;
				}
			}
			if ((ecx & 0x20) == 0x00 && edx_131 == 0x7F)
			{
				edx_131 = (int32) edi_116[0x01];
				edi_116 = (struct Eq_1872 *) edi_116[0x02];
				if (edx_131 != 0x00)
				{
l0040239A:
					int32 ebx_135 = (int32) *(ebp_121 - 0x01);
					if ((byte) ebx_135 == 0x00)
					{
						ebx_135 = 0x00;
						goto l004023D6;
					}
					int32 esi_165;
					if ((ecx & 0x4000) == 0x00)
						esi_165 = tolower(edx_131) - tolower(ebx_135);
					else
						esi_165 = edx_131 - ebx_135;
					if (esi_165 != 0x00)
					{
l004023D6:
						eax_151 = edx_131 - ebx_135;
						return eax_151;
					}
l00402457:
					cl_120 = (byte) (word32) edi_116->b0000;
					ebp_121 = ebp_121 + 0x02;
					goto l00402364;
				}
			}
			edi_116 = eax_100;
			goto l0040239A;
		}
		int32 edx_271 = (int32) *(ebp_121 - 0x01);
		if (edx_271 == 0x00)
		{
			eax_151 = (struct Eq_1872 *) 0x5B;
			return eax_151;
		}
		if (edi_116[0x01] != 33)
		{
			struct Eq_1872 * eax_291 = fn004020C0(eax_100, ecx, edx_271, esi_222);
			edi_116 = eax_291;
			if (eax_291 == null)
			{
l0040252E:
				eax_151 = (struct Eq_1872 *) 0x5D;
				return eax_151;
			}
			goto l00402457;
		}
		struct Eq_1872 * ebx_297 = edi_116[0x02];
		if (fn004020C0(ebx_297, ecx, edx_271, esi_222) != null)
		{
			edi_116 = ebx_297;
			goto l00402457;
		}
		byte al_306 = (byte) (word32) edi_116[0x02];
		if (al_306 == 0x5D)
		{
			ebx_297 = (struct Eq_1872 *) edi_116[0x03];
			al_306 = (byte) (word32) edi_116[0x03];
		}
		if (al_306 == 0x5D)
		{
			edi_116 = (struct Eq_1872 *) ebx_297[0x01];
			goto l00402457;
		}
		if (al_306 == 0x7F)
		{
			if ((ecx & 0x20) != 0x00)
			{
				ebx_297 = (struct Eq_1872 *) ebx_297[0x01];
l00402507:
				al_306 = (byte) (word32) ebx_297->b0000;
				goto l0040250A;
			}
			al_306 = (byte) (word32) ebx_297[0x01];
			ebx_297 = (struct Eq_1872 *) ebx_297[0x01];
		}
		ebx_297 = (struct Eq_1872 *) ebx_297[0x01];
		if (al_306 == 0x00)
			goto l0040252E;
		goto l00402507;
	}
	eax_151 = -(int32) *esi_222;
	return eax_151;
}

Eq_43 fn004025B0(Eq_43 eax, Eq_2125 * edx, ptr32 & ecxOut)
{
	*ecxOut = ecx;
	Eq_43 eax_23 = realloc(edx->t0008, (edx->dw0004 + edx->dw000C) * 0x04 + 0x08);
	if (eax_23 == 0x00)
		return 0x01;
	else
	{
		ui32 edi_39 = edx->dw0004;
		edx->t0008 = eax_23;
		int32 eax_41 = edx->dw000C;
		edx->dw0004 = edi_39 + 0x01;
		*eax_23 = eax;
		edx->t0008->u0 = 0x00;
		word32 ecx_42;
		*ecxOut = edi_39 + 0x01;
		return 0x00;
	}
}

void fn00402620(Eq_43 eax, Eq_2125 * edx)
{
	if (eax != 0x00 && edx != null)
	{
		word32 ecx_20;
		fn004025B0(eax, edx, out ecx_20);
		return;
	}
	else
		return;
}

void fn00402640(Eq_43 eax, Eq_2125 * edx)
{
	Eq_43 eax_14 = *eax;
	if (eax_14 != 0x00)
		fn00402640(eax_14, edx);
	fn00402620(*eax, edx);
	Eq_43 eax_20 = *eax;
	if (eax_20 != 0x00)
		fn00402640(eax_20, edx);
	free(eax);
	return;
}

Eq_43 fn00402680(Eq_43 eax, word16 dx, ptr32 ebp)
{
fn00402680_entry:
	Eq_43 eax_23 = strlen(eax)
	word32 eax_26 = eax_23 + 0x10 & ~0x0F
	fn00401FC0(eax_26)
	struct Eq_2519 * esp_29 = fp - 0x7C - eax_26
	Mem32[esp_29 + 0x08:word32] = eax_23 + 0x01
	esp_29->t0004 = eax
	esp_29->t0000 = &esp_29->t0008
	Eq_43 eax_35 = memcpy(esp_29->t0000, esp_29->t0004, esp_29->t0008)
	esp_29->t0000 = eax_35
	Eq_43 eax_38 = fn00402D30(eax_35, dwArg00)
	struct Eq_2559 * ebp_126 = fp - 0x04
	Eq_43 ebx_16 = eax
	Eq_43 eax_102 = fn004022D0(fp - 44)
	branch eax_102 == 0x00 l004026E3
	goto l004026DB
l00402680:
l004026DB:
	return eax_102
l004026E3:
	branch fn00402030(eax_38, edx, ebp, dwArg00, dwArg04) == 0x00 l00402950
l004026F6:
	esp_29->t0000 = fp - 44
	eax_102 = fn00402680(eax_38, DPB(dx, SLICE(edx, byte, 8) | 0x80, 8), fp - 0x04)
l0040270D:
	struct Eq_2519 * esp_107 = esp_29
	branch eax_102 != 0x00 l004026DB
l00402711:
	Eq_43 eax_121
	byte al_112 = (byte) (word32) *eax
	branch al_112 == 0x5C l00402A78
l0040271D:
	bool Z_835 = cond(al_112 - 0x2F)
	branch al_112 == 0x2F l00402A78
l00402725:
	byte * esi_837 = *(fp - 0x4C)
	byte * edi_838 = &globals->b40A184
	word32 ecx_839 = 0x02
l00402732:
	branch ecx_839 == 0x00 l00402734
l00402732_1:
	Z_835 = cond(*esi_971 - *edi_972)
	esi_837 = esi_971 + 0x01
	edi_838 = edi_972 + 0x01
	ecx_839 = ecx_839 - 0x01
	byte * esi_971 = esi_837
	byte * edi_972 = edi_838
	branch *esi_971 != *edi_972 l00402732
l00402734:
	branch Z_835 l00402A78
l0040273A:
	*(fp - 0x61) = 0x5C
l0040273E:
	*(fp - 0x44) = (union Eq_43 *) ebx_16
	*(fp - 0x4C) = 0x00
	branch (*(fp - 0x38) & 0x10) != 0x00 && fn00402030(ebx_16, *(fp - 0x38), ebp, dwArg00, dwArg04) == 0x00 l00402B85
l00402752:
	union Eq_43 * eax_150 = *(fp - 0x24)
	*(fp - 0x3C) = (union Eq_43 **) eax_150
	Eq_43 eax_152 = *eax_150
	branch eax_152 == 0x00 l00402BD3
l00402762:
	ui32 ecx_157 = *(fp - 0x38)
	*(fp - 0x40) = 0x02
	*(fp - 0x6C) = ecx_157 & 0x04
	*(fp - 0x34) = ecx_157 & 0x8000
l00402780:
	branch *(ebp_126 - 0x3C) == 0x01 l004029E2
l0040278A:
	esp_107->t0000 = eax_152
	word32 eax_208 = fn004032A0(dwArg00)
	*(ebp_126 - 44) = eax_208
	branch eax_208 == 0x00 l00402B13
l0040279D:
	branch *(ebp_126 - 0x48) == 0x00 l00402B65
l004027A8:
	esp_107->t0000 = **(ebp_126 - 0x38)
	*(ebp_126 - 0x4C) = (union Eq_43 *) strlen(esp_107->t0000)
l004027B8:
	ui32 eax_217 = *(ebp_126 - 0x34)
	*(ebp_126 - 0x44) = 0x00
	*(ebp_126 - 88) = eax_217 & 0x40
l004027C8:
	esp_107->t0000 = *(ebp_126 - 44)
	struct Eq_2877 * eax_238 = fn00403440(dwArg00, out ebp_126)
	branch eax_238 == null l004029C5
l004027DD:
	branch (*(ebp_126 - 0x30) == 0x00 || eax_238->dw0008 == 0x10) && fn00402330(*(ebp_126 - 0x40), *(ebp_126 - 0x34), eax_238->dw0008 + 0x01) == null l004027EA
	goto l004027C8
l004027E4:
l004027EA:
l004027FE:
	word32 edx_256 = (word32) eax_238->w0006
	word32 ecx_260 = *(ebp_126 - 0x4C)
	*(ebp_126 - 0x50) = (struct Eq_2519 **) esp_107
	ui32 eax_262 = ecx_260 + 0x11 + edx_256
	fn00401FC0(eax_262 & ~0x0F)
	struct Eq_2928 * esp_266 = esp_107 - (eax_262 & ~0x0F)
	*(ebp_126 - 0x54) = &esp_266->t0008
	word32 eax_267 = 0x00
	branch ecx_260 != 0x00 l00402A14
l00402827:
	esp_266->t0008 = edx_256 + 0x01
	esp_266->t0004 = eax_238->dw0008[0x01]
	esp_266->t0000 = (&esp_266->t0008)[eax_267 / 0x0C]
	memcpy(esp_266->t0000, esp_266->t0004, esp_266->t0008)
	esp_266->t0000 = esp_266->t0008
	word32 eax_288 = strlen(esp_266->t0000) + 0x10 & ~0x0F
	fn00401FC0(eax_288)
	union Eq_43 * esp_292 = esp_266 - eax_288
	struct Eq_3041 * esi_291 = *(ebp_126 - 0x54)
	ptr32 edx_296 = esp_292
	goto l0040286D
l00402860:
	edx_296 = edx_296 + 0x01
	*(edx_296 - 0x01) = al_312
	esi_291 = esi_291 + 0x01
	branch al_312 == 0x00 l00402888
l0040286D:
	branch (byte) (word32) esi_291->b0000 != 0x7F l00402860
	byte al_312 = (byte) (word32) esi_291->b0000
	branch al_312 != 0x7F l00402860
l00402874:
	byte al_516 = (byte) (word32) esi_291[0x01]
	byte * edx_518 = edx_296 + 0x01
	*(edx_518 - 0x01) = al_516
	struct Eq_3105 * esi_517 = esi_291 + 0x01
	branch al_516 != 0x00 l0040286D
	byte al_524 = (byte) (word32) esi_517->b0002
	*edx_518 = al_524
	edx_296 = edx_518 + 0x01
	esi_291 = (struct Eq_3041 *) (esi_517->b0002 + 0x01)
	branch al_524 != 0x00 l0040286D
l00402888:
	*esp_292 = esp_292
	branch _strdup(*esp_292) == 0x00 l00402A62
	esp_266->t0000 = esp_292
	Eq_43 eax_326 = _strdup(esp_266->t0000)
	branch eax_326 == 0x00 l00402A62
l0040289C:
	*(ebp_126 - 0x3C) = *(ebp_126 - 0x3C) & (word32) (*(ebp_126 - 0x3C) == 0x02) - 0x01
	branch *(ebp_126 - 88) != 0x00 l00402A53
	*(ebp_126 - 0x3C) = *(ebp_126 - 0x3C) & (word32) (*(ebp_126 - 0x3C) == 0x02) - 0x01
	branch *(ebp_126 - 88) != 0x00 l00402A53
l004028B6:
	int32 ecx_384
	branch *(ebp_126 - 0x44) == 0x00 l00402B7C
	Eq_43 ebx_375 = *(ebp_126 - 0x44)
	branch ebx_375 == 0x00 l00402B7C
l004028C1:
	ui32 edi_422 = *(ebp_126 - 0x34)
	goto l004028E4
l004028D0:
	eax_444 = strcoll(esp_266->t0000, esp_266->t0004)
	ecx_466 = *ebx_375.u0
	edx_451 = *ebx_375.u0
	branch eax_444 <= 0x00 l00402900
l004028DE:
	branch edx_451 == 0x00 l00402906
	branch edx_451 == 0x00 l00402906
l004028E2:
	ebx_375 = edx_451
l004028E4:
	int32 eax_444
	Eq_43 edx_451
	Eq_43 ecx_466
	Eq_43 eax_434 = *ebx_375.u0
	esp_266->t0000 = eax_326
	esp_266->t0004 = eax_434
	branch (edi_422 & 0x4000) != 0x00 l004028D0
l004028F2:
	eax_444 = _stricoll(esp_266->t0000, esp_266->t0004)
	ecx_466 = *ebx_375.u0
	edx_451 = *ebx_375.u0
	branch eax_444 > 0x00 l004028DE
l00402900:
	edx_451 = ecx_466
	branch ecx_466 != 0x00 l004028E2
l00402906:
	ecx_384 = eax_444
l00402908:
	*(ebp_126 - 0x54) = ecx_384
	esp_266->t0000.u0 = 0x0C
	Eq_43 eax_389 = malloc(esp_266->t0000)
	branch eax_389 == 0x00 l0040293D
l0040291B:
	*eax_389 = eax_326
	eax_389->u0 = 0x00
	eax_389->u0 = 0x00
	branch ebx_375 == 0x00 l0040293D
l0040292F:
	branch *(ebp_126 - 0x54) <= 0x00 l00402B50
l0040293A:
	*ebx_375.u0 = eax_389
l0040293D:
	branch *(ebp_126 - 0x44) == 0x00 l00402B5D
l00402948:
	esp_107 = (struct Eq_2519 *) *(ebp_126 - 0x50)
	goto l004027C8
l00402950:
	esp_29->t0000 = eax_38
	word32 eax_883 = strlen(esp_29->t0000) + 0x10 & ~0x0F
	fn00401FC0(eax_883)
	union Eq_43 * esp_890 = esp_29 - eax_883
	Eq_43 edx_886 = eax_38
	ptr32 ecx_893 = esp_890
	goto l00402982
l00402975:
	ecx_893 = ecx_893 + 0x01
	*(ecx_893 - 0x01) = al_908
	edx_886 = edx_886
	branch al_908 == 0x00 l0040299D
l00402982:
	branch (byte) (word32) *edx_886 != 0x7F l00402975
	byte al_908 = (byte) (word32) *edx_886
	branch al_908 != 0x7F l00402975
l00402989:
	byte al_941 = (byte) (word32) *edx_886
	byte * ecx_943 = ecx_893 + 0x01
	*(ecx_943 - 0x01) = al_941
	struct Eq_3283 * edx_942 = edx_886
	branch al_941 != 0x00 l00402982
	byte al_949 = (byte) (word32) edx_942->b0002
	*ecx_943 = al_949
	ecx_893 = ecx_943 + 0x01
	edx_886 = edx_942->b0002 + 0x01
	branch al_949 != 0x00 l00402982
l0040299D:
	*esp_890 = esp_890
	branch _strdup(*esp_890) == 0x00 l004026DB
	esp_29->t0000 = esp_890
	Eq_43 eax_922 = _strdup(esp_29->t0000)
	eax_102.u0 = 0x01
	branch eax_922 == 0x00 l004026DB
l004029B6:
	Eq_43 ecx_933
	fn004025B0(eax_922, fp - 44, out ecx_933)
	word32 ecx_937
	eax_102 = fn004025B0(ecx_933, fp - 44, out ecx_937)
	goto l0040270D
l004029C5:
	esp_107->t0000 = *(ebp_126 - 44)
	fn00403490(dwArg00)
	branch *(ebp_126 - 0x44) == 0x00 l004029E2
l004029D7:
	fn00402640(*(ebp_126 - 0x44), ebp_126->ptr0008)
l004029E2:
	*(ebp_126 - 0x38) = *(ebp_126 - 0x38) + 0x04
	union Eq_43 * edi_197 = *(ebp_126 - 0x38)
	esp_107->t0000 = *(edi_197 - 0x04)
	free(esp_107->t0000)
	eax_152 = *edi_197
	branch eax_152 != 0x00 l00402780
l004029FE:
	eax_121 = *(ebp_126 - 0x20)
l00402A01:
	esp_107->t0000 = eax_121
	free(esp_107->t0000)
	return *(ebp_126 - 0x3C)
l00402A14:
	union Eq_43 * eax_544 = *(ebp_126 - 0x38)
	Eq_43 esi_545 = *(ebp_126 - 0x4C)
	*(ebp_126 - 100) = edx_256
	Eq_43 eax_547 = *eax_544
	esp_266->t0008 = esi_545
	esp_266->t0000 = &esp_266->t0008
	esp_266->t0004 = eax_547
	memcpy(esp_266->t0000, esp_266->t0004, esp_266->t0008)
	byte al_553 = (byte) (word32) Mem550[esp_266 + 11 + esi_545:byte]
	edx_256 = *(ebp_126 - 100)
	branch al_553 == 0x5C || al_553 == 0x2F l00402A70
	goto l00402A3F
l00402A3B:
l00402A3F:
	int32 esi_566 = *(ebp_126 - 0x4C)
	(&esp_266->t0008)[esi_566 / 0x0C] = (struct Eq_2928) (byte) (word32) *(ebp_126 - 0x5D)
	eax_267 = esi_566 + 0x01
	goto l00402827
l00402A53:
	fn00402620(eax_326, ebp_126->ptr0008)
	goto l00402948
l00402A62:
	*(ebp_126 - 0x3C) = 0x03
	goto l00402948
l00402A70:
	eax_267 = *(ebp_126 - 0x4C)
	goto l00402827
l00402A78:
	esp_29->t0000 = *(fp - 0x4C)
	word32 eax_733 = strlen(esp_29->t0000) + eax
	branch eax >= eax_733 l00402C21
l00402A8D:
	byte dl_795 = (byte) (word32) *eax_733
	branch dl_795 == 0x2F l00402C16
l00402A99:
	branch dl_795 != 0x5C l00402ABB
	goto l00402C16
l00402AA5:
	byte al_818 = (byte) (word32) (eax_733 - (struct <anonymous> *) 0x01)->b0000
	branch al_818 == 0x5C || al_818 == 0x2F l00402B71
	goto l00402AB9
l00402AB1:
l00402AB9:
	eax_733 = edx_807
l00402ABB:
	Eq_43 edx_807 = eax_733 - (struct <anonymous> *) 0x01
	branch edx_807 != eax l00402AA5
l00402AC2:
	byte al_814 = (byte) (word32) (eax_733 - (struct <anonymous> *) 0x01)->b0000
	*(fp - 0x44) = (union Eq_43 *) edx_807
	*(fp - 0x61) = al_814
l00402ACC:
	branch *(fp - 0x61) != 0x5C && *(fp - 0x61) != 0x2F l00402BE2
l00402AD6:
	struct Eq_3747 * eax_759 = *(fp - 0x44)
	word32 edx_764 = (word32) eax_759->b0001
	byte cl_761 = (byte) (word32) *(fp - 0x61)
	byte * eax_762 = &eax_759->b0001
	byte dl_765 = (byte) edx_764
	branch dl_765 != 0x5C l00402AF5
l00402AE8:
	eax_762 = eax_762 + 0x01
	edx_764 = (word32) *eax_762
	cl_761 = (byte) edx_764
	dl_765 = (byte) edx_764
	branch dl_765 == 0x5C l00402AE8
l00402AF5:
	branch dl_765 == 0x2F l00402AE8
l00402AFA:
	*(fp - 0x44) = (byte **) eax_762
	*(fp - 0x61) = cl_761
l00402B00:
	branch *(fp - 0x4C) != 0x00 l00402752
l00402B0B:
	ebx_16 = *(fp - 0x44)
	goto l0040273E
l00402B13:
	word32 ebx_590 = *(ebp_126 - 0x68)
	branch ebx_590 != 0x00 l00402B42
l00402B1A:
	<anonymous> * edi_612 = *(ebp_126 - 0x5C)
	branch edi_612 == null l004029E2
l00402B25:
	esp_107->t0004 = *_errno()
	Eq_43 eax_620 = **(ebp_126 - 0x38)
	esp_107->t0000 = eax_620
	word32 edi_624
	word32 esi_625
	word32 ebx_626
	word32 eax_627
	byte SCZO_628
	word32 edx_629
	word32 ecx_630
	byte SZO_631
	byte C_632
	byte Z_633
	byte dh_634
	byte al_635
	byte cl_636
	byte dl_637
	word16 dx_638
	edi_612()
	branch eax_627 == 0x00 l004029E2
l00402B42:
	*(ebp_126 - 0x3C) = 0x01
	goto l004029E2
l00402B50:
	word32 edi_415 = *(ebp_126 - 0x44)
	*ebx_375.u0 = eax_389
	branch edi_415 != 0x00 l00402948
l00402B5D:
	*(ebp_126 - 0x44) = (union Eq_43 *) eax_389
	goto l00402948
l00402B65:
	*(ebp_126 - 0x4C) = 0x00
	goto l004027B8
l00402B71:
	*(fp - 0x44) = (union Eq_43 *) edx_807
	*(fp - 0x61) = al_818
	goto l00402ACC
l00402B7C:
	ebx_375.u0 = 0x00
	ecx_384 = 0x00
	goto l00402908
l00402B85:
l00402B97:
	esp_29->t0000 = ebx_16
	word32 eax_672 = strlen(esp_29->t0000) + 0x10 & ~0x0F
	fn00401FC0(eax_672)
	union Eq_43 * esp_675 = esp_29 - eax_672
	ptr32 edx_679 = esp_675
	goto l00402BC3
l00402BB6:
	edx_679 = edx_679 + 0x01
	*(edx_679 - 0x01) = al_695
	ebx_16 = ebx_16
	branch al_695 == 0x00 l00402BF5
l00402BC3:
	branch (byte) (word32) *ebx_16 != 0x7F l00402BB6
	byte al_695 = (byte) (word32) *ebx_16
	branch al_695 != 0x7F l00402BB6
l00402BCA:
	struct Eq_3630 * ebx_719 = ebx_16
	al_695 = (byte) (word32) ebx_719->b0001
	ebx_16 = &ebx_719->b0001
	goto l00402BB6
l00402BD3:
	eax_121 = *(fp - 0x3C)
	*(fp - 0x40) = 0x02
	goto l00402A01
l00402BE2:
l00402BEC:
	*(fp - 0x61) = 0x5C
	goto l00402B00
l00402BF5:
	*esp_675 = esp_675
	fn00402620(_strdup(*esp_675), fp->ptr0004)
	eax_121 = *(fp - 0x24)
	*(fp - 0x40) = 0x00
	esp_107 = esp_29
	goto l00402A01
l00402C16:
	*(fp - 0x61) = dl_795
	*(fp - 0x44) = (union Eq_43 *) eax_733
	goto l00402ACC
l00402C21:
	byte cl_830 = (byte) (word32) *eax_733
	*(fp - 0x44) = (union Eq_43 *) eax_733
	*(fp - 0x61) = cl_830
	goto l00402ACC
fn00402680_exit:
}

Eq_43 fn00402C30(word32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10)
{
	Eq_43 ebx_148 = dwArg04;
	if (dwArg10 != null && (dwArg08 & 0x02) == 0x00)
		dwArg10->dw000C = 0x00;
	if (dwArg10->dw0000 != 4235654)
	{
		fn004022D0(dwArg10);
		dwArg10->dw0000 = 4235654;
	}
	Eq_43 eax_36 = fn00402680(dwArg04, (word16) dwArg08, fp - 0x04);
	if (eax_36 == 0x02 && (dwArg08 & 0x10) != 0x00)
	{
		*(fp - 0x24) = (union Eq_43 *) eax_36;
		*(fp - 0x20) = fp - 44;
		*(fp - 44) = (union Eq_43 *) dwArg04;
		word32 eax_77 = strlen(*(fp - 44)) + 0x10 & ~0x0F;
		fn00401FC0(eax_77);
		union Eq_43 * esp_81 = fp - 44 - eax_77;
		word32 ecx_80 = *(fp - 0x24);
		ptr32 edx_146 = esp_81;
		do
		{
			byte al_96 = (byte) (word32) *ebx_148;
			if (al_96 == 0x7F)
			{
				byte al_136 = (byte) (word32) *ebx_148;
				byte * edx_138 = edx_146 + 0x01;
				*(edx_138 - 0x01) = al_136;
				struct Eq_3964 * ebx_137 = ebx_148;
				byte al_144 = (byte) (word32) ebx_137->b0002;
				*edx_138 = al_144;
				edx_146 = edx_138 + 0x01;
				ebx_148 = ebx_137->b0002 + 0x01;
				if (al_144 == 0x00)
					break;
				continue;
			}
			edx_146 = edx_146 + 0x01;
			*(edx_146 - 0x01) = al_96;
			ebx_148 = ebx_148;
		} while (al_96 == 0x00);
		*(fp - 0x24) = ecx_80;
		*esp_81 = esp_81;
		fn00402620(_strdup(*esp_81), dwArg10);
		Eq_43 ecx_109 = *(fp - 0x24);
		struct Eq_2125 * esi_113 = *(fp - 0x0C);
		Eq_43 edi_115 = *(fp - 0x08);
		ptr32 ebp_117 = *(fp - 0x04);
		return ecx_109;
		*(ebp_117 - 0x20) = (union Eq_43 *) ecx_109;
		*fp = (union Eq_43 *) edi_115;
		fn00402620(_strdup(*fp), esi_113);
		return *(ebp_117 - 0x20);
	}
	else
		return eax_36;
}

Eq_43 fn00402D30(Eq_43 eax, word32 dwArg04)
{
fn00402D30_entry:
	struct Eq_4044 * esp_21
	word32 ebp_22
	word32 edi_23
	word32 esi_24
	word32 ebx_25
	byte SCZO_26
	Eq_43 eax_27
	byte SZO_28
	byte C_29
	byte Z_30
	word32 edx_31
	word32 ecx_32
	word16 cx_33
	word16 ax_34
	byte CZ_35
	word16 dx_36
	word16 di_37
	msvcrt.dll!setlocale()
	branch eax_27 == 0x00 l00402D60
	goto l00402D56
l00402D30:
l00402D56:
	esp_21->t0000 = eax_27
	_strdup(esp_21->t0000)
l00402D60:
	esp_21->dw0004 = 0x0040A198
	esp_21->t0000.u0 = 0x02
	struct Eq_4072 * esp_44
	word32 ebp_45
	word32 edi_46
	Eq_43 esi_47
	Eq_43 ebx_48
	byte SCZO_49
	word32 eax_50
	byte SZO_51
	byte C_52
	byte Z_53
	word32 edx_54
	word32 ecx_55
	word16 cx_56
	word16 ax_57
	byte CZ_58
	word16 dx_59
	word16 di_60
	msvcrt.dll!setlocale()
	branch esi_47 == 0x00 || *esi_47 == 0x00 l00402D7D
	goto l00402DF0
l00402D78:
l00402D7D:
	esp_44->t0008.u0 = 0x00
	esp_44->t0004.u0 = 0x0040A19A
	esp_44->t0000.u0 = 0x00
	Eq_43 eax_103 = wcstombs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	Mem105[esp_44 + 0x04:word32] = eax_103 + 0x01
	esp_44->t0000 = globals->t40D068
	Eq_43 eax_108 = realloc(esp_44->t0000, esp_44->t0004)
	globals->t40D068 = eax_108
	Mem110[esp_44 + 0x08:word32] = eax_103 + 0x01
	esp_44->t0004.u0 = 0x0040A19A
	esp_44->t0000 = eax_108
	Eq_43 eax_113 = wcstombs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	esp_44->t0004 = ebx_48
	esp_44->t0000.u0 = 0x02
	union Eq_43 * esp_116
	word32 ebp_117
	word32 edi_118
	word32 esi_119
	Eq_43 ebx_120
	byte SCZO_121
	word32 eax_122
	byte SZO_123
	byte C_124
	byte Z_125
	word32 edx_126
	word32 ecx_127
	word16 cx_128
	word16 ax_129
	byte CZ_130
	word16 dx_131
	word16 di_132
	msvcrt.dll!setlocale()
	*esp_116 = (union Eq_43 *) ebx_120
	free(*esp_116)
	return globals->t40D068
l00402DF0:
	Eq_4212 dwLoc28_215
	esp_44->t0008.u0 = 0x00
	esp_44->t0004 = esi_47
	esp_44->t0000.u0 = 0x00
	Eq_43 eax_151 = mbstowcs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	word32 eax_153 = eax_151 + 0x12 + eax_151
	fn00401FC0(eax_153 & ~0x0F)
	struct Eq_4248 * esp_157 = esp_44 - (eax_153 & ~0x0F)
	esp_157->t0008 = eax_151
	esp_157->t0004 = esi_47
	word32 v13_160 = esp_157 + 0x0D >>u 0x01
	esp_157->t0000 = v13_160 * 0x02
	Eq_43 eax_169 = mbstowcs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	(eax_169 * 0x02)[v13_160] = 0x00
	word32 eax_177 = (word32) null[v13_160]
	word16 ax_178 = (word16) eax_177
	word16 wLoc2A_179 = ax_178
	branch eax_169 <= 0x01 l00402F4E
l00402E5C:
	branch ax_178 == 0x5C || ax_178 == 0x2F l00402E6C
	goto l00402F76
l00402E62:
l00402E6C:
	dwLoc28_215 = v13_160 * 0x02
	branch ax_178 == Mem172[(v13_160 + 0x02) + v13_160:word16] && Mem172[(v13_160 + 0x04) + v13_160:word16] == 0x00 l004030CF
l00402E80:
	word16 ax_220 = (word16) (word32) wLoc2A_179
	branch ax_220 == 0x00 l00403087
l00402E8D:
	Eq_4212 edx_224 = dwLoc28_215
	Eq_4212 edi_226 = dwLoc28_215
	goto l00402EA8
l00402E94:
	branch ax_220 == 0x2F l00402EBA
l00402E9A:
	ax_220 = (word16) (word32) *edx_224
	ecx_484 = *edx_224
	branch ax_220 == 0x00 l00402EDC
l00402EA6:
	edx_224 = ecx_484
l00402EA8:
	word16 ax_497
	Eq_4212 ecx_484
	branch ax_220 != 0x5C l00402E94
l00402EAE:
	ax_497 = (word16) (word32) *edx_224
	branch ax_497 != 0x5C l00402EC3
l00402EB7:
	edx_224 = edx_224
l00402EBA:
	ax_497 = (word16) (word32) *edx_224
	branch ax_497 == 0x5C l00402EB7
l00402EC3:
	branch ax_497 == 0x2F l00402EB7
l00402EC9:
	branch ax_497 == 0x00 l00402EDC
l00402ECE:
	ax_220 = (word16) (word32) *edx_224
	edi_226 = edx_224
	ecx_484 = edx_224
	branch ax_220 != 0x00 l00402EA6
l00402EDC:
	branch dwLoc28_215 < edi_226 l00402F61
l00402EE3:
	word16 * eax_258
	branch wLoc2A_179 == 0x5C || wLoc2A_179 == 0x2F l00402EF5
	goto l004030AF
l00402EEA:
l00402EF5:
	eax_258 = (word16 *) dwLoc28_215
l00402EFB:
	*eax_258 = 0x00
	esp_157->t0008.u0 = 0x00
	esp_157->t0000.u0 = 0x00
	esp_157->t0004 = v13_160 * 0x02
	Eq_43 eax_269 = wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	Mem271[esp_157 + 0x04:word32] = eax_269 + 0x01
	esp_157->t0000 = globals->t40D068
	Eq_43 eax_274 = realloc(esp_157->t0000, esp_157->t0004)
	globals->t40D068 = eax_274
	Mem277[esp_157 + 0x08:word32] = eax_269 + 0x01
	esp_157->t0000 = eax_274
	esp_157->t0004 = v13_160 * 0x02
	wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	goto l00403037
l00402F4E:
	dwLoc28_215 = v13_160 * 0x02
	goto l00402E80
l00402F59:
	branch dx_473 != 0x2F l00402FA5
l00402F5F:
	edi_226 = eax_302
l00402F61:
	Eq_4212 eax_302 = edi_226 - 0x02
	branch dwLoc28_215 >= eax_302 l00402FA5
l00402F68:
	word16 dx_473 = (word16) (word32) *(edi_226 - 0x02)
	branch dx_473 != 0x5C l00402F59
l00402F72:
	edi_226 = eax_302
	goto l00402F61
l00402F76:
	dwLoc28_215 = v13_160 * 0x02
	branch Mem172[v13_160 + 0x02 + v13_160:word16] != 0x3A l00402E80
l00402F8B:
	dwLoc28_215 = v13_160 * 0x02 + 0x04
	wLoc2A_179 = (word16) (word32) Mem172[v13_160 + 0x04 + v13_160:word16]
	goto l00402E80
l00402FA5:
	branch dwLoc28_215 == eax_302 l004030E5
l00402FAE:
	*eax_302 = 0x00
	word16 dx_318 = (word16) (word32) null[v13_160]
	struct Eq_4502 * eax_319 = v13_160 * 0x02
	branch dx_318 != 0x5C && dx_318 != 0x2F l0040308F
l00402FC8:
	eax_319 = eax_319 + 0x01
	word16 cx_439 = (word16) (word32) eax_319->w0000
	branch cx_439 == 0x5C || cx_439 == 0x2F l00402FC8
	goto l00402FDA
l00402FD4:
l00402FDA:
	branch eax_319 - v13_160 * 0x02 <= 0x05 l00403099
l00402FE8:
	eax_319 = v13_160 * 0x02
l00402FEB:
	struct Eq_4502 * ecx_331 = eax_319
l00402FED:
	branch dx_318 == 0x00 l00403013
l00402FF2:
	ecx_331 = ecx_331 + 0x01
	*(ecx_331 - 0x02) = dx_318
	branch dx_318 == 0x2F l00403062
l00402FFF:
	word32 edi_402 = eax_319 + 0x02
	branch eax_319->w0000 == 0x5C l00403060
l00403008:
	dx_318 = (word16) (word32) eax_319[0x01]
	eax_319 = edi_402
	branch dx_318 != 0x00 l00402FF2
l00403013:
	ecx_331->w0000 = 0x00
	esp_157->t0008 = eax_169
	esp_157->t0000 = esi_47
	esp_157->t0004 = v13_160 * 0x02
	Eq_43 eax_360 = wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	branch eax_360 == ~0x00 l00403037
l00403033:
	Mem364[esi_47 + eax_360:byte] = 0x00
l00403037:
	esp_157->t0004 = ebx_48
	esp_157->t0000.u0 = 0x02
	union Eq_43 * esp_184
	word32 ebp_185
	word32 edi_186
	Eq_43 esi_187
	Eq_43 ebx_188
	byte SCZO_189
	word32 eax_190
	byte SZO_191
	byte C_192
	byte Z_193
	word32 edx_194
	word32 ecx_195
	word16 cx_196
	word16 ax_197
	byte CZ_198
	word16 dx_199
	word16 di_200
	msvcrt.dll!setlocale()
	*esp_184 = (union Eq_43 *) ebx_188
	free(*esp_184)
	return esi_187
l00403060:
	eax_319 = edi_402
l00403062:
	dx_318 = (word16) (word32) eax_319->w0000
	branch dx_318 != 0x2F l004030C4
l00403070:
	eax_319 = eax_319 + 0x02
	dx_318 = (word16) (word32) eax_319->w0000
	branch dx_318 == 0x5C || dx_318 == 0x2F l00403070
	goto l00402FED
l0040307C:
l0040308F:
l00403099:
	branch Mem315[v13_160 + 0x02 + v13_160:word16] != dx_318 l00402FE8
	branch Mem315[v13_160 + 0x02 + v13_160:word16] != dx_318 l00402FE8
l004030A7:
	dx_318 = (word16) (word32) eax_319->w0000
	goto l00402FEB
l004030AF:
	*dwLoc28_215 = 0x2E
	eax_258 = (word16 *) dwLoc28_215
	goto l00402EFB
l004030C4:
	branch dx_318 == 0x5C l00403070
	goto l00402FED
l004030CF:
l004030E5:
	branch wLoc2A_179 == 0x5C l004030FA
l004030EC:
	eax_302 = dwLoc28_215
	branch wLoc2A_179 != 0x2F l00402FAE
l004030FA:
	eax_302 = dwLoc28_215
	branch *dwLoc28_215 != (word16) ((word32) wLoc2A_179) l00402FAE
l0040310B:
	word16 dx_459 = (word16) (word32) *dwLoc28_215
	branch dx_459 == 0x2F l00402FAE
l00403119:
	eax_302 = edi_226
	branch dx_459 != 0x5C l00402FAE
l00403125:
	eax_302 = dwLoc28_215
	goto l00402FAE
fn00402D30_exit:
}

Eq_43 fn00403130(Eq_43 eax, word16 dx)
{
	if (FindNextFileA(eax, fp + 4294966964) != 0x00)
	{
		Eq_43 ebx_65;
		struct Eq_4674 * ebp_66;
		struct Eq_4675 * esi_67;
		word16 ax_68 = fn004054F0(edx + 0x0C, 0x0104, 0x0040A1A0, out ebx_65, out ebp_66, out esi_67);
		esi_67->w0006 = ax_68;
		word32 eax_70 = ebp_66->dwFFFFFEB8;
		uint32 eax_73 = DPB(eax_70, (byte) eax_70 & 88, 0);
		if (eax_73 <= 0x10)
		{
			esi_67->dw0008 = eax_73;
			return ebx_65;
		}
		else
		{
			esi_67->dw0008 = 0x18;
			return ebx_65;
		}
	}
	else
	{
		if (GetLastError() != 0x12)
			*_errno() = 0x02;
		return 0x00;
	}
}

Eq_43 fn004031D0(Eq_43 eax, Eq_43 edx)
{
	Eq_43 eax_19 = FindFirstFileA(eax, fp + 4294966964);
	Eq_43 esi_24 = eax_19;
	if (eax_19 != ~0x00)
	{
		struct Eq_4752 * ebx_52;
		struct Eq_4753 * ebp_53;
		word16 ax_55 = fn004054F0(edx, 0x0104, 0x0040A1A0, out ebx_52, out ebp_53, out esi_24);
		word32 ecx_56 = ebp_53->dwFFFFFEB8;
		ebx_52->w0006 = ax_55;
		uint32 ecx_59 = DPB(ecx_56, (byte) ecx_56 & 88, 0);
		ebx_52->dw0008 = ecx_59;
		if (ecx_59 > 0x10)
			ebx_52->dw0008 = 0x18;
	}
	else
	{
		Eq_43 eax_65 = _errno();
		Eq_43 eax_67 = GetLastError();
		*eax_65 = eax_67;
		if (eax_67 != 0x03)
		{
			if (*_errno() != 0x010B)
			{
				if (*_errno() != 0x02)
				{
					*_errno() = 22;
					esi_24 = eax_19;
				}
			}
			else
				*_errno() = 0x14;
		}
		else
			*_errno() = 0x02;
	}
	return esi_24;
}

Eq_43 fn004032A0(word32 dwArg04)
{
	esp = fp;
	esp = fp - 0x04;
	dwLoc04 = ebp;
	esp = fp - 0x08;
	dwLoc08 = edi;
	esp = fp - 0x0C;
	dwLoc0C = esi;
	esp = fp - 0x10;
	dwLoc10 = ebx;
	esp = fp - 0x013C;
	eax = dwArg04;
	SZO = cond(eax & eax);
	Z = SZO;
	C.u0 = false;
	if (Test(EQ,Z))
	{
		eax = _errno();
		*eax = 22;
		eax.u0 = 0x00;
		SZO = cond(0x00);
		C.u0 = false;
		goto l004033CD;
	}
	SCZO = cond(*eax.u0 - 0x00);
	if (Test(EQ,Z))
	{
		eax = _errno();
		*eax.u0 = 0x02;
		eax.u0 = 0x00;
		SZO = cond(0x00);
		C.u0 = false;
		goto l004033CD;
	}
	edi = fp - 288;
	dwLoc0134.u0 = 0x0104;
	ebx = fp - 288;
	dwLoc0138 = eax;
	dwLoc013C = fp - 288;
	eax = _fullpath(dwLoc013C, dwLoc0138, 0x0104);
	SCZO = cond(bLoc0120 - 0x00);
	if (Test(NE,Z))
	{
		do
		{
			edx = *ebx;
			ebx = ebx;
			eax = edx;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
		SZO = cond(eax & 0x8080);
		C.u0 = false;
		if (Test(NE,Z))
		{
			al = al + al;
			SCZO = cond(al);
			ebx = ebx - 0x03 - C;
			ebx = ebx - (fp - 288);
			eax = (word32) Mem0[fp - 0x0121 + ebx:byte];
			SCZO = cond(al - 0x5C);
			if (Test(EQ,Z))
				goto l00403364;
		}
		else
		{
			eax = eax >> 0x10;
			ebx = ebx;
			al = al + al;
			SCZO = cond(al);
			ebx = ebx - 0x03 - C;
			ebx = ebx - (fp - 288);
			eax = (word32) Mem0[fp - 0x0121 + ebx:byte];
			SCZO = cond(al - 0x5C);
			if (Test(EQ,Z))
				goto l00403364;
		}
		SCZO = cond(al - 0x2F);
		if (Test(EQ,Z))
		{
l00403364:
			edx.u0 = 0x2A;
			eax = *ebx;
			Mem0[fp - 288 + ebx:word16] = dx;
			dwLoc013C = eax;
			eax = malloc(dwLoc013C);
			SZO = cond(eax & eax);
			C.u0 = false;
			esi = eax;
			if (Test(NE,Z))
			{
				ebp = *eax.u0;
				ebx = *ebx;
				SCZO = cond(ebx);
				dwLoc0134 = ebx;
				dwLoc0138 = fp - 288;
				dwLoc013C = ebp;
				eax = memcpy(dwLoc013C, dwLoc0138, dwLoc0134);
				edx = esi;
				eax = ebp;
				eax = fn004031D0(eax, edx);
				SCZO = cond(eax - ~0x00);
				*esi = eax;
				if (Test(NE,Z))
				{
					eax.u0 = 0x0110;
					esi->u1 = ax;
					eax = esi;
					*esi = 0x00;
					*esi = 0x00;
				}
				else
				{
					*esp = esi;
					free(*esp);
					eax.u0 = 0x00;
					SZO = cond(0x00);
					C.u0 = false;
				}
			}
			else
			{
				eax = _errno();
				*eax.u0 = 0x0C;
				eax.u0 = 0x00;
				SZO = cond(0x00);
				C.u0 = false;
			}
l004033CD:
			esp = *esp;
			SCZO = cond(esp);
			ebx = *esp;
			esp = *esp;
			esi = *esp;
			esp = *esp;
			edi = *esp;
			esp = *esp;
			ebp = *esp;
			esp = *esp;
			return eax;
		}
		ecx = 0x5C;
		Mem0[fp - 288 + ebx:word16] = cx;
		ebx = fp - 288;
		do
		{
			edx = *ebx;
			ebx = *ebx;
			eax = *edx.u0;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
	}
	else
	{
		do
		{
			edx = *ebx;
			ebx = ebx;
			eax = edx;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
	}
	SZO = cond(eax & 0x8080);
	SZO = cond(eax & 0x8080);
	C.u0 = false;
	if (Test(EQ,Z))
	{
		eax = eax >> 0x10;
		ebx = *ebx;
		SCZO = cond(ebx);
	}
	al = al + al;
	SCZO = cond(al);
	ebx = ebx - 0x03 - C;
	ebx = ebx - (fp - 288);
	al = al + al;
	SCZO = cond(al);
	ebx = ebx - 0x03 - C;
	ebx = ebx - (fp - 288);
	SCZO = cond(ebx);
	goto l00403364;
}

Eq_5108 * fn00403440(word32 dwArg04, ptr32 & ebpOut)
{
	*ebpOut = ebp;
	struct Eq_5108 * eax_16;
	if (dwArg04 == null)
	{
		*_errno() = 0x09;
		eax_16 = null;
		return eax_16;
	}
	int32 eax_24 = dwArg04->dw0114;
	dwArg04->dw0114 = eax_24 + 0x01;
	if (eax_24 > 0x00)
	{
		eax_16 = fn00403130(dwArg04->t0110, (word16) dwArg04);
		if (eax_16 == null)
			return eax_16;
	}
	eax_16 = dwArg04;
	return eax_16;
}

void fn00403490(word32 dwArg04)
{
	if (dwArg04 != 0x00 && FindClose(*dwArg04) != 0x00)
		free(dwArg04);
	else
		*_errno() = 0x09;
	return;
}

void fn004036E0(Eq_5162 al, Eq_5163 * edx)
{
	int32 ebx_33;
	byte ch_9 = edx->b0005;
	if ((ch_9 & 0x20) == 0x00)
	{
		ebx_33 = edx->dw0018;
		if (edx->dw001C <= ebx_33)
			goto l00403704;
	}
	if ((ch_9 & 0x10) != 0x00)
	{
		word32 esp_59;
		word32 ebx_60;
		byte SCZO_61;
		word32 ecx_62;
		word32 edx_63;
		byte ch_64;
		byte SZO_65;
		byte C_66;
		byte Z_67;
		byte al_68;
		word32 eax_69;
		msvcrt.dll!fputc();
		edx->dw0018 = edx->dw0018 + 0x01;
		return;
	}
	edx->ptr0000[edx->dw0018].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00] = al;
	ebx_33 = edx->dw0018;
l00403704:
	edx->dw0018 = ebx_33 + 0x01;
	return;
}

word32 fn00404B80(word32 dwArg04, ptr32 dwArg08, word32 dwArg0C, word32 dwArg10, word32 dwArg14, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	*ebpOut = ebp;
	*esiOut = esi;
	*ebxOut = ebx;
	struct Eq_5227 * esi_145 = dwArg10;
	char * eax_39 = getenv("PRINTF_EXPONENT_DIGITS");
l00404C10:
	int32 eax_143 = (int32) esi_145->b0000;
	struct Eq_5227 * ebx_144 = esi_145[0x01];
	Eq_5162 al_134 = (byte) eax_143;
	struct Eq_5227 * ecx_137 = ebx_144;
	if (eax_143 != 0x00)
	{
		do
		{
			if (eax_143 != 0x25)
			{
				fn004036E0(al_134, fp - 0x40);
				esi_145 = ebx_144;
				goto l00404C10;
			}
			word32 eax_149 = fp->dw0004;
			*(fp - 0x34) = ~0x00;
			*(fp - 0x38) = ~0x00;
			*(fp - 88) = 0x00;
			*(fp - 0x3C) = eax_149;
			word32 edx_154 = (word32) esi_145[0x01];
			*(fp - 0x54) = fp - 0x38;
			*(fp - 0x5C) = 0x00;
			byte dl_155 = (byte) edx_154;
			while (dl_155 != 0x00)
			{
				cu8 al_176 = (byte) (edx_154 - 0x20);
				int32 edi_177 = (int32) dl_155;
				struct Eq_5227 * esi_180 = ecx_137[0x01];
				if (al_176 <= 0x5A)
				{
					ui32 eax_181 = (word32) al_176;
					word32 esp_185;
					word32 ebp_186;
					word32 edi_187;
					word32 esi_188;
					word32 ebx_189;
					byte SCZO_190;
					word32 eax_191;
					byte SZO_192;
					byte C_193;
					word16 ax_194;
					byte Z_195;
					byte CZ_196;
					byte ah_197;
					word32 ecx_198;
					word32 edx_199;
					byte dl_200;
					byte al_201;
					byte S_202;
					(*globals->a40A1D8)();
					return eax_191;
				}
				word32 eax_203 = *(fp - 0x5C);
				if (eax_203 == 0x04 || (byte) (edx_154 - 0x30) > 0x09)
				{
					fn004036E0(0x25, fp - 0x40);
					esi_145 = ebx_144;
					goto l00404C10;
				}
				if (eax_203 != 0x00)
				{
					if (eax_203 == 0x02)
						*(fp - 0x5C) = 0x03;
				}
				else
					*(fp - 0x5C) = 0x01;
				if (*(fp - 0x54) != 0x00)
				{
					int32 eax_240 = **(fp - 0x54);
					if (eax_240 < 0x00)
					{
						**(fp - 0x54) = edi_177 - 0x30;
						edx_154 = (word32) ecx_137[0x01];
						dl_155 = (byte) edx_154;
						ecx_137 = esi_180;
						continue;
					}
					**(fp - 0x54) = edi_177 - 0x30 + (eax_240 * 0x05) * 0x02;
				}
				edx_154 = (word32) ecx_137[0x01];
				dl_155 = (byte) edx_154;
				ecx_137 = esi_180;
			}
			eax_143 = (int32) ecx_137->b0000;
			ebx_144 = (struct Eq_5227 *) ecx_137[0x01];
			esi_145 = ecx_137;
			al_134 = (byte) eax_143;
			ecx_137 = ebx_144;
		} while (eax_143 != 0x00);
	}
	return *(fp - 0x28);
	word32 ebx_125;
	*ebxOut = fp->dw005C;
	word32 esi_127;
	*esiOut = fp->dw0060;
	word32 ebp_131;
	*ebpOut = fp->dw0068;
	return fp->dw0044;
}

word16 fn004054F0(word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 & ebxOut, ptr32 & ebpOut, HANDLE & esiOut)
{
	*ebxOut = ebx;
	*esiOut = esi;
	word32 ebp_15;
	return fn00405520(dwArg04, dwArg08, dwArg0C, fp + 0x10, out ebp_15);
}

word16 fn00405520(word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 dwArg10, ptr32 & ebpOut)
{
	if (dwArg08 == 0x00)
	{
		word32 ebx_64;
		word32 ebp_65;
		word32 esi_66;
		return (word16) fn00404B80(0x00, dwArg04, 0x00, dwArg0C, dwArg10, out ebx_64, out ebp_65, out esi_66);
	}
	else
	{
		Eq_5528 (* ebx_42)[];
		word32 ebp_43;
		Eq_1812 esi_44;
		Eq_1812 eax_45 = fn00404B80(0x00, dwArg04, dwArg08 - 0x01, dwArg0C, dwArg10, out ebx_42, out ebp_43, out esi_44);
		word16 ax_46 = (word16) eax_45;
		Eq_1812 edx_49 = eax_45;
		if (eax_45 > esi_44)
			edx_49 = esi_44;
		Mem51[ebx_42 + edx_49:byte] = 0x00;
		return ax_46;
	}
}

void fn004081E8(word32 dwArg04)
{
	fn00401FF0(dwArg04, fp + 0x08);
	return;
}

