// classCPP.c
// Generated by decompiling classCPP.exe
// using Reko decompiler version 0.6.2.0.

#include "classCPP.h"

void fn00401180(word32 ecx, word32 ebx, word32 ebp)
{
	ptr32 ebp_151 = fp - 0x04;
	LPTOP_LEVEL_EXCEPTION_FILTER * esp_162 = fp - 0x1C;
	<anonymous> * eax_11 = globals->ptr40A0D8;
	if (eax_11 != null)
	{
		word32 esp_150;
		byte SCZO_153;
		word32 eax_154;
		byte SZO_155;
		byte C_156;
		byte Z_157;
		word32 edx_158;
		word32 esi_160;
		word32 edi_161;
		eax_11();
		esp_162 = esp_150 - 0x0C;
	}
	*esp_162 = (LPTOP_LEVEL_EXCEPTION_FILTER *) &globals->t401000;
	SetUnhandledExceptionFilter(*esp_162);
	fn004017E0(ecx, ebx);
	fn004018C0();
	word32 ecx_37 = fn004014D0(ebp_151);
	union Eq_44 * esp_34 = esp_162;
	Eq_44 eax_38 = globals->t40D020;
	if (eax_38 != 0x00)
	{
		globals->t409004 = eax_38;
		*esp_34 = (union Eq_44 *) eax_38;
		word32 eax_97 = iob->dw0010;
		*(esp_34 - 0x04) = eax_97;
		struct Eq_176 * esp_99;
		word32 ebp_100;
		struct Eq_178 * ebx_101;
		byte SCZO_102;
		word32 eax_103;
		byte SZO_104;
		byte C_105;
		byte Z_106;
		word32 edx_107;
		word32 ecx_108;
		word32 esi_109;
		word32 edi_110;
		setmode();
		esp_99->t0000 = globals->t40D020;
		word32 eax_114 = ebx_101->dw0030;
		esp_99->dwFFFFFFFC = eax_114;
		struct Eq_202 * esp_116;
		word32 ebp_117;
		struct Eq_204 * ebx_118;
		byte SCZO_119;
		word32 eax_120;
		byte SZO_121;
		byte C_122;
		byte Z_123;
		word32 edx_124;
		word32 ecx_125;
		word32 esi_126;
		word32 edi_127;
		setmode();
		esp_116->t0000 = globals->t40D020;
		word32 eax_131 = ebx_118->dw0050;
		esp_116->dwFFFFFFFC = eax_131;
		word32 esp_133;
		word32 ebp_134;
		word32 ebx_135;
		byte SCZO_136;
		word32 eax_137;
		byte SZO_138;
		byte C_139;
		byte Z_140;
		word32 edx_141;
		word32 ecx_142;
		word32 esi_143;
		word32 edi_144;
		setmode();
	}
	word32 esp_42;
	word32 ebp_43;
	word32 ebx_44;
	byte SCZO_45;
	union Eq_44 * eax_46;
	byte SZO_47;
	byte C_48;
	byte Z_49;
	word32 edx_50;
	Eq_44 ecx_51;
	word32 esi_52;
	word32 edi_53;
	_p__fmode();
	Eq_44 edx_55 = globals->t409004;
	*eax_46 = (union Eq_44 *) edx_55;
	word32 edx_57;
	Eq_44 ecx_58 = fn00401DE0(ecx_51, edx_55, esi_52, edi_53, out edx_57);
	__align(esp_42 + ~0x03);
	word32 eax_59 = fn00401950(esi_52);
	struct Eq_100 * esp_60;
	word32 ebp_61;
	word32 ebx_62;
	byte SCZO_63;
	word32 * eax_64;
	byte SZO_65;
	byte C_66;
	byte Z_67;
	word32 edx_68;
	word32 ecx_69;
	word32 esi_70;
	word32 edi_71;
	_p__environ();
	esp_60->dw0004 = *eax_64;
	esp_60->dw0000 = globals->dw40D000;
	word32 eax_77 = globals->dw40D004;
	esp_60->dwFFFFFFFC = eax_77;
	fn00401410(esi_70, ebp);
	struct Eq_136 * esp_80;
	word32 ebp_81;
	word32 ebx_82;
	byte SCZO_83;
	word32 eax_84;
	byte SZO_85;
	byte C_86;
	byte Z_87;
	word32 edx_88;
	word32 ecx_89;
	word32 esi_90;
	word32 edi_91;
	cexit();
	esp_80->tFFFFFFFC = 0x00;
	ExitProcess(esp_80->tFFFFFFFC);
}

void fn00401260()
{
	word32 esp_16;
	byte SCZO_17;
	word32 eax_18;
	byte SZO_19;
	byte C_20;
	_getmainargs();
	return;
}

Eq_44 Win32CrtStartup()
{
	word32 esp_5;
	byte SCZO_6;
	word32 esi_7;
	word32 edi_8;
	word32 eax_9;
	word32 ecx_10;
	word32 ebx_11;
	word32 ebp_12;
	_set_app_type();
	fn00401180(ecx_10, ebx_11, ebp_12);
	word32 esp_19;
	byte SCZO_20;
	word32 esi_21;
	word32 edi_22;
	word32 eax_23;
	word32 ecx_24;
	word32 ebx_25;
	word32 ebp_26;
	_set_app_type();
	fn00401180(ecx_24, ebx_25, ebp_26);
	return fn004012E0();
}

int32 fn004012E0()
{
	return atexit(*esp_1);
}

void fn00401410(word32 esi, word32 dwArg00)
{
	__align(fp);
	fn00401950(esi);
	fn00408294(fp - 0x14);
	*(fp - 44) = fp - 0x18;
	*(fp - 0x30) = 0x0040A0D4;
	struct Eq_311 * esp_22;
	word32 ecx_23;
	word32 ebp_24;
	byte SCZO_25;
	word32 eax_26;
	word32 edx_27;
	word32 esi_28;
	msvcrt.dll!scanf();
	esp_22->dw0000 = dwLoc18;
	fn00408250(fp - 0x14, dwArg00);
	fn00408220(fp - 0x14);
	esp_22->dw0004 = ebp_24 - 0x10;
	esp_22->dw0000 = 0x0040A0D4;
	struct Eq_346 * esp_42;
	word32 ecx_43;
	ptr32 ebp_44;
	byte SCZO_45;
	word32 eax_46;
	word32 edx_47;
	word32 esi_48;
	msvcrt.dll!scanf();
	word32 edx_49 = *(ebp_44 - 0x10);
	esp_42->dw0000 = edx_49;
	fn00408250(ebp_44 - 0x0C, dwArg00);
	fn00408220(ebp_44 - 0x0C);
	esp_42->ptr0004 = ebp_44 - 0x10;
	esp_42->dw0000 = 0x0040A0D4;
	word32 * esp_61;
	word32 ecx_62;
	ptr32 ebp_63;
	byte SCZO_64;
	word32 eax_65;
	word32 edx_66;
	word32 esi_67;
	msvcrt.dll!scanf();
	*esp_61 = *(ebp_63 - 0x10);
	fn00408250(ebp_63 - 0x0C, dwArg00);
	fn00408220(ebp_63 - 0x0C);
	return;
}

int32 fn004014D0(ptr32 ebp)
{
	if ((globals->b409000 & 0x02) == 0x00)
	{
		fn00401260();
		return ecx;
	}
	Eq_44 eax_43 = GetCommandLineA();
	Eq_44 eax_47 = strlen(eax_43);
	word32 eax_48 = eax_47 + 0x11 + eax_47;
	fn00401FD0(eax_48 & ~0x0F);
	Eq_44 esi_163 = eax_43;
	struct Eq_434 * esp_52 = fp - 0x5C - (eax_48 & ~0x0F);
	int32 eax_161 = 0x00;
	byte al_157 = 0x00;
l00401547:
	esi_163 = esi_163 + 0x01 + 0x01;
	ci8 bl_156 = (byte) (word32) *(esi_163 - 0x01);
	int32 ecx_112 = (int32) bl_156;
	if (ecx_112 == 0x00)
	{
l004015D0:
		byte * eax_104;
		byte * edx_148 = *(fp - 0x30);
		if (eax_161 != 0x00)
		{
			eax_104 = edx_148 + eax_161;
			do
			{
				edx_148 = edx_148 + 0x01;
				*(edx_148 - 0x01) = 0x5C;
			} while (edx_148 != eax_104);
		}
		else
			eax_104 = edx_148;
		if (*(fp - 0x38) != 0x00 || *(fp - 0x40) < eax_104)
		{
			*eax_104 = 0x00;
			esp_52->ptr000C = fp - 44;
			esp_52->dw0008 = 0x00;
			esp_52->dw0004 = *(fp - 0x3C);
			esp_52->dw0000 = *(fp - 0x40);
			ecx_112 = fn00402C40(dwArg00, dwArg04, dwArg08, dwArg0C);
		}
		globals->dw40D004 = *(fp - 0x28);
		globals->dw40D000 = *(fp - 0x24);
		return ecx_112;
	}
l00401555:
	word32 edi_171;
	if (bl_156 != 0x3F)
	{
		if (bl_156 <= 0x3F)
		{
			byte * ebx_291;
			if (bl_156 == 0x27)
			{
				if ((globals->b409000 & 0x10) != 0x00)
				{
					int32 ebx_353 = eax_161 >> 0x01;
					if (ebx_353 != 0x00)
					{
						byte * edx_377 = *(fp - 0x30);
						ebx_291 = edx_377 + ebx_353;
						do
						{
							edx_377 = edx_377 + 0x01;
							*(edx_377 - 0x01) = 0x5C;
						} while (edx_377 != ebx_291);
					}
					else
						ebx_291 = (byte *) *(fp - 0x30);
					if ((al_157 & 0x01) != 0x00 || *(fp - 0x34) == 0x22)
					{
						*(fp - 0x30) = ebx_291 + 0x01;
						*ebx_291 = 0x27;
						*(fp - 0x38) = 0x01;
						eax_161 = 0x00;
						al_157 = 0x00;
						goto l00401547;
					}
l004015AD:
					*(fp - 0x30) = (byte **) ebx_291;
					esi_163 = esi_163 + 0x00;
					bl_156 = (byte) (word32) *(esi_163 - 0x01);
					*(fp - 0x34) = *(fp - 0x34) ^ ecx_112;
					*(fp - 0x38) = 0x01;
					eax_161 = 0x00;
					al_157 = 0x00;
					ecx_112 = (int32) bl_156;
					if (ecx_112 != 0x00)
						goto l00401555;
					goto l004015D0;
				}
				goto l004016B5;
			}
			if (bl_156 != 0x2A)
			{
				if (bl_156 == 0x22)
				{
					int32 ebx_312 = eax_161 >> 0x01;
					if (ebx_312 != 0x00)
					{
						byte * edx_336 = *(fp - 0x30);
						ebx_291 = edx_336 + ebx_312;
						do
						{
							edx_336 = edx_336 + 0x01;
							*(edx_336 - 0x01) = 0x5C;
						} while (edx_336 != ebx_291);
					}
					else
						ebx_291 = (byte *) *(fp - 0x30);
					if ((al_157 & 0x01) != 0x00 || *(fp - 0x34) == 0x27)
					{
						*(fp - 0x30) = ebx_291 + 0x01;
						*ebx_291 = 0x22;
						*(fp - 0x38) = 0x01;
						eax_161 = 0x00;
						al_157 = 0x00;
						goto l00401547;
					}
					goto l004015AD;
				}
				goto l004016B5;
			}
		}
		else
		{
			if (bl_156 == 0x5C)
			{
				eax_161 = eax_161 + 0x01;
				al_157 = (byte) eax_161;
				goto l00401547;
			}
			if (bl_156 != 0x7F)
			{
				if (bl_156 != 0x5B)
				{
l004016B5:
					ci8 * edx_223 = *(fp - 0x30);
					ci8 * edi_225 = *(fp - 0x30) + eax_161;
					if (eax_161 != 0x00)
					{
						do
						{
							edx_223 = edx_223 + 0x01;
							*(edx_223 - 0x01) = 0x5C;
						} while (edx_223 != edi_225);
					}
					else
						edi_225 = (ci8 *) *(fp - 0x30);
					if (*(fp - 0x34) == 0x00)
					{
						esp_52->dw0000 = ecx_112;
						if (isspace(esp_52->dw0000) != 0x00)
						{
							if (*(fp - 0x38) == 0x00 && *(fp - 0x40) >= edi_225)
							{
								*(fp - 0x30) = (ci8 **) edi_225;
								eax_161 = 0x00;
								al_157 = 0x00;
							}
							else
							{
								*edi_225 = 0x00;
								esp_52->ptr000C = fp - 44;
								esp_52->dw0008 = 0x00;
								esp_52->dw0004 = *(fp - 0x3C);
								int32 edi_261 = *(fp - 0x40);
								esp_52->dw0000 = edi_261;
								fn00402C40(dwArg00, dwArg04, dwArg08, dwArg0C);
								*(fp - 0x3C) = *(fp - 0x3C) | 0x01;
								*(fp - 0x30) = edi_261;
								*(fp - 0x38) = 0x00;
								eax_161 = 0x00;
								al_157 = 0x00;
							}
							goto l00401547;
						}
					}
					*(fp - 0x30) = edi_225 + 0x01;
					*edi_225 = bl_156;
					eax_161 = 0x00;
					al_157 = 0x00;
					goto l00401547;
				}
				edi_171 = 0x01;
				if ((globals->b409000 & 0x20) == 0x00)
				{
l0040167B:
					ci8 * eax_177;
					if (eax_161 != 0x00)
					{
						ci8 * edx_200 = *(fp - 0x30);
						eax_177 = edx_200 + eax_161;
						do
						{
							edx_200 = edx_200 + 0x01;
							*(edx_200 - 0x01) = 0x5C;
						} while (edx_200 != eax_177);
					}
					else
						eax_177 = (ci8 *) *(fp - 0x30);
					if ((byte) edi_171 != 0x00 || ecx_112 == 0x7F)
					{
						*eax_177 = 0x7F;
						eax_177 = eax_177 + 0x01;
					}
					*eax_177 = bl_156;
					*(fp - 0x30) = eax_177 + 0x01;
					eax_161 = 0x00;
					al_157 = 0x00;
					goto l00401547;
				}
			}
		}
	}
	word32 edx_214 = *(fp - 0x34);
	edi_171 = DPB(edx_214, edx_214 != 0x00, 0);
	goto l0040167B;
}

void fn004017E0(word32 ecx, word32 ebx)
{
	byte dh_10 = SLICE(SCZDOP, byte, 8);
	if (((SCZDOP ^ 0x00200000 ^ SCZDOP) & 0x00200000) != 0x00)
	{
		word32 eax_49;
		word32 ebx_50;
		word32 ecx_51;
		word32 edx_52;
		__cpuid(0x00, ecx, &eax_49, &ebx_50, &ecx_51, &edx_52);
		if (eax_49 != 0x00)
		{
			word32 eax_70;
			word32 ebx_71;
			word32 ecx_72;
			ui32 edx_73;
			__cpuid(0x01, ecx_51, &eax_70, &ebx_71, &ecx_72, &edx_73);
			if ((dh_10 & 0x01) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x01;
			if ((dh_10 & 0x80) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x02;
			if ((edx_73 & 0x00800000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x04;
			if ((edx_73 & 0x01000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x08;
			if ((edx_73 & 0x02000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x10;
			if ((edx_73 & 0x04000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x20;
			if ((cl & 0x01) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x40;
			word32 ecx_99 = DPB(ecx_72, ch & 0x20, 8);
			if ((ch & 0x20) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x80;
			uint32 eax_106;
			word32 ebx_107;
			word32 ecx_108;
			word32 edx_109;
			__cpuid(0x80000000, ecx_99, &eax_106, &ebx_107, &ecx_108, &edx_109);
			if (eax_106 > 0x80000000)
			{
				word32 eax_113;
				word32 ebx_114;
				word32 ecx_115;
				int32 edx_116;
				__cpuid(0x80000001, ecx_108, &eax_113, &ebx_114, &ecx_115, &edx_116);
				if (edx_116 < 0x00)
					globals->dw40D024 = globals->dw40D024 | 0x0100;
				if ((edx_116 & 0x40000000) != 0x00)
					globals->dw40D024 = globals->dw40D024 | 0x0200;
			}
		}
	}
	return;
}

void fn004018C0()
{
fn004018C0_entry:
l004018C0:
fn004018C0_exit:
}

word32 fn00401900(word32 esi)
{
	word32 * esp_24 = fp - 0x1C;
	ui32 ebx_14 = globals->dw408300;
	if (ebx_14 == ~0x00)
	{
		ebx_14 = 0x00;
		while (true)
		{
			ui32 eax_48 = ebx_14 + 0x01;
			if ((&globals->dw408300)[eax_48] == 0x00)
				break;
			ebx_14 = eax_48;
		}
	}
	if (ebx_14 != 0x00)
	{
		do
		{
			word32 ebx_32;
			byte SCZO_33;
			byte Z_34;
			byte SZO_35;
			byte C_36;
			word32 esi_37;
			word32 eax_38;
			word32 edx_39;
			(&globals->dw408300)[ebx_14]();
		} while (ebx_32 != 0x01);
	}
	*esp_24 = 0x004018D0;
	return fn004012E0();
}

word32 fn00401950(word32 esi)
{
	if (globals->dw40D028 == 0x00)
	{
		globals->dw40D028 = 0x01;
		return fn00401900(esi);
	}
	else
		return eax;
}

Eq_44 fn00401CA0(Eq_44 ecx, Eq_44 edx, word32 dwArg04, ptr32 & edxOut, ptr32 & esiOut, ptr32 & ediOut)
{
	word32 esp_17;
	word32 esi_18;
	word32 ebx_19;
	byte SCZO_20;
	word32 eax_21;
	word32 ebp_22;
	word32 edi_23;
	word32 ecx_24;
	word32 edx_25;
	byte SZO_26;
	byte C_27;
	byte Z_28;
	msvcrt.dll!fwrite();
	word32 esp_34;
	word32 esi_35;
	word32 ebx_36;
	byte SCZO_37;
	Eq_44 eax_38;
	word32 ebp_39;
	word32 edi_40;
	Eq_44 ecx_41;
	Eq_44 edx_42;
	byte SZO_43;
	byte C_44;
	byte Z_45;
	msvcrt.dll!vfprintf();
	abort();
	word32 edi_52;
	*ediOut = ecx_41;
	word32 esi_55;
	*esiOut = edx_42;
	if (VirtualQuery(eax_38, fp - 0x54, 0x1C) == 0x00)
	{
		word32 edx_85;
		word32 ebx_86;
		return fn00401DBB(ecx_41, edx_42, eax_38, out edx_85, out ebx_86);
	}
	else
	{
		word32 edx_79;
		word32 ebx_80;
		word32 ebp_81;
		word32 esi_82;
		word32 edi_83;
		return fn00401D21(eax_38, fp - 0x20, edx_42, ecx_41, out edx_79, out ebx_80, out ebp_81, out esi_82, out edi_83);
	}
}

Eq_44 fn00401CF0(Eq_44 eax, Eq_44 ecx, Eq_44 edx, ptr32 & edxOut, Eq_1216 * & ebxOut)
{
	if (VirtualQuery(eax, fp - 0x38, 0x1C) == 0x00)
	{
		word32 edx_52;
		word32 ebx_53;
		return fn00401DBB(ecx, edx, eax, out edx_52, out ebx_53);
	}
	else
	{
		word32 edx_40;
		Eq_44 ebx_41;
		word32 * ebp_42;
		Eq_44 esi_43;
		Eq_44 edi_44;
		return fn00401D21(eax, fp - 0x04, edx, ecx, out edx_40, out ebx_41, out ebp_42, out esi_43, out edi_44);
	}
}

word32 fn00401D21(Eq_44 ebx, word32 * ebp, Eq_44 esi, Eq_44 edi, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	*edxOut = edx;
	word32 eax_4 = *(ebp - 0x20);
	if (eax_4 == 0x04 || eax_4 == 0x40)
	{
		v3->t0008 = edi;
		v3->t0004 = esi;
		v3->t0000 = ebx;
		memcpy(v3->t0000, v3->t0004, v3->t0008);
	}
	else
	{
		Eq_44 eax_49 = *(ebp - 0x28);
		v3->t000C = ebp - 0x38;
		v3->t0008.u0 = 0x40;
		*(ebp - 0x3C) = ebp - 0x38;
		v3->t0004 = eax_49;
		v3->t0000 = *(ebp - 0x34);
		VirtualProtect(v3->t0000, v3->t0004, v3->t0008, v3->t000C);
		*(ebp - 0x40) = *(ebp - 0x20);
		v3->t0008 = edi;
		v3->t0004 = esi;
		v3->t0000 = ebx;
		memcpy(v3->t0000, v3->t0004, v3->t0008);
		word32 edx_50;
		*edxOut = ebp - 0x38;
		ecx = *(ebp - 0x40);
		if (ecx != 0x04 && ecx != 0x40)
		{
			Eq_1328 edx_72 = *(ebp - 0x3C);
			*edxOut = edx_72;
			v3->t0008 = *(ebp - 0x38);
			Eq_44 eax_74 = *(ebp - 0x28);
			v3->t000C = edx_72;
			v3->t0004 = eax_74;
			v3->t0000 = *(ebp - 0x34);
			VirtualProtect(v3->t0000, v3->t0004, v3->t0008, v3->t000C);
			word32 ebx_84;
			*ebxOut = *(ebp - 0x0C);
			word32 esi_86;
			*esiOut = *(ebp - 0x08);
			word32 edi_88;
			*ediOut = *(ebp - 0x04);
			word32 ebp_90;
			*ebpOut = *ebp;
			return ecx;
		}
	}
	word32 ebx_28;
	*ebxOut = *(ebp - 0x0C);
	word32 esi_30;
	*esiOut = *(ebp - 0x08);
	word32 edi_32;
	*ediOut = *(ebp - 0x04);
	word32 ebp_34;
	*ebpOut = *ebp;
	return ecx;
}

Eq_44 fn00401DBB(Eq_44 ecx, Eq_44 edx, Eq_44 ebx, ptr32 & edxOut, ptr32 & ebxOut)
{
	*ebxOut = ebx;
	v3->t0008 = ebx;
	v3->dw0004 = 0x1C;
	v3->dw0000 = 0x0040A0F4;
	Eq_44 edx_9;
	word32 esi_10;
	word32 edi_11;
	Eq_44 ecx_12 = fn00401CA0(ecx, edx, dwArg00, out edx_9, out esi_10, out edi_11);
	word32 edx_15;
	return fn00401DE0(ecx_12, edx_9, esi_10, edi_11, out edx_15);
}

Eq_44 fn00401DE0(Eq_44 ecx, Eq_44 edx, word32 esi, word32 edi, ptr32 & edxOut)
{
	*edxOut = edx;
	if (globals->dw40D05C != 0x00)
		return ecx;
	globals->dw40D05C = 0x01;
	if (true)
		return ecx;
	struct Eq_1526 * ebx_101;
	if (false)
	{
		if ((word32 *) 4237288 != 0x00 || (word32 *) 4237292 != 0x00)
		{
l00401EB0:
			ebx_101 = (struct Eq_1526 *) 4237288;
			goto l00401EB5;
		}
		ecx = (union Eq_44 *) 0x0040A7F0;
		ebx_101 = (struct Eq_1526 *) 0x0040A7F4;
		if (ecx != 0x00)
		{
			ebx_101 = (struct Eq_1526 *) 4237288;
			goto l00401E4C;
		}
	}
	else
		ebx_101 = (struct Eq_1526 *) 4237288;
	edx = ebx_101->dw0000;
	*edxOut = edx;
	if (edx == 0x00)
	{
		if (ebx_101->dw0004 == 0x00)
		{
l00401E4C:
			word32 eax_126 = ebx_101->dw0008;
			if (eax_126 != 0x01)
			{
				word32 edx_229;
				word32 esi_230;
				word32 edi_231;
				Eq_44 ecx_232 = fn00401CA0(ecx, edx, 0x0040A128, out edx_229, out esi_230, out edi_231);
				word32 esp_233;
				word32 eax_234;
				byte SZO_235;
				byte C_236;
				byte Z_237;
				byte SCZO_238;
				word32 edi_239;
				word32 esi_240;
				word32 ebx_241;
				word32 ecx_242;
				word32 edx_243;
				byte dl_244;
				byte S_245;
				word16 si_246;
				_register_frame_info();
				return ecx_242;
			}
			else
			{
				while (true)
				{
					struct Eq_1576 * ebx_140 = ebx_101 + 0x01;
					if (ebx_140 >= (struct Eq_1576 *) 4237288)
						return ecx;
					Eq_44 ecx_147 = ebx_140->t0000;
					Eq_44 edx_143 = (word32) ebx_140->b0008;
					struct Eq_1590 * esi_145 = ebx_140->ptr0004;
					Eq_1594 edi_151 = *ecx_147;
					if (edx_143 == 0x10)
					{
						ci16 si_203 = (word16) (word32) esi_145->w400000;
						ui32 edx_207 = (word32) si_203;
						if (si_203 < 0x00)
							edx_207 = edx_207 | 0xFFFF0000;
						*(fp - 0x10) = (word32) edi_151;
						word32 edx_220;
						ecx = fn00401CF0(&esi_145->w400000, 0x02, fp - 0x10, out edx_220, out ebx_101);
						continue;
					}
					if (edx_143 != 0x20)
						break;
					*(fp - 0x10) = (union Eq_1618 *) (edi_151 - ecx_147);
					word32 edx_199;
					ecx = fn00401CF0(&esi_145->w400000, 0x04, fp - 0x10, out edx_199, out ebx_101);
				}
				if (edx_143 == 0x08)
				{
					ci8 dl_165 = (byte) (word32) esi_145->w400000;
					ui32 esi_169 = (word32) dl_165;
					if (dl_165 < 0x00)
						esi_169 = esi_169 | ~0xFF;
					*(fp - 0x10) = (word32) edi_151;
					word32 edx_184;
					ecx = fn00401CF0(&esi_145->w400000, 0x01, fp - 0x10, out edx_184, out ebx_101);
					continue;
				}
				else
				{
					*(fp - 0x28) = (union Eq_44 *) edx_143;
					*(fp - 44) = 0x0040A15C;
					*(fp - 0x10) = 0x00;
					word32 edx_160;
					word32 esi_161;
					word32 edi_162;
					ecx = fn00401CA0(ecx_147, edx_143, dwArg00, out edx_160, out esi_161, out edi_162);
					goto l00401EB0;
				}
			}
		}
	}
l00401EB5:
	if (ebx_101 < (struct Eq_1526 *) 4237288)
	{
		do
		{
			struct Eq_1705 * edx_90 = ebx_101->dw0004;
			*(fp - 0x10) = edx_90->dw400000 + ebx_101->dw0000;
			word32 edx_100;
			ecx = fn00401CF0(&edx_90->dw400000, 0x04, fp - 0x10, out edx_100, out ebx_101);
		} while (ebx_101 < (struct Eq_1526 *) 4237288);
	}
	return ecx;
}

void fn00401FD0(uint32 eax)
{
	struct Eq_1753 * ecx_10 = fp + 0x04;
	if (eax >= 0x1000)
	{
		do
		{
			ecx_10 = ecx_10 - 0x1000;
			ecx_10->dw0000 = ecx_10->dw0000;
			eax = eax - 0x1000;
		} while (eax > 0x1000);
	}
	word32 * ecx_16 = ecx_10 - eax;
	*ecx_16 = *ecx_16;
	return;
}

void fn00402000(word32 dwArg04, ptr32 dwArg08)
{
	word32 ebx_15;
	word32 ebp_16;
	word32 esi_17;
	fn00404B90(0x3000, iob + 0x20, 0x00, dwArg04, dwArg08, out ebx_15, out ebp_16, out esi_17);
	return;
}

Eq_44 fn00402040(Eq_44 eax, word32 edx, ptr32 dwArg00, word32 dwArg04, word32 dwArg08)
{
	struct Eq_1811 * ebx_15 = eax;
	if (eax == 0x00)
		return 0x00;
	int32 ecx_62 = (int32) *eax;
	Eq_44 eax_129 = 0x00;
	struct Eq_1811 * edx_148 = eax;
	if (ecx_62 == 0x00)
		return 0x00;
l00402060:
	if (true && ecx_62 == 0x7F)
	{
		edx_148 = ebx_15 + 0x01;
		if (ebx_15->b0000 == 0x00)
			return 0x00;
	}
	if (eax_129 == 0x00)
	{
		if (ecx_62 != 0x3F && ecx_62 != 0x2A)
		{
			eax_129 = (word32) (ecx_62 == 0x5B);
			goto l00402083;
		}
	}
	else if (ecx_62 != 0x5D || eax_129 <= 0x01)
	{
		eax_129 = eax_129;
l00402083:
		ebx_15 = edx_148;
		ecx_62 = (int32) edx_148->b0000;
		edx_148 = edx_148->b0000 + 0x01;
		if (ecx_62 != 0x00)
			goto l00402060;
		return 0x00;
	}
	return eax_129;
	return 0x01;
}

Eq_1865 * fn004020D0(Eq_1865 * eax, ui32 ecx, int32 edx, byte * esi)
{
fn004020D0_entry:
	byte cl_116
	word32 ebx_17 = (word32) eax->b0000
	int32 edi_192 = (int32) (byte) ebx_17
	branch edi_192 == 0x5D l004021C0
	goto l004020E9
l004020D0:
l004020E9:
	cl_116 = (byte) ebx_17
	branch edi_192 != 0x2D l0040211E
	goto l004021C0
l004020F5:
	branch ebx_100 == 0x00 l004021B0
l004020FD:
	branch ebx_100 == 0x5C l004021B0
	branch ebx_100 == 0x5C l004021B0
l00402106:
	branch ebx_100 == 0x2F l004021B0
	branch ebx_100 == 0x2F l004021B0
l0040210F:
	branch ebx_100 == edx l004021E8
	edi_192 = ebx_100
	cl_116 = (byte) (word32) esi_104->b0000
	eax = esi_104
	branch ebx_100 == edx l004021E8
l0040211E:
	branch (int32) cl_116 == 0x5D l004021B0
	branch (int32) cl_116 == 0x5D l004021B0
	int32 ebx_100 = (int32) cl_116
	struct Eq_1865 * esi_104 = eax + 0x01
	branch ebx_100 == 0x5D l004021B0
l0040212D:
	branch ebx_100 != 0x2D l004020F5
	branch ebx_100 != 0x2D l004020F5
	branch ebx_100 != 0x2D l004020F5
l00402132:
	branch (byte) (word32) eax[0x01] == 0x5D l004021D4
	branch (byte) (word32) eax[0x01] == 0x5D l004021D4
	byte bl_208 = (byte) (word32) eax[0x01]
	branch bl_208 == 0x5D l004021D4
l0040213F:
	int32 ebp_211 = (int32) bl_208
	byte bl_215 = (byte) ebp_211
	branch ebp_211 == 0x00 l004021B0
	int32 ebp_216 = (int32) bl_215
	byte bl_220 = (byte) ebp_216
	branch ebp_216 == 0x00 l004021B0
	int32 ebp_221 = (int32) bl_220
	ebx_100 = ebp_221
	branch ebp_221 == 0x00 l004021B0
l00402148:
	int32 eax_255
	branch edi_192 >= ebp_221 l004022D8
	branch edi_192 >= ebp_221 l004022D8
	esi_104 = eax + 0x02
	branch edi_192 >= ebp_221 l004022D8
l00402153:
	branch edi_192 != edx l0040216E
	branch edi_192 != edx l0040216E
	eax_255 = edi_192 + 0x01
	branch edi_192 != edx l0040216E
	goto l00402220
l00402160:
	eax_255 = eax_255 + 0x01
	branch edx == eax_255 - 0x01 l00402220
l0040216E:
	branch ebp_221 > eax_255 l00402160
	branch ebp_221 > eax_255 l00402160
l00402172:
	branch ebp_221 >= eax_255 l004020FD
	branch ebp_221 >= eax_255 l004020FD
l00402176:
	branch edx == eax_255 l0040218F
	branch edx == eax_255 l0040218F
l00402180:
	branch eax_255 == ebp_221 + 0x02 l004020FD
l00402188:
	eax_255 = eax_255 - 0x01
	branch edx != eax_255 l00402180
l0040218F:
l00402195:
	byte al_281 = (byte) (word32) esi_104->b0000
	branch al_281 == 0x5D l00402243
l004021A0:
	branch al_281 == 0x7F l00402265
l004021A8:
	esi_104 = esi_104 + 0x01
	branch al_281 != 0x00 l00402195
l004021B0:
	return null
l004021C0:
	branch edi_192 == edx l00402280
l004021C8:
	cl_116 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l0040211E
l004021D4:
	edi_192 = 0x2D
	eax = esi_104
	cl_116 = 0x5D
	branch 0x2D != edx l0040211E
l004021E8:
	goto l004021FA
l004021F0:
	eax = eax + 0x01
	branch cl_116 == 0x00 l004021B0
l004021F7:
	cl_116 = (byte) (word32) eax->b0000
l004021FA:
	branch cl_116 == 0x5D l004022C5
l00402203:
	branch cl_116 != 0x7F l004021F0
l00402208:
	branch (ecx & 0x20) != 0x00 l004022D0
l00402210:
	cl_116 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l004021F0
l00402220:
l00402226:
	byte al_338 = (byte) (word32) esi_104->b0000
	branch al_338 == 0x5D l00402243
l0040222D:
	branch al_338 == 0x7F l00402250
l00402231:
	esi_104 = esi_104 + 0x01
	branch al_338 == 0x00 l004021B0
l0040223C:
	al_338 = (byte) (word32) esi_104->b0000
	branch al_338 != 0x5D l0040222D
l00402243:
	return esi_104 + 0x01
l00402250:
	branch (ecx & 0x20) != 0x00 l00402260
l00402254:
	al_338 = (byte) (word32) esi_104[0x01]
	esi_104 = esi_104 + 0x01
	goto l00402231
l00402260:
	esi_104 = esi_104 + 0x01
	goto l00402226
l00402265:
	branch (ecx & 0x20) != 0x00 l00402275
l00402269:
	al_281 = (byte) (word32) esi_104[0x01]
	esi_104 = esi_104 + 0x01
	goto l004021A8
l00402275:
	esi_104 = esi_104 + 0x01
	goto l00402195
l00402280:
	eax = eax + 0x01
l00402290:
	byte dl_419 = (byte) (word32) eax->b0000
	branch dl_419 == 0x5D l004022C5
l00402298:
	branch dl_419 == 0x7F l004022B0
l0040229D:
	eax = eax + 0x01
	branch dl_419 != 0x00 l00402290
	goto l004021B0
l004022B0:
	branch (ecx & 0x20) != 0x00 l004022C0
l004022B4:
	dl_419 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l0040229D
l004022C0:
	eax = eax + 0x01
	goto l00402290
l004022C5:
	return eax + 0x01
l004022D0:
	eax = eax + 0x01
	goto l004021F7
l004022D8:
	eax_255 = edi_192
	goto l00402172
fn004020D0_exit:
}

Eq_2118 * fn004022E0(Eq_2118 * eax)
{
	struct Eq_2118 * eax_28;
	if (eax != null)
	{
		int32 eax_54 = eax->dw000C;
		Eq_44 ebp_56 = (eax_54 + 0x01) * 0x04;
		Eq_44 eax_58 = malloc(ebp_56);
		eax->t0008 = eax_58;
		Eq_44 ebx_59 = eax_58;
		eax_28 = (struct Eq_2118 *) 0x03;
		if (eax_58 == 0x00)
			return eax_28;
		eax->dw0004 = 0x00;
		ui32 edx_67 = eax_54 + 0x01;
		if (eax_54 > 0x01)
		{
			Eq_2152 ecx_69 = ebp_56 - 0x04;
			while (true)
			{
				Mem73[ebx_59 + ecx_69:word32] = 0x00;
				ecx_69 = ecx_69 - 0x04;
				edx_67 = edx_67 - 0x01;
				if (edx_67 == 0x00)
					break;
				ebx_59 = eax->t0008;
			}
		}
	}
	eax_28 = null;
	return eax_28;
}

Eq_1865 * fn00402340(Eq_1865 * eax, ui32 ecx, byte * edx)
{
	byte cl_120;
	struct Eq_1865 * eax_151;
	struct Eq_1865 * edi_116 = eax;
	if (*edx != 0x2E)
		cl_120 = (byte) (word32) eax->b0000;
	else
	{
		int32 eax_376 = (int32) eax->b0000;
		if ((byte) eax_376 != 0x2E)
		{
			cl_120 = (byte) eax_376;
			eax_151 = eax_376 - 0x2E;
			if ((ecx & 0x00010000) == 0x00)
				return eax_151;
		}
		else
			cl_120 = 0x2E;
	}
	ptr32 ebp_121 = edx[0x01];
l00402374:
	int32 edx_131 = (int32) cl_120;
	byte * esi_222 = ebp_121 - 0x01;
	struct Eq_1865 * eax_100 = edi_116[0x01];
	if (edx_131 != 0x00)
	{
		if (cl_120 == 0x3F)
		{
			if (*(ebp_121 - 0x01) == 0x00)
			{
				eax_151 = (struct Eq_1865 *) 0x3F;
				return eax_151;
			}
			edi_116 = eax_100;
			goto l00402467;
		}
		if (cl_120 != 0x5B)
		{
			if (cl_120 == 0x2A)
			{
				byte dl_202 = (byte) (word32) edi_116[0x01];
				struct Eq_1865 * ebx_203 = eax_100;
				if (dl_202 == 0x2A)
				{
					do
					{
						ebx_203 = (struct Eq_1865 *) ebx_203[0x01];
						dl_202 = (byte) (word32) ebx_203->b0000;
					} while (dl_202 == 0x2A);
				}
				eax_151 = null;
				if (dl_202 == 0x00)
					return eax_151;
l00402429:
				eax_151 = fn00402340(ebx_203, ecx | 0x00010000, esi_222);
				if (eax_151 != null)
				{
					esi_222 = (byte *) esi_222[0x01];
					if (*(esi_222 - 0x01) != 0x00)
						goto l00402429;
					return eax_151;
				}
				else
				{
					return null;
					return null;
				}
			}
			if ((ecx & 0x20) == 0x00 && edx_131 == 0x7F)
			{
				edx_131 = (int32) edi_116[0x01];
				edi_116 = (struct Eq_1865 *) edi_116[0x02];
				if (edx_131 != 0x00)
				{
l004023AA:
					int32 ebx_135 = (int32) *(ebp_121 - 0x01);
					if ((byte) ebx_135 == 0x00)
					{
						ebx_135 = 0x00;
						goto l004023E6;
					}
					int32 esi_165;
					if ((ecx & 0x4000) == 0x00)
						esi_165 = tolower(edx_131) - tolower(ebx_135);
					else
						esi_165 = edx_131 - ebx_135;
					if (esi_165 != 0x00)
					{
l004023E6:
						eax_151 = edx_131 - ebx_135;
						return eax_151;
					}
l00402467:
					cl_120 = (byte) (word32) edi_116->b0000;
					ebp_121 = ebp_121 + 0x02;
					goto l00402374;
				}
			}
			edi_116 = eax_100;
			goto l004023AA;
		}
		int32 edx_271 = (int32) *(ebp_121 - 0x01);
		if (edx_271 == 0x00)
		{
			eax_151 = (struct Eq_1865 *) 0x5B;
			return eax_151;
		}
		if (edi_116[0x01] != 33)
		{
			struct Eq_1865 * eax_291 = fn004020D0(eax_100, ecx, edx_271, esi_222);
			edi_116 = eax_291;
			if (eax_291 == null)
			{
l0040253E:
				eax_151 = (struct Eq_1865 *) 0x5D;
				return eax_151;
			}
			goto l00402467;
		}
		struct Eq_1865 * ebx_297 = edi_116[0x02];
		if (fn004020D0(ebx_297, ecx, edx_271, esi_222) != null)
		{
			edi_116 = ebx_297;
			goto l00402467;
		}
		byte al_306 = (byte) (word32) edi_116[0x02];
		if (al_306 == 0x5D)
		{
			ebx_297 = (struct Eq_1865 *) edi_116[0x03];
			al_306 = (byte) (word32) edi_116[0x03];
		}
		if (al_306 == 0x5D)
		{
			edi_116 = (struct Eq_1865 *) ebx_297[0x01];
			goto l00402467;
		}
		if (al_306 == 0x7F)
		{
			if ((ecx & 0x20) != 0x00)
			{
				ebx_297 = (struct Eq_1865 *) ebx_297[0x01];
l00402517:
				al_306 = (byte) (word32) ebx_297->b0000;
				goto l0040251A;
			}
			al_306 = (byte) (word32) ebx_297[0x01];
			ebx_297 = (struct Eq_1865 *) ebx_297[0x01];
		}
		ebx_297 = (struct Eq_1865 *) ebx_297[0x01];
		if (al_306 == 0x00)
			goto l0040253E;
		goto l00402517;
	}
	eax_151 = -(int32) *esi_222;
	return eax_151;
}

Eq_44 fn004025C0(Eq_44 eax, Eq_2118 * edx, ptr32 & ecxOut)
{
	*ecxOut = ecx;
	Eq_44 eax_23 = realloc(edx->t0008, (edx->dw0004 + edx->dw000C) * 0x04 + 0x08);
	if (eax_23 == 0x00)
		return 0x01;
	else
	{
		ui32 edi_39 = edx->dw0004;
		edx->t0008 = eax_23;
		int32 eax_41 = edx->dw000C;
		edx->dw0004 = edi_39 + 0x01;
		*eax_23 = eax;
		edx->t0008->u0 = 0x00;
		word32 ecx_42;
		*ecxOut = edi_39 + 0x01;
		return 0x00;
	}
}

void fn00402630(Eq_44 eax, Eq_2118 * edx)
{
	if (eax != 0x00 && edx != null)
	{
		word32 ecx_20;
		fn004025C0(eax, edx, out ecx_20);
		return;
	}
	else
		return;
}

void fn00402650(Eq_44 eax, Eq_2118 * edx)
{
	Eq_44 eax_14 = *eax;
	if (eax_14 != 0x00)
		fn00402650(eax_14, edx);
	fn00402630(*eax, edx);
	Eq_44 eax_20 = *eax;
	if (eax_20 != 0x00)
		fn00402650(eax_20, edx);
	free(eax);
	return;
}

Eq_44 fn00402690(Eq_44 eax, word16 dx, ptr32 ebp)
{
fn00402690_entry:
	Eq_44 eax_23 = strlen(eax)
	word32 eax_26 = eax_23 + 0x10 & ~0x0F
	fn00401FD0(eax_26)
	struct Eq_2512 * esp_29 = fp - 0x7C - eax_26
	Mem32[esp_29 + 0x08:word32] = eax_23 + 0x01
	esp_29->t0004 = eax
	esp_29->t0000 = &esp_29->t0008
	Eq_44 eax_35 = memcpy(esp_29->t0000, esp_29->t0004, esp_29->t0008)
	esp_29->t0000 = eax_35
	Eq_44 eax_38 = fn00402D40(eax_35, dwArg00)
	struct Eq_2552 * ebp_126 = fp - 0x04
	Eq_44 ebx_16 = eax
	Eq_44 eax_102 = fn004022E0(fp - 44)
	branch eax_102 == 0x00 l004026F3
	goto l004026EB
l00402690:
l004026EB:
	return eax_102
l004026F3:
	branch fn00402040(eax_38, edx, ebp, dwArg00, dwArg04) == 0x00 l00402960
l00402706:
	esp_29->t0000 = fp - 44
	eax_102 = fn00402690(eax_38, DPB(dx, SLICE(edx, byte, 8) | 0x80, 8), fp - 0x04)
l0040271D:
	struct Eq_2512 * esp_107 = esp_29
	branch eax_102 != 0x00 l004026EB
l00402721:
	Eq_44 eax_121
	byte al_112 = (byte) (word32) *eax
	branch al_112 == 0x5C l00402A88
l0040272D:
	bool Z_835 = cond(al_112 - 0x2F)
	branch al_112 == 0x2F l00402A88
l00402735:
	byte * esi_837 = *(fp - 0x4C)
	byte * edi_838 = &globals->b40A188
	word32 ecx_839 = 0x02
l00402742:
	branch ecx_839 == 0x00 l00402744
l00402742_1:
	Z_835 = cond(*esi_971 - *edi_972)
	esi_837 = esi_971 + 0x01
	edi_838 = edi_972 + 0x01
	ecx_839 = ecx_839 - 0x01
	byte * esi_971 = esi_837
	byte * edi_972 = edi_838
	branch *esi_971 != *edi_972 l00402742
l00402744:
	branch Z_835 l00402A88
l0040274A:
	*(fp - 0x61) = 0x5C
l0040274E:
	*(fp - 0x44) = (union Eq_44 *) ebx_16
	*(fp - 0x4C) = 0x00
	branch (*(fp - 0x38) & 0x10) != 0x00 && fn00402040(ebx_16, *(fp - 0x38), ebp, dwArg00, dwArg04) == 0x00 l00402B95
l00402762:
	union Eq_44 * eax_150 = *(fp - 0x24)
	*(fp - 0x3C) = (union Eq_44 **) eax_150
	Eq_44 eax_152 = *eax_150
	branch eax_152 == 0x00 l00402BE3
l00402772:
	ui32 ecx_157 = *(fp - 0x38)
	*(fp - 0x40) = 0x02
	*(fp - 0x6C) = ecx_157 & 0x04
	*(fp - 0x34) = ecx_157 & 0x8000
l00402790:
	branch *(ebp_126 - 0x3C) == 0x01 l004029F2
l0040279A:
	esp_107->t0000 = eax_152
	word32 eax_208 = fn004032B0(dwArg00)
	*(ebp_126 - 44) = eax_208
	branch eax_208 == 0x00 l00402B23
l004027AD:
	branch *(ebp_126 - 0x48) == 0x00 l00402B75
l004027B8:
	esp_107->t0000 = **(ebp_126 - 0x38)
	*(ebp_126 - 0x4C) = (union Eq_44 *) strlen(esp_107->t0000)
l004027C8:
	ui32 eax_217 = *(ebp_126 - 0x34)
	*(ebp_126 - 0x44) = 0x00
	*(ebp_126 - 88) = eax_217 & 0x40
l004027D8:
	esp_107->t0000 = *(ebp_126 - 44)
	struct Eq_2870 * eax_238 = fn00403450(dwArg00, out ebp_126)
	branch eax_238 == null l004029D5
l004027ED:
	branch (*(ebp_126 - 0x30) == 0x00 || eax_238->dw0008 == 0x10) && fn00402340(*(ebp_126 - 0x40), *(ebp_126 - 0x34), eax_238->dw0008 + 0x01) == null l004027FA
	goto l004027D8
l004027F4:
l004027FA:
l0040280E:
	word32 edx_256 = (word32) eax_238->w0006
	word32 ecx_260 = *(ebp_126 - 0x4C)
	*(ebp_126 - 0x50) = (struct Eq_2512 **) esp_107
	ui32 eax_262 = ecx_260 + 0x11 + edx_256
	fn00401FD0(eax_262 & ~0x0F)
	struct Eq_2921 * esp_266 = esp_107 - (eax_262 & ~0x0F)
	*(ebp_126 - 0x54) = &esp_266->t0008
	word32 eax_267 = 0x00
	branch ecx_260 != 0x00 l00402A24
l00402837:
	esp_266->t0008 = edx_256 + 0x01
	esp_266->t0004 = eax_238->dw0008[0x01]
	esp_266->t0000 = (&esp_266->t0008)[eax_267 / 0x0C]
	memcpy(esp_266->t0000, esp_266->t0004, esp_266->t0008)
	esp_266->t0000 = esp_266->t0008
	word32 eax_288 = strlen(esp_266->t0000) + 0x10 & ~0x0F
	fn00401FD0(eax_288)
	union Eq_44 * esp_292 = esp_266 - eax_288
	struct Eq_3034 * esi_291 = *(ebp_126 - 0x54)
	ptr32 edx_296 = esp_292
	goto l0040287D
l00402870:
	edx_296 = edx_296 + 0x01
	*(edx_296 - 0x01) = al_312
	esi_291 = esi_291 + 0x01
	branch al_312 == 0x00 l00402898
l0040287D:
	branch (byte) (word32) esi_291->b0000 != 0x7F l00402870
	byte al_312 = (byte) (word32) esi_291->b0000
	branch al_312 != 0x7F l00402870
l00402884:
	byte al_516 = (byte) (word32) esi_291[0x01]
	byte * edx_518 = edx_296 + 0x01
	*(edx_518 - 0x01) = al_516
	struct Eq_3098 * esi_517 = esi_291 + 0x01
	branch al_516 != 0x00 l0040287D
	byte al_524 = (byte) (word32) esi_517->b0002
	*edx_518 = al_524
	edx_296 = edx_518 + 0x01
	esi_291 = (struct Eq_3034 *) (esi_517->b0002 + 0x01)
	branch al_524 != 0x00 l0040287D
l00402898:
	*esp_292 = esp_292
	branch _strdup(*esp_292) == 0x00 l00402A72
	esp_266->t0000 = esp_292
	Eq_44 eax_326 = _strdup(esp_266->t0000)
	branch eax_326 == 0x00 l00402A72
l004028AC:
	*(ebp_126 - 0x3C) = *(ebp_126 - 0x3C) & (word32) (*(ebp_126 - 0x3C) == 0x02) - 0x01
	branch *(ebp_126 - 88) != 0x00 l00402A63
	*(ebp_126 - 0x3C) = *(ebp_126 - 0x3C) & (word32) (*(ebp_126 - 0x3C) == 0x02) - 0x01
	branch *(ebp_126 - 88) != 0x00 l00402A63
l004028C6:
	int32 ecx_384
	branch *(ebp_126 - 0x44) == 0x00 l00402B8C
	Eq_44 ebx_375 = *(ebp_126 - 0x44)
	branch ebx_375 == 0x00 l00402B8C
l004028D1:
	ui32 edi_422 = *(ebp_126 - 0x34)
	goto l004028F4
l004028E0:
	eax_444 = strcoll(esp_266->t0000, esp_266->t0004)
	ecx_466 = *ebx_375.u0
	edx_451 = *ebx_375.u0
	branch eax_444 <= 0x00 l00402910
l004028EE:
	branch edx_451 == 0x00 l00402916
	branch edx_451 == 0x00 l00402916
l004028F2:
	ebx_375 = edx_451
l004028F4:
	int32 eax_444
	Eq_44 edx_451
	Eq_44 ecx_466
	Eq_44 eax_434 = *ebx_375.u0
	esp_266->t0000 = eax_326
	esp_266->t0004 = eax_434
	branch (edi_422 & 0x4000) != 0x00 l004028E0
l00402902:
	eax_444 = _stricoll(esp_266->t0000, esp_266->t0004)
	ecx_466 = *ebx_375.u0
	edx_451 = *ebx_375.u0
	branch eax_444 > 0x00 l004028EE
l00402910:
	edx_451 = ecx_466
	branch ecx_466 != 0x00 l004028F2
l00402916:
	ecx_384 = eax_444
l00402918:
	*(ebp_126 - 0x54) = ecx_384
	esp_266->t0000.u0 = 0x0C
	Eq_44 eax_389 = malloc(esp_266->t0000)
	branch eax_389 == 0x00 l0040294D
l0040292B:
	*eax_389 = eax_326
	eax_389->u0 = 0x00
	eax_389->u0 = 0x00
	branch ebx_375 == 0x00 l0040294D
l0040293F:
	branch *(ebp_126 - 0x54) <= 0x00 l00402B60
l0040294A:
	*ebx_375.u0 = eax_389
l0040294D:
	branch *(ebp_126 - 0x44) == 0x00 l00402B6D
l00402958:
	esp_107 = (struct Eq_2512 *) *(ebp_126 - 0x50)
	goto l004027D8
l00402960:
	esp_29->t0000 = eax_38
	word32 eax_883 = strlen(esp_29->t0000) + 0x10 & ~0x0F
	fn00401FD0(eax_883)
	union Eq_44 * esp_890 = esp_29 - eax_883
	Eq_44 edx_886 = eax_38
	ptr32 ecx_893 = esp_890
	goto l00402992
l00402985:
	ecx_893 = ecx_893 + 0x01
	*(ecx_893 - 0x01) = al_908
	edx_886 = edx_886
	branch al_908 == 0x00 l004029AD
l00402992:
	branch (byte) (word32) *edx_886 != 0x7F l00402985
	byte al_908 = (byte) (word32) *edx_886
	branch al_908 != 0x7F l00402985
l00402999:
	byte al_941 = (byte) (word32) *edx_886
	byte * ecx_943 = ecx_893 + 0x01
	*(ecx_943 - 0x01) = al_941
	struct Eq_3276 * edx_942 = edx_886
	branch al_941 != 0x00 l00402992
	byte al_949 = (byte) (word32) edx_942->b0002
	*ecx_943 = al_949
	ecx_893 = ecx_943 + 0x01
	edx_886 = edx_942->b0002 + 0x01
	branch al_949 != 0x00 l00402992
l004029AD:
	*esp_890 = esp_890
	branch _strdup(*esp_890) == 0x00 l004026EB
	esp_29->t0000 = esp_890
	Eq_44 eax_922 = _strdup(esp_29->t0000)
	eax_102.u0 = 0x01
	branch eax_922 == 0x00 l004026EB
l004029C6:
	Eq_44 ecx_933
	fn004025C0(eax_922, fp - 44, out ecx_933)
	word32 ecx_937
	eax_102 = fn004025C0(ecx_933, fp - 44, out ecx_937)
	goto l0040271D
l004029D5:
	esp_107->t0000 = *(ebp_126 - 44)
	fn004034A0(dwArg00)
	branch *(ebp_126 - 0x44) == 0x00 l004029F2
l004029E7:
	fn00402650(*(ebp_126 - 0x44), ebp_126->ptr0008)
l004029F2:
	*(ebp_126 - 0x38) = *(ebp_126 - 0x38) + 0x04
	union Eq_44 * edi_197 = *(ebp_126 - 0x38)
	esp_107->t0000 = *(edi_197 - 0x04)
	free(esp_107->t0000)
	eax_152 = *edi_197
	branch eax_152 != 0x00 l00402790
l00402A0E:
	eax_121 = *(ebp_126 - 0x20)
l00402A11:
	esp_107->t0000 = eax_121
	free(esp_107->t0000)
	return *(ebp_126 - 0x3C)
l00402A24:
	union Eq_44 * eax_544 = *(ebp_126 - 0x38)
	Eq_44 esi_545 = *(ebp_126 - 0x4C)
	*(ebp_126 - 100) = edx_256
	Eq_44 eax_547 = *eax_544
	esp_266->t0008 = esi_545
	esp_266->t0000 = &esp_266->t0008
	esp_266->t0004 = eax_547
	memcpy(esp_266->t0000, esp_266->t0004, esp_266->t0008)
	byte al_553 = (byte) (word32) Mem550[esp_266 + 11 + esi_545:byte]
	edx_256 = *(ebp_126 - 100)
	branch al_553 == 0x5C || al_553 == 0x2F l00402A80
	goto l00402A4F
l00402A4B:
l00402A4F:
	int32 esi_566 = *(ebp_126 - 0x4C)
	(&esp_266->t0008)[esi_566 / 0x0C] = (struct Eq_2921) (byte) (word32) *(ebp_126 - 0x5D)
	eax_267 = esi_566 + 0x01
	goto l00402837
l00402A63:
	fn00402630(eax_326, ebp_126->ptr0008)
	goto l00402958
l00402A72:
	*(ebp_126 - 0x3C) = 0x03
	goto l00402958
l00402A80:
	eax_267 = *(ebp_126 - 0x4C)
	goto l00402837
l00402A88:
	esp_29->t0000 = *(fp - 0x4C)
	word32 eax_733 = strlen(esp_29->t0000) + eax
	branch eax >= eax_733 l00402C31
l00402A9D:
	byte dl_795 = (byte) (word32) *eax_733
	branch dl_795 == 0x2F l00402C26
l00402AA9:
	branch dl_795 != 0x5C l00402ACB
	goto l00402C26
l00402AB5:
	byte al_818 = (byte) (word32) (eax_733 - (struct <anonymous> *) 0x01)->b0000
	branch al_818 == 0x5C || al_818 == 0x2F l00402B81
	goto l00402AC9
l00402AC1:
l00402AC9:
	eax_733 = edx_807
l00402ACB:
	Eq_44 edx_807 = eax_733 - (struct <anonymous> *) 0x01
	branch edx_807 != eax l00402AB5
l00402AD2:
	byte al_814 = (byte) (word32) (eax_733 - (struct <anonymous> *) 0x01)->b0000
	*(fp - 0x44) = (union Eq_44 *) edx_807
	*(fp - 0x61) = al_814
l00402ADC:
	branch *(fp - 0x61) != 0x5C && *(fp - 0x61) != 0x2F l00402BF2
l00402AE6:
	struct Eq_3740 * eax_759 = *(fp - 0x44)
	word32 edx_764 = (word32) eax_759->b0001
	byte cl_761 = (byte) (word32) *(fp - 0x61)
	byte * eax_762 = &eax_759->b0001
	byte dl_765 = (byte) edx_764
	branch dl_765 != 0x5C l00402B05
l00402AF8:
	eax_762 = eax_762 + 0x01
	edx_764 = (word32) *eax_762
	cl_761 = (byte) edx_764
	dl_765 = (byte) edx_764
	branch dl_765 == 0x5C l00402AF8
l00402B05:
	branch dl_765 == 0x2F l00402AF8
l00402B0A:
	*(fp - 0x44) = (byte **) eax_762
	*(fp - 0x61) = cl_761
l00402B10:
	branch *(fp - 0x4C) != 0x00 l00402762
l00402B1B:
	ebx_16 = *(fp - 0x44)
	goto l0040274E
l00402B23:
	word32 ebx_590 = *(ebp_126 - 0x68)
	branch ebx_590 != 0x00 l00402B52
l00402B2A:
	<anonymous> * edi_612 = *(ebp_126 - 0x5C)
	branch edi_612 == null l004029F2
l00402B35:
	esp_107->t0004 = *_errno()
	Eq_44 eax_620 = **(ebp_126 - 0x38)
	esp_107->t0000 = eax_620
	word32 edi_624
	word32 esi_625
	word32 ebx_626
	word32 eax_627
	byte SCZO_628
	word32 edx_629
	word32 ecx_630
	byte SZO_631
	byte C_632
	byte Z_633
	byte dh_634
	byte al_635
	byte cl_636
	byte dl_637
	word16 dx_638
	edi_612()
	branch eax_627 == 0x00 l004029F2
l00402B52:
	*(ebp_126 - 0x3C) = 0x01
	goto l004029F2
l00402B60:
	word32 edi_415 = *(ebp_126 - 0x44)
	*ebx_375.u0 = eax_389
	branch edi_415 != 0x00 l00402958
l00402B6D:
	*(ebp_126 - 0x44) = (union Eq_44 *) eax_389
	goto l00402958
l00402B75:
	*(ebp_126 - 0x4C) = 0x00
	goto l004027C8
l00402B81:
	*(fp - 0x44) = (union Eq_44 *) edx_807
	*(fp - 0x61) = al_818
	goto l00402ADC
l00402B8C:
	ebx_375.u0 = 0x00
	ecx_384 = 0x00
	goto l00402918
l00402B95:
l00402BA7:
	esp_29->t0000 = ebx_16
	word32 eax_672 = strlen(esp_29->t0000) + 0x10 & ~0x0F
	fn00401FD0(eax_672)
	union Eq_44 * esp_675 = esp_29 - eax_672
	ptr32 edx_679 = esp_675
	goto l00402BD3
l00402BC6:
	edx_679 = edx_679 + 0x01
	*(edx_679 - 0x01) = al_695
	ebx_16 = ebx_16
	branch al_695 == 0x00 l00402C05
l00402BD3:
	branch (byte) (word32) *ebx_16 != 0x7F l00402BC6
	byte al_695 = (byte) (word32) *ebx_16
	branch al_695 != 0x7F l00402BC6
l00402BDA:
	struct Eq_3623 * ebx_719 = ebx_16
	al_695 = (byte) (word32) ebx_719->b0001
	ebx_16 = &ebx_719->b0001
	goto l00402BC6
l00402BE3:
	eax_121 = *(fp - 0x3C)
	*(fp - 0x40) = 0x02
	goto l00402A11
l00402BF2:
l00402BFC:
	*(fp - 0x61) = 0x5C
	goto l00402B10
l00402C05:
	*esp_675 = esp_675
	fn00402630(_strdup(*esp_675), fp->ptr0004)
	eax_121 = *(fp - 0x24)
	*(fp - 0x40) = 0x00
	esp_107 = esp_29
	goto l00402A11
l00402C26:
	*(fp - 0x61) = dl_795
	*(fp - 0x44) = (union Eq_44 *) eax_733
	goto l00402ADC
l00402C31:
	byte cl_830 = (byte) (word32) *eax_733
	*(fp - 0x44) = (union Eq_44 *) eax_733
	*(fp - 0x61) = cl_830
	goto l00402ADC
fn00402690_exit:
}

Eq_44 fn00402C40(word32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10)
{
	Eq_44 ebx_148 = dwArg04;
	if (dwArg10 != null && (dwArg08 & 0x02) == 0x00)
		dwArg10->dw000C = 0x00;
	if (dwArg10->dw0000 != 0x0040A18A)
	{
		fn004022E0(dwArg10);
		dwArg10->dw0000 = 0x0040A18A;
	}
	Eq_44 eax_36 = fn00402690(dwArg04, (word16) dwArg08, fp - 0x04);
	if (eax_36 == 0x02 && (dwArg08 & 0x10) != 0x00)
	{
		*(fp - 0x24) = (union Eq_44 *) eax_36;
		*(fp - 0x20) = fp - 44;
		*(fp - 44) = (union Eq_44 *) dwArg04;
		word32 eax_77 = strlen(*(fp - 44)) + 0x10 & ~0x0F;
		fn00401FD0(eax_77);
		union Eq_44 * esp_81 = fp - 44 - eax_77;
		word32 ecx_80 = *(fp - 0x24);
		ptr32 edx_146 = esp_81;
		do
		{
			byte al_96 = (byte) (word32) *ebx_148;
			if (al_96 == 0x7F)
			{
				byte al_136 = (byte) (word32) *ebx_148;
				byte * edx_138 = edx_146 + 0x01;
				*(edx_138 - 0x01) = al_136;
				struct Eq_3957 * ebx_137 = ebx_148;
				byte al_144 = (byte) (word32) ebx_137->b0002;
				*edx_138 = al_144;
				edx_146 = edx_138 + 0x01;
				ebx_148 = ebx_137->b0002 + 0x01;
				if (al_144 == 0x00)
					break;
				continue;
			}
			edx_146 = edx_146 + 0x01;
			*(edx_146 - 0x01) = al_96;
			ebx_148 = ebx_148;
		} while (al_96 == 0x00);
		*(fp - 0x24) = ecx_80;
		*esp_81 = esp_81;
		fn00402630(_strdup(*esp_81), dwArg10);
		Eq_44 ecx_109 = *(fp - 0x24);
		struct Eq_2118 * esi_113 = *(fp - 0x0C);
		Eq_44 edi_115 = *(fp - 0x08);
		ptr32 ebp_117 = *(fp - 0x04);
		return ecx_109;
		*(ebp_117 - 0x20) = (union Eq_44 *) ecx_109;
		*fp = (union Eq_44 *) edi_115;
		fn00402630(_strdup(*fp), esi_113);
		return *(ebp_117 - 0x20);
	}
	else
		return eax_36;
}

Eq_44 fn00402D40(Eq_44 eax, word32 dwArg04)
{
fn00402D40_entry:
	struct Eq_4037 * esp_21
	word32 ebp_22
	word32 edi_23
	word32 esi_24
	word32 ebx_25
	byte SCZO_26
	Eq_44 eax_27
	byte SZO_28
	byte C_29
	byte Z_30
	word32 edx_31
	word32 ecx_32
	word16 cx_33
	word16 ax_34
	byte CZ_35
	word16 dx_36
	word16 di_37
	msvcrt.dll!setlocale()
	branch eax_27 == 0x00 l00402D70
	goto l00402D66
l00402D40:
l00402D66:
	esp_21->t0000 = eax_27
	_strdup(esp_21->t0000)
l00402D70:
	esp_21->dw0004 = 0x0040A19C
	esp_21->t0000.u0 = 0x02
	struct Eq_4065 * esp_44
	word32 ebp_45
	word32 edi_46
	Eq_44 esi_47
	Eq_44 ebx_48
	byte SCZO_49
	word32 eax_50
	byte SZO_51
	byte C_52
	byte Z_53
	word32 edx_54
	word32 ecx_55
	word16 cx_56
	word16 ax_57
	byte CZ_58
	word16 dx_59
	word16 di_60
	msvcrt.dll!setlocale()
	branch esi_47 == 0x00 || *esi_47 == 0x00 l00402D8D
	goto l00402E00
l00402D88:
l00402D8D:
	esp_44->t0008.u0 = 0x00
	esp_44->t0004.u0 = 0x0040A19E
	esp_44->t0000.u0 = 0x00
	Eq_44 eax_103 = wcstombs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	Mem105[esp_44 + 0x04:word32] = eax_103 + 0x01
	esp_44->t0000 = globals->t40D068
	Eq_44 eax_108 = realloc(esp_44->t0000, esp_44->t0004)
	globals->t40D068 = eax_108
	Mem110[esp_44 + 0x08:word32] = eax_103 + 0x01
	esp_44->t0004.u0 = 0x0040A19E
	esp_44->t0000 = eax_108
	Eq_44 eax_113 = wcstombs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	esp_44->t0004 = ebx_48
	esp_44->t0000.u0 = 0x02
	union Eq_44 * esp_116
	word32 ebp_117
	word32 edi_118
	word32 esi_119
	Eq_44 ebx_120
	byte SCZO_121
	word32 eax_122
	byte SZO_123
	byte C_124
	byte Z_125
	word32 edx_126
	word32 ecx_127
	word16 cx_128
	word16 ax_129
	byte CZ_130
	word16 dx_131
	word16 di_132
	msvcrt.dll!setlocale()
	*esp_116 = (union Eq_44 *) ebx_120
	free(*esp_116)
	return globals->t40D068
l00402E00:
	Eq_4205 dwLoc28_215
	esp_44->t0008.u0 = 0x00
	esp_44->t0004 = esi_47
	esp_44->t0000.u0 = 0x00
	Eq_44 eax_151 = mbstowcs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	word32 eax_153 = eax_151 + 0x12 + eax_151
	fn00401FD0(eax_153 & ~0x0F)
	struct Eq_4241 * esp_157 = esp_44 - (eax_153 & ~0x0F)
	esp_157->t0008 = eax_151
	esp_157->t0004 = esi_47
	word32 v13_160 = esp_157 + 0x0D >>u 0x01
	esp_157->t0000 = v13_160 * 0x02
	Eq_44 eax_169 = mbstowcs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	(eax_169 * 0x02)[v13_160] = 0x00
	word32 eax_177 = (word32) null[v13_160]
	word16 ax_178 = (word16) eax_177
	word16 wLoc2A_179 = ax_178
	branch eax_169 <= 0x01 l00402F5E
l00402E6C:
	branch ax_178 == 0x5C || ax_178 == 0x2F l00402E7C
	goto l00402F86
l00402E72:
l00402E7C:
	dwLoc28_215 = v13_160 * 0x02
	branch ax_178 == Mem172[(v13_160 + 0x02) + v13_160:word16] && Mem172[(v13_160 + 0x04) + v13_160:word16] == 0x00 l004030DF
l00402E90:
	word16 ax_220 = (word16) (word32) wLoc2A_179
	branch ax_220 == 0x00 l00403097
l00402E9D:
	Eq_4205 edx_224 = dwLoc28_215
	Eq_4205 edi_226 = dwLoc28_215
	goto l00402EB8
l00402EA4:
	branch ax_220 == 0x2F l00402ECA
l00402EAA:
	ax_220 = (word16) (word32) *edx_224
	ecx_484 = *edx_224
	branch ax_220 == 0x00 l00402EEC
l00402EB6:
	edx_224 = ecx_484
l00402EB8:
	word16 ax_497
	Eq_4205 ecx_484
	branch ax_220 != 0x5C l00402EA4
l00402EBE:
	ax_497 = (word16) (word32) *edx_224
	branch ax_497 != 0x5C l00402ED3
l00402EC7:
	edx_224 = edx_224
l00402ECA:
	ax_497 = (word16) (word32) *edx_224
	branch ax_497 == 0x5C l00402EC7
l00402ED3:
	branch ax_497 == 0x2F l00402EC7
l00402ED9:
	branch ax_497 == 0x00 l00402EEC
l00402EDE:
	ax_220 = (word16) (word32) *edx_224
	edi_226 = edx_224
	ecx_484 = edx_224
	branch ax_220 != 0x00 l00402EB6
l00402EEC:
	branch dwLoc28_215 < edi_226 l00402F71
l00402EF3:
	word16 * eax_258
	branch wLoc2A_179 == 0x5C || wLoc2A_179 == 0x2F l00402F05
	goto l004030BF
l00402EFA:
l00402F05:
	eax_258 = (word16 *) dwLoc28_215
l00402F0B:
	*eax_258 = 0x00
	esp_157->t0008.u0 = 0x00
	esp_157->t0000.u0 = 0x00
	esp_157->t0004 = v13_160 * 0x02
	Eq_44 eax_269 = wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	Mem271[esp_157 + 0x04:word32] = eax_269 + 0x01
	esp_157->t0000 = globals->t40D068
	Eq_44 eax_274 = realloc(esp_157->t0000, esp_157->t0004)
	globals->t40D068 = eax_274
	Mem277[esp_157 + 0x08:word32] = eax_269 + 0x01
	esp_157->t0000 = eax_274
	esp_157->t0004 = v13_160 * 0x02
	wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	goto l00403047
l00402F5E:
	dwLoc28_215 = v13_160 * 0x02
	goto l00402E90
l00402F69:
	branch dx_473 != 0x2F l00402FB5
l00402F6F:
	edi_226 = eax_302
l00402F71:
	Eq_4205 eax_302 = edi_226 - 0x02
	branch dwLoc28_215 >= eax_302 l00402FB5
l00402F78:
	word16 dx_473 = (word16) (word32) *(edi_226 - 0x02)
	branch dx_473 != 0x5C l00402F69
l00402F82:
	edi_226 = eax_302
	goto l00402F71
l00402F86:
	dwLoc28_215 = v13_160 * 0x02
	branch Mem172[v13_160 + 0x02 + v13_160:word16] != 0x3A l00402E90
l00402F9B:
	dwLoc28_215 = v13_160 * 0x02 + 0x04
	wLoc2A_179 = (word16) (word32) Mem172[v13_160 + 0x04 + v13_160:word16]
	goto l00402E90
l00402FB5:
	branch dwLoc28_215 == eax_302 l004030F5
l00402FBE:
	*eax_302 = 0x00
	word16 dx_318 = (word16) (word32) null[v13_160]
	struct Eq_4495 * eax_319 = v13_160 * 0x02
	branch dx_318 != 0x5C && dx_318 != 0x2F l0040309F
l00402FD8:
	eax_319 = eax_319 + 0x01
	word16 cx_439 = (word16) (word32) eax_319->w0000
	branch cx_439 == 0x5C || cx_439 == 0x2F l00402FD8
	goto l00402FEA
l00402FE4:
l00402FEA:
	branch eax_319 - v13_160 * 0x02 <= 0x05 l004030A9
l00402FF8:
	eax_319 = v13_160 * 0x02
l00402FFB:
	struct Eq_4495 * ecx_331 = eax_319
l00402FFD:
	branch dx_318 == 0x00 l00403023
l00403002:
	ecx_331 = ecx_331 + 0x01
	*(ecx_331 - 0x02) = dx_318
	branch dx_318 == 0x2F l00403072
l0040300F:
	word32 edi_402 = eax_319 + 0x02
	branch eax_319->w0000 == 0x5C l00403070
l00403018:
	dx_318 = (word16) (word32) eax_319[0x01]
	eax_319 = edi_402
	branch dx_318 != 0x00 l00403002
l00403023:
	ecx_331->w0000 = 0x00
	esp_157->t0008 = eax_169
	esp_157->t0000 = esi_47
	esp_157->t0004 = v13_160 * 0x02
	Eq_44 eax_360 = wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	branch eax_360 == ~0x00 l00403047
l00403043:
	Mem364[esi_47 + eax_360:byte] = 0x00
l00403047:
	esp_157->t0004 = ebx_48
	esp_157->t0000.u0 = 0x02
	union Eq_44 * esp_184
	word32 ebp_185
	word32 edi_186
	Eq_44 esi_187
	Eq_44 ebx_188
	byte SCZO_189
	word32 eax_190
	byte SZO_191
	byte C_192
	byte Z_193
	word32 edx_194
	word32 ecx_195
	word16 cx_196
	word16 ax_197
	byte CZ_198
	word16 dx_199
	word16 di_200
	msvcrt.dll!setlocale()
	*esp_184 = (union Eq_44 *) ebx_188
	free(*esp_184)
	return esi_187
l00403070:
	eax_319 = edi_402
l00403072:
	dx_318 = (word16) (word32) eax_319->w0000
	branch dx_318 != 0x2F l004030D4
l00403080:
	eax_319 = eax_319 + 0x02
	dx_318 = (word16) (word32) eax_319->w0000
	branch dx_318 == 0x5C || dx_318 == 0x2F l00403080
	goto l00402FFD
l0040308C:
l0040309F:
l004030A9:
	branch Mem315[v13_160 + 0x02 + v13_160:word16] != dx_318 l00402FF8
	branch Mem315[v13_160 + 0x02 + v13_160:word16] != dx_318 l00402FF8
l004030B7:
	dx_318 = (word16) (word32) eax_319->w0000
	goto l00402FFB
l004030BF:
	*dwLoc28_215 = 0x2E
	eax_258 = (word16 *) dwLoc28_215
	goto l00402F0B
l004030D4:
	branch dx_318 == 0x5C l00403080
	goto l00402FFD
l004030DF:
l004030F5:
	branch wLoc2A_179 == 0x5C l0040310A
l004030FC:
	eax_302 = dwLoc28_215
	branch wLoc2A_179 != 0x2F l00402FBE
l0040310A:
	eax_302 = dwLoc28_215
	branch *dwLoc28_215 != (word16) ((word32) wLoc2A_179) l00402FBE
l0040311B:
	word16 dx_459 = (word16) (word32) *dwLoc28_215
	branch dx_459 == 0x2F l00402FBE
l00403129:
	eax_302 = edi_226
	branch dx_459 != 0x5C l00402FBE
l00403135:
	eax_302 = dwLoc28_215
	goto l00402FBE
fn00402D40_exit:
}

Eq_44 fn00403140(Eq_44 eax, word16 dx)
{
	if (FindNextFileA(eax, fp + 4294966964) != 0x00)
	{
		Eq_44 ebx_65;
		struct Eq_4667 * ebp_66;
		struct Eq_4668 * esi_67;
		word16 ax_68 = fn00405500(edx + 0x0C, 0x0104, 0x0040A1A4, out ebx_65, out ebp_66, out esi_67);
		esi_67->w0006 = ax_68;
		word32 eax_70 = ebp_66->dwFFFFFEB8;
		uint32 eax_73 = DPB(eax_70, (byte) eax_70 & 88, 0);
		if (eax_73 <= 0x10)
		{
			esi_67->dw0008 = eax_73;
			return ebx_65;
		}
		else
		{
			esi_67->dw0008 = 0x18;
			return ebx_65;
		}
	}
	else
	{
		if (GetLastError() != 0x12)
			*_errno() = 0x02;
		return 0x00;
	}
}

Eq_44 fn004031E0(Eq_44 eax, Eq_44 edx)
{
	Eq_44 eax_19 = FindFirstFileA(eax, fp + 4294966964);
	Eq_44 esi_24 = eax_19;
	if (eax_19 != ~0x00)
	{
		struct Eq_4745 * ebx_52;
		struct Eq_4746 * ebp_53;
		word16 ax_55 = fn00405500(edx, 0x0104, 0x0040A1A4, out ebx_52, out ebp_53, out esi_24);
		word32 ecx_56 = ebp_53->dwFFFFFEB8;
		ebx_52->w0006 = ax_55;
		uint32 ecx_59 = DPB(ecx_56, (byte) ecx_56 & 88, 0);
		ebx_52->dw0008 = ecx_59;
		if (ecx_59 > 0x10)
			ebx_52->dw0008 = 0x18;
	}
	else
	{
		Eq_44 eax_65 = _errno();
		Eq_44 eax_67 = GetLastError();
		*eax_65 = eax_67;
		if (eax_67 != 0x03)
		{
			if (*_errno() != 0x010B)
			{
				if (*_errno() != 0x02)
				{
					*_errno() = 22;
					esi_24 = eax_19;
				}
			}
			else
				*_errno() = 0x14;
		}
		else
			*_errno() = 0x02;
	}
	return esi_24;
}

Eq_44 fn004032B0(word32 dwArg04)
{
	esp = fp;
	esp = fp - 0x04;
	dwLoc04 = ebp;
	esp = fp - 0x08;
	dwLoc08 = edi;
	esp = fp - 0x0C;
	dwLoc0C = esi;
	esp = fp - 0x10;
	dwLoc10 = ebx;
	esp = fp - 0x013C;
	eax = dwArg04;
	SZO = cond(eax & eax);
	Z = SZO;
	C.u0 = false;
	if (Test(EQ,Z))
	{
		eax = _errno();
		*eax = 22;
		eax.u0 = 0x00;
		SZO = cond(0x00);
		C.u0 = false;
		goto l004033DD;
	}
	SCZO = cond(*eax.u0 - 0x00);
	if (Test(EQ,Z))
	{
		eax = _errno();
		*eax.u0 = 0x02;
		eax.u0 = 0x00;
		SZO = cond(0x00);
		C.u0 = false;
		goto l004033DD;
	}
	edi = fp - 288;
	dwLoc0134.u0 = 0x0104;
	ebx = fp - 288;
	dwLoc0138 = eax;
	dwLoc013C = fp - 288;
	eax = _fullpath(dwLoc013C, dwLoc0138, 0x0104);
	SCZO = cond(bLoc0120 - 0x00);
	if (Test(NE,Z))
	{
		do
		{
			edx = *ebx;
			ebx = ebx;
			eax = edx;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
		SZO = cond(eax & 0x8080);
		C.u0 = false;
		if (Test(NE,Z))
		{
			al = al + al;
			SCZO = cond(al);
			ebx = ebx - 0x03 - C;
			ebx = ebx - (fp - 288);
			eax = (word32) Mem0[fp - 0x0121 + ebx:byte];
			SCZO = cond(al - 0x5C);
			if (Test(EQ,Z))
				goto l00403374;
		}
		else
		{
			eax = eax >> 0x10;
			ebx = ebx;
			al = al + al;
			SCZO = cond(al);
			ebx = ebx - 0x03 - C;
			ebx = ebx - (fp - 288);
			eax = (word32) Mem0[fp - 0x0121 + ebx:byte];
			SCZO = cond(al - 0x5C);
			if (Test(EQ,Z))
				goto l00403374;
		}
		SCZO = cond(al - 0x2F);
		if (Test(EQ,Z))
		{
l00403374:
			edx.u0 = 0x2A;
			eax = *ebx;
			Mem0[fp - 288 + ebx:word16] = dx;
			dwLoc013C = eax;
			eax = malloc(dwLoc013C);
			SZO = cond(eax & eax);
			C.u0 = false;
			esi = eax;
			if (Test(NE,Z))
			{
				ebp = *eax.u0;
				ebx = *ebx;
				SCZO = cond(ebx);
				dwLoc0134 = ebx;
				dwLoc0138 = fp - 288;
				dwLoc013C = ebp;
				eax = memcpy(dwLoc013C, dwLoc0138, dwLoc0134);
				edx = esi;
				eax = ebp;
				eax = fn004031E0(eax, edx);
				SCZO = cond(eax - ~0x00);
				*esi = eax;
				if (Test(NE,Z))
				{
					eax.u0 = 0x0110;
					esi->u1 = ax;
					eax = esi;
					*esi = 0x00;
					*esi = 0x00;
				}
				else
				{
					*esp = esi;
					free(*esp);
					eax.u0 = 0x00;
					SZO = cond(0x00);
					C.u0 = false;
				}
			}
			else
			{
				eax = _errno();
				*eax.u0 = 0x0C;
				eax.u0 = 0x00;
				SZO = cond(0x00);
				C.u0 = false;
			}
l004033DD:
			esp = *esp;
			SCZO = cond(esp);
			ebx = *esp;
			esp = *esp;
			esi = *esp;
			esp = *esp;
			edi = *esp;
			esp = *esp;
			ebp = *esp;
			esp = *esp;
			return eax;
		}
		ecx = 0x5C;
		Mem0[fp - 288 + ebx:word16] = cx;
		ebx = fp - 288;
		do
		{
			edx = *ebx;
			ebx = *ebx;
			eax = *edx.u0;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
	}
	else
	{
		do
		{
			edx = *ebx;
			ebx = ebx;
			eax = edx;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
	}
	SZO = cond(eax & 0x8080);
	SZO = cond(eax & 0x8080);
	C.u0 = false;
	if (Test(EQ,Z))
	{
		eax = eax >> 0x10;
		ebx = *ebx;
		SCZO = cond(ebx);
	}
	al = al + al;
	SCZO = cond(al);
	ebx = ebx - 0x03 - C;
	ebx = ebx - (fp - 288);
	al = al + al;
	SCZO = cond(al);
	ebx = ebx - 0x03 - C;
	ebx = ebx - (fp - 288);
	SCZO = cond(ebx);
	goto l00403374;
}

Eq_5101 * fn00403450(word32 dwArg04, ptr32 & ebpOut)
{
	*ebpOut = ebp;
	struct Eq_5101 * eax_16;
	if (dwArg04 == null)
	{
		*_errno() = 0x09;
		eax_16 = null;
		return eax_16;
	}
	int32 eax_24 = dwArg04->dw0114;
	dwArg04->dw0114 = eax_24 + 0x01;
	if (eax_24 > 0x00)
	{
		eax_16 = fn00403140(dwArg04->t0110, (word16) dwArg04);
		if (eax_16 == null)
			return eax_16;
	}
	eax_16 = dwArg04;
	return eax_16;
}

void fn004034A0(word32 dwArg04)
{
	if (dwArg04 != 0x00 && FindClose(*dwArg04) != 0x00)
		free(dwArg04);
	else
		*_errno() = 0x09;
	return;
}

void fn004036F0(Eq_5155 al, Eq_5156 * edx)
{
	int32 ebx_33;
	byte ch_9 = edx->b0005;
	if ((ch_9 & 0x20) == 0x00)
	{
		ebx_33 = edx->dw0018;
		if (edx->dw001C <= ebx_33)
			goto l00403714;
	}
	if ((ch_9 & 0x10) != 0x00)
	{
		word32 esp_59;
		word32 ebx_60;
		byte SCZO_61;
		word32 ecx_62;
		word32 edx_63;
		byte ch_64;
		byte SZO_65;
		byte C_66;
		byte Z_67;
		byte al_68;
		word32 eax_69;
		msvcrt.dll!fputc();
		edx->dw0018 = edx->dw0018 + 0x01;
		return;
	}
	edx->ptr0000[edx->dw0018].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00] = al;
	ebx_33 = edx->dw0018;
l00403714:
	edx->dw0018 = ebx_33 + 0x01;
	return;
}

word32 fn00404B90(word32 dwArg04, ptr32 dwArg08, word32 dwArg0C, word32 dwArg10, word32 dwArg14, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	*ebpOut = ebp;
	*esiOut = esi;
	*ebxOut = ebx;
	struct Eq_5220 * esi_145 = dwArg10;
	char * eax_39 = getenv("PRINTF_EXPONENT_DIGITS");
l00404C20:
	int32 eax_143 = (int32) esi_145->b0000;
	struct Eq_5220 * ebx_144 = esi_145[0x01];
	Eq_5155 al_134 = (byte) eax_143;
	struct Eq_5220 * ecx_137 = ebx_144;
	if (eax_143 != 0x00)
	{
		do
		{
			if (eax_143 != 0x25)
			{
				fn004036F0(al_134, fp - 0x40);
				esi_145 = ebx_144;
				goto l00404C20;
			}
			word32 eax_149 = fp->dw0004;
			*(fp - 0x34) = ~0x00;
			*(fp - 0x38) = ~0x00;
			*(fp - 88) = 0x00;
			*(fp - 0x3C) = eax_149;
			word32 edx_154 = (word32) esi_145[0x01];
			*(fp - 0x54) = fp - 0x38;
			*(fp - 0x5C) = 0x00;
			byte dl_155 = (byte) edx_154;
			while (dl_155 != 0x00)
			{
				cu8 al_176 = (byte) (edx_154 - 0x20);
				int32 edi_177 = (int32) dl_155;
				struct Eq_5220 * esi_180 = ecx_137[0x01];
				if (al_176 <= 0x5A)
				{
					ui32 eax_181 = (word32) al_176;
					word32 esp_185;
					word32 ebp_186;
					word32 edi_187;
					word32 esi_188;
					word32 ebx_189;
					byte SCZO_190;
					word32 eax_191;
					byte SZO_192;
					byte C_193;
					word16 ax_194;
					byte Z_195;
					byte CZ_196;
					byte ah_197;
					word32 ecx_198;
					word32 edx_199;
					byte dl_200;
					byte al_201;
					byte S_202;
					(*globals->a40A1DC)();
					return eax_191;
				}
				word32 eax_203 = *(fp - 0x5C);
				if (eax_203 == 0x04 || (byte) (edx_154 - 0x30) > 0x09)
				{
					fn004036F0(0x25, fp - 0x40);
					esi_145 = ebx_144;
					goto l00404C20;
				}
				if (eax_203 != 0x00)
				{
					if (eax_203 == 0x02)
						*(fp - 0x5C) = 0x03;
				}
				else
					*(fp - 0x5C) = 0x01;
				if (*(fp - 0x54) != 0x00)
				{
					int32 eax_240 = **(fp - 0x54);
					if (eax_240 < 0x00)
					{
						**(fp - 0x54) = edi_177 - 0x30;
						edx_154 = (word32) ecx_137[0x01];
						dl_155 = (byte) edx_154;
						ecx_137 = esi_180;
						continue;
					}
					**(fp - 0x54) = edi_177 - 0x30 + (eax_240 * 0x05) * 0x02;
				}
				edx_154 = (word32) ecx_137[0x01];
				dl_155 = (byte) edx_154;
				ecx_137 = esi_180;
			}
			eax_143 = (int32) ecx_137->b0000;
			ebx_144 = (struct Eq_5220 *) ecx_137[0x01];
			esi_145 = ecx_137;
			al_134 = (byte) eax_143;
			ecx_137 = ebx_144;
		} while (eax_143 != 0x00);
	}
	return *(fp - 0x28);
	word32 ebx_125;
	*ebxOut = fp->dw005C;
	word32 esi_127;
	*esiOut = fp->dw0060;
	word32 ebp_131;
	*ebpOut = fp->dw0068;
	return fp->dw0044;
}

word16 fn00405500(word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 & ebxOut, ptr32 & ebpOut, HANDLE & esiOut)
{
	*ebxOut = ebx;
	*esiOut = esi;
	word32 ebp_15;
	return fn00405530(dwArg04, dwArg08, dwArg0C, fp + 0x10, out ebp_15);
}

word16 fn00405530(word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 dwArg10, ptr32 & ebpOut)
{
	if (dwArg08 == 0x00)
	{
		word32 ebx_64;
		word32 ebp_65;
		word32 esi_66;
		return (word16) fn00404B90(0x00, dwArg04, 0x00, dwArg0C, dwArg10, out ebx_64, out ebp_65, out esi_66);
	}
	else
	{
		Eq_5521 (* ebx_42)[];
		word32 ebp_43;
		Eq_1805 esi_44;
		Eq_1805 eax_45 = fn00404B90(0x00, dwArg04, dwArg08 - 0x01, dwArg0C, dwArg10, out ebx_42, out ebp_43, out esi_44);
		word16 ax_46 = (word16) eax_45;
		Eq_1805 edx_49 = eax_45;
		if (eax_45 > esi_44)
			edx_49 = esi_44;
		Mem51[ebx_42 + edx_49:byte] = 0x00;
		return ax_46;
	}
}

void fn004081F8(word32 * ecx)
{
	*ecx = 0x00;
	return;
}

void fn0040820C(word32 * ecx)
{
	*ecx = 0x01;
	return;
}

void fn00408220(word32 * ecx)
{
	if (*ecx == 0x01)
		fn004082A8(0x0040A0C0);
	else
		fn004082A8(0x0040A0CA);
	return;
}

void fn00408250(word32 * ecx, word32 dwArg04)
{
	if (dwArg04 == 0x01 && *ecx == 0x00)
		fn0040820C(ecx);
	else if (dwArg04 == 0x00 && *ecx == 0x01)
		fn004081F8(ecx);
	return;
}

void fn00408294(word32 * ecx)
{
	*ecx = 0x00;
	return;
}

void fn004082A8(word32 dwArg04)
{
	fn00402000(dwArg04, fp + 0x08);
	return;
}

