// datatypesCPP.c
// Generated by decompiling datatypesCPP.exe
// using Reko decompiler version 0.6.2.0.

#include "datatypesCPP.h"

void fn00401180(word32 ecx, word32 ebx)
{
	ptr32 ebp_160 = fp - 0x04;
	LPTOP_LEVEL_EXCEPTION_FILTER * esp_10 = fp - 0x1C;
	<anonymous> * eax_12 = globals->ptr40A158;
	if (eax_12 != null)
	{
		word32 esp_159;
		byte SCZO_162;
		word32 eax_163;
		byte SZO_164;
		byte C_165;
		byte Z_166;
		word32 edx_167;
		word32 esi_169;
		word32 edi_170;
		byte bpl_171;
		eax_12();
		esp_10 = esp_159 - 0x0C;
	}
	*esp_10 = (LPTOP_LEVEL_EXCEPTION_FILTER *) &globals->t401000;
	SetUnhandledExceptionFilter(*esp_10);
	fn00401D60(ecx, ebx);
	fn00401E40();
	word32 ecx_39 = fn00401A50(ebp_160);
	union Eq_43 * esp_36 = esp_10;
	Eq_43 eax_40 = globals->t40D020;
	if (eax_40 != 0x00)
	{
		globals->t409004 = eax_40;
		*esp_36 = (union Eq_43 *) eax_40;
		word32 eax_103 = iob->dw0010;
		*(esp_36 - 0x04) = eax_103;
		struct Eq_181 * esp_105;
		word32 ebp_106;
		struct Eq_183 * ebx_107;
		byte SCZO_108;
		word32 eax_109;
		byte SZO_110;
		byte C_111;
		byte Z_112;
		word32 edx_113;
		word32 ecx_114;
		word32 esi_115;
		word32 edi_116;
		byte bpl_117;
		setmode();
		esp_105->t0000 = globals->t40D020;
		word32 eax_121 = ebx_107->dw0030;
		esp_105->dwFFFFFFFC = eax_121;
		struct Eq_208 * esp_123;
		word32 ebp_124;
		struct Eq_210 * ebx_125;
		byte SCZO_126;
		word32 eax_127;
		byte SZO_128;
		byte C_129;
		byte Z_130;
		word32 edx_131;
		word32 ecx_132;
		word32 esi_133;
		word32 edi_134;
		byte bpl_135;
		setmode();
		esp_123->t0000 = globals->t40D020;
		word32 eax_139 = ebx_125->dw0050;
		esp_123->dwFFFFFFFC = eax_139;
		word32 esp_141;
		word32 ebp_142;
		word32 ebx_143;
		byte SCZO_144;
		word32 eax_145;
		byte SZO_146;
		byte C_147;
		byte Z_148;
		word32 edx_149;
		word32 ecx_150;
		word32 esi_151;
		word32 edi_152;
		byte bpl_153;
		setmode();
	}
	word32 esp_44;
	word32 ebp_45;
	word32 ebx_46;
	byte SCZO_47;
	union Eq_43 * eax_48;
	byte SZO_49;
	byte C_50;
	byte Z_51;
	word32 edx_52;
	Eq_43 ecx_53;
	word32 esi_54;
	word32 edi_55;
	byte bpl_56;
	_p__fmode();
	Eq_43 edx_58 = globals->t409004;
	*eax_48 = (union Eq_43 *) edx_58;
	word32 edx_60;
	byte bpl_61;
	Eq_43 ecx_62 = fn00402360(ecx_53, edx_58, esi_54, edi_55, out edx_60, out bpl_61);
	__align(esp_44 + ~0x03);
	word32 eax_63 = fn00401ED0(esi_54);
	struct Eq_104 * esp_64;
	word32 ebp_65;
	word32 ebx_66;
	byte SCZO_67;
	word32 * eax_68;
	byte SZO_69;
	byte C_70;
	byte Z_71;
	word32 edx_72;
	word32 ecx_73;
	word32 esi_74;
	word32 edi_75;
	byte bpl_76;
	_p__environ();
	esp_64->dw0004 = *eax_68;
	esp_64->dw0000 = globals->dw40D000;
	word32 eax_82 = globals->dw40D004;
	esp_64->dwFFFFFFFC = eax_82;
	fn00401410(bpl_76, esi_74);
	struct Eq_141 * esp_85;
	word32 ebp_86;
	Eq_143 ebx_87;
	byte SCZO_88;
	word32 eax_89;
	byte SZO_90;
	byte C_91;
	byte Z_92;
	word32 edx_93;
	word32 ecx_94;
	word32 esi_95;
	word32 edi_96;
	byte bpl_97;
	cexit();
	esp_85->tFFFFFFFC = ebx_87;
	ExitProcess(esp_85->tFFFFFFFC);
}

void fn00401260()
{
	word32 esp_16;
	byte SCZO_17;
	word32 eax_18;
	byte SZO_19;
	byte C_20;
	_getmainargs();
	return;
}

Eq_43 Win32CrtStartup()
{
	word32 esp_5;
	byte SCZO_6;
	word32 esi_7;
	word32 edi_8;
	word32 eax_9;
	word32 ecx_10;
	word32 ebx_11;
	_set_app_type();
	fn00401180(ecx_10, ebx_11);
	word32 esp_18;
	byte SCZO_19;
	word32 esi_20;
	word32 edi_21;
	word32 eax_22;
	word32 ecx_23;
	word32 ebx_24;
	_set_app_type();
	fn00401180(ecx_23, ebx_24);
	return fn004012E0();
}

int32 fn004012E0()
{
	return atexit(*esp_1);
}

void fn00401410(byte bpl, word32 esi)
{
	__align(fp - 0x10);
	fn00401ED0(esi);
	*(fp - 33) = 0x61;
	*(fp - 0x24) = 0x61;
	*(fp - 0x28) = 0x61;
	*(fp - 0x2A) = 0x61;
	*(fp - 0xD0) = fp - 0x2A;
	*(fp - 212) = fp - 0x28;
	*(fp - 0xD8) = fp - 0x24;
	*(fp - 220) = fp - 33;
	*(fp - 0xE0) = 0x0040A0C0;
	struct Eq_358 * esp_31;
	word32 ebp_32;
	word32 edi_33;
	word32 esi_34;
	word32 ebx_35;
	byte SCZO_36;
	word32 eax_37;
	word16 ax_38;
	word32 ecx_39;
	word32 edx_40;
	byte al_41;
	word16 cx_42;
	byte cl_43;
	byte bpl_44;
	msvcrt.dll!scanf();
	word16 ax_50 = (word16) (word32) esp_31->w00BC;
	byte al_53 = (byte) (word32) esp_31->b00BF;
	word32 * ebx_47 = (word32) (word16) (word32) esp_31->w00B6;
	word32 * ecx_48 = esp_31->ptr00B8;
	esp_31->ptr0010 = ebx_47;
	esp_31->ptr000C = ecx_48;
	word16 * edx_51 = (word32) ax_50;
	esp_31->ptr0008 = edx_51;
	esp_31->ptr0004 = (int32) al_53;
	esp_31->dw0000 = 0x0040A0CC;
	fn00408778(dwArg00);
	esp_31->b00B5 = 0x10;
	esp_31->w00B2 = 0x10;
	esp_31->dw00AC = 0x10;
	esp_31->dw00A8 = 0x10;
	esp_31->dw00A0 = 0x10;
	esp_31->dw00A4 = 0x00;
	esp_31->ptr0014 = (word32 *) &esp_31->dw00A0;
	esp_31->ptr0010 = (word32 *) &esp_31->dw00A8;
	esp_31->ptr000C = (word32 *) &esp_31->dw00AC;
	esp_31->ptr0008 = (word16 *) &esp_31->w00B2;
	esp_31->ptr0004 = (byte *) &esp_31->b00B5;
	esp_31->dw0000 = 0x0040A0D9;
	struct Eq_473 * esp_78;
	word32 ebp_79;
	word32 edi_80;
	word32 esi_81;
	word32 ebx_82;
	byte SCZO_83;
	word32 eax_84;
	word16 ax_85;
	word32 ecx_86;
	word32 edx_87;
	byte al_88;
	word16 cx_89;
	byte cl_90;
	byte bpl_91;
	msvcrt.dll!scanf();
	word16 cx_97 = (word16) (word32) esp_78->w00B2;
	byte cl_100 = (byte) (word32) esp_78->b00B5;
	word32 edx_93 = esp_78->dw00A4;
	word32 * edi_94 = esp_78->ptr00A8;
	word32 * esi_95 = esp_78->ptr00AC;
	esp_78->ptr0014 = esp_78->ptr00A0;
	esp_78->dw0018 = edx_93;
	esp_78->ptr0010 = edi_94;
	esp_78->ptr000C = esi_95;
	word16 * ebx_98 = (int32) cx_97;
	esp_78->ptr0008 = ebx_98;
	byte * ecx_101 = (int32) cl_100;
	esp_78->ptr0004 = ecx_101;
	esp_78->dw0000 = 0x0040A0E8;
	fn00408778(dwArg00);
	esp_78->b009F = 0x10;
	esp_78->w009C = 0x10;
	esp_78->dw0098 = 0x10;
	esp_78->dw0094 = 0x10;
	esp_78->dw0088 = 0x10;
	esp_78->dw008C = 0x00;
	esp_78->ptr0014 = (word32 *) &esp_78->dw0088;
	esp_78->ptr0010 = (word32 *) &esp_78->dw0094;
	esp_78->ptr000C = (word32 *) &esp_78->dw0098;
	esp_78->ptr0008 = (word16 *) &esp_78->w009C;
	esp_78->ptr0004 = (byte *) &esp_78->b009F;
	esp_78->dw0000 = 0x0040A0D9;
	struct Eq_596 * esp_126;
	word32 ebp_127;
	word32 edi_128;
	word32 esi_129;
	word32 ebx_130;
	byte SCZO_131;
	word32 eax_132;
	word16 ax_133;
	word32 ecx_134;
	word32 edx_135;
	byte al_136;
	word16 cx_137;
	byte cl_138;
	byte bpl_139;
	msvcrt.dll!scanf();
	word16 cx_145 = (word16) (word32) esp_126->w009C;
	byte cl_148 = (byte) (word32) esp_126->b009F;
	word32 edx_141 = esp_126->dw008C;
	word32 edi_142 = esp_126->dw0094;
	word32 * esi_143 = esp_126->ptr0098;
	esp_126->dw0014 = esp_126->dw0088;
	esp_126->dw0018 = edx_141;
	esp_126->dw0010 = edi_142;
	esp_126->ptr000C = esi_143;
	real64 * ebx_146 = (word32) cx_145;
	esp_126->ptr0008 = ebx_146;
	esp_126->ptr0004 = (word32) cl_148;
	esp_126->dw0000 = 0x0040A0E8;
	fn00408778(dwArg00);
	esp_126->dw0084 = globals->dw40A148;
	esp_126->r0078 = globals->r40A150;
	esp_126->dw0060 = 0x99999800;
	esp_126->dw0064 = 0x81999999;
	esp_126->dw0068 = 0x4003;
	esp_126->ptr000C = (word32 *) &esp_126->dw0060;
	esp_126->ptr0008 = (real64 *) &esp_126->r0078;
	esp_126->ptr0004 = (word32 *) &esp_126->dw0084;
	esp_126->dw0000 = 0x0040A0F8;
	struct Eq_706 * esp_174;
	word32 ebp_175;
	word32 edi_176;
	word32 esi_177;
	word32 ebx_178;
	byte SCZO_179;
	word32 eax_180;
	word16 ax_181;
	word32 ecx_182;
	word32 edx_183;
	byte al_184;
	word16 cx_185;
	byte cl_186;
	byte bpl_187;
	msvcrt.dll!scanf();
	word32 edx_189 = esp_174->dw0064;
	word32 ecx_190 = esp_174->dw0068;
	real64 rLoc1_191 = esp_174->r0078;
	real64 rLoc2_192 = (real64) esp_174->r0084;
	esp_174->dw0014 = esp_174->dw0060;
	esp_174->dw0018 = edx_189;
	esp_174->dw001C = ecx_190;
	esp_174->r000C = rLoc1_191;
	esp_174->r0004 = rLoc2_192;
	esp_174->dw0000 = 0x0040A101;
	fn00408778(dwArg00);
	esp_174->b00CF = 0x01;
}

int32 fn00401A50(ptr32 ebp)
{
	if ((globals->b409000 & 0x02) == 0x00)
	{
		fn00401260();
		return ecx;
	}
	Eq_43 eax_43 = GetCommandLineA();
	Eq_43 eax_47 = strlen(eax_43);
	word32 eax_48 = eax_47 + 0x11 + eax_47;
	fn00402550(eax_48 & ~0x0F);
	Eq_43 esi_163 = eax_43;
	struct Eq_796 * esp_52 = fp - 0x5C - (eax_48 & ~0x0F);
	int32 eax_161 = 0x00;
	byte al_157 = 0x00;
l00401AC7:
	esi_163 = esi_163 + 0x01 + 0x01;
	ci8 bl_156 = (byte) (word32) *(esi_163 - 0x01);
	int32 ecx_112 = (int32) bl_156;
	if (ecx_112 == 0x00)
	{
l00401B50:
		byte * eax_104;
		byte * edx_148 = *(fp - 0x30);
		if (eax_161 != 0x00)
		{
			eax_104 = edx_148 + eax_161;
			do
			{
				edx_148 = edx_148 + 0x01;
				*(edx_148 - 0x01) = 0x5C;
			} while (edx_148 != eax_104);
		}
		else
			eax_104 = edx_148;
		if (*(fp - 0x38) != 0x00 || *(fp - 0x40) < eax_104)
		{
			*eax_104 = 0x00;
			esp_52->ptr000C = fp - 44;
			esp_52->dw0008 = 0x00;
			esp_52->dw0004 = *(fp - 0x3C);
			esp_52->dw0000 = *(fp - 0x40);
			ecx_112 = fn004031C0(dwArg00, dwArg04, dwArg08, dwArg0C);
		}
		globals->dw40D004 = *(fp - 0x28);
		globals->dw40D000 = *(fp - 0x24);
		return ecx_112;
	}
l00401AD5:
	word32 edi_171;
	if (bl_156 != 0x3F)
	{
		if (bl_156 <= 0x3F)
		{
			byte * ebx_291;
			if (bl_156 == 0x27)
			{
				if ((globals->b409000 & 0x10) != 0x00)
				{
					int32 ebx_353 = eax_161 >> 0x01;
					if (ebx_353 != 0x00)
					{
						byte * edx_377 = *(fp - 0x30);
						ebx_291 = edx_377 + ebx_353;
						do
						{
							edx_377 = edx_377 + 0x01;
							*(edx_377 - 0x01) = 0x5C;
						} while (edx_377 != ebx_291);
					}
					else
						ebx_291 = (byte *) *(fp - 0x30);
					if ((al_157 & 0x01) != 0x00 || *(fp - 0x34) == 0x22)
					{
						*(fp - 0x30) = ebx_291 + 0x01;
						*ebx_291 = 0x27;
						*(fp - 0x38) = 0x01;
						eax_161 = 0x00;
						al_157 = 0x00;
						goto l00401AC7;
					}
l00401B2D:
					*(fp - 0x30) = (byte **) ebx_291;
					esi_163 = esi_163 + 0x00;
					bl_156 = (byte) (word32) *(esi_163 - 0x01);
					*(fp - 0x34) = *(fp - 0x34) ^ ecx_112;
					*(fp - 0x38) = 0x01;
					eax_161 = 0x00;
					al_157 = 0x00;
					ecx_112 = (int32) bl_156;
					if (ecx_112 != 0x00)
						goto l00401AD5;
					goto l00401B50;
				}
				goto l00401C35;
			}
			if (bl_156 != 0x2A)
			{
				if (bl_156 == 0x22)
				{
					int32 ebx_312 = eax_161 >> 0x01;
					if (ebx_312 != 0x00)
					{
						byte * edx_336 = *(fp - 0x30);
						ebx_291 = edx_336 + ebx_312;
						do
						{
							edx_336 = edx_336 + 0x01;
							*(edx_336 - 0x01) = 0x5C;
						} while (edx_336 != ebx_291);
					}
					else
						ebx_291 = (byte *) *(fp - 0x30);
					if ((al_157 & 0x01) != 0x00 || *(fp - 0x34) == 0x27)
					{
						*(fp - 0x30) = ebx_291 + 0x01;
						*ebx_291 = 0x22;
						*(fp - 0x38) = 0x01;
						eax_161 = 0x00;
						al_157 = 0x00;
						goto l00401AC7;
					}
					goto l00401B2D;
				}
				goto l00401C35;
			}
		}
		else
		{
			if (bl_156 == 0x5C)
			{
				eax_161 = eax_161 + 0x01;
				al_157 = (byte) eax_161;
				goto l00401AC7;
			}
			if (bl_156 != 0x7F)
			{
				if (bl_156 != 0x5B)
				{
l00401C35:
					ci8 * edx_223 = *(fp - 0x30);
					ci8 * edi_225 = *(fp - 0x30) + eax_161;
					if (eax_161 != 0x00)
					{
						do
						{
							edx_223 = edx_223 + 0x01;
							*(edx_223 - 0x01) = 0x5C;
						} while (edx_223 != edi_225);
					}
					else
						edi_225 = (ci8 *) *(fp - 0x30);
					if (*(fp - 0x34) == 0x00)
					{
						esp_52->dw0000 = ecx_112;
						if (isspace(esp_52->dw0000) != 0x00)
						{
							if (*(fp - 0x38) == 0x00 && *(fp - 0x40) >= edi_225)
							{
								*(fp - 0x30) = (ci8 **) edi_225;
								eax_161 = 0x00;
								al_157 = 0x00;
							}
							else
							{
								*edi_225 = 0x00;
								esp_52->ptr000C = fp - 44;
								esp_52->dw0008 = 0x00;
								esp_52->dw0004 = *(fp - 0x3C);
								int32 edi_261 = *(fp - 0x40);
								esp_52->dw0000 = edi_261;
								fn004031C0(dwArg00, dwArg04, dwArg08, dwArg0C);
								*(fp - 0x3C) = *(fp - 0x3C) | 0x01;
								*(fp - 0x30) = edi_261;
								*(fp - 0x38) = 0x00;
								eax_161 = 0x00;
								al_157 = 0x00;
							}
							goto l00401AC7;
						}
					}
					*(fp - 0x30) = edi_225 + 0x01;
					*edi_225 = bl_156;
					eax_161 = 0x00;
					al_157 = 0x00;
					goto l00401AC7;
				}
				edi_171 = 0x01;
				if ((globals->b409000 & 0x20) == 0x00)
				{
l00401BFB:
					ci8 * eax_177;
					if (eax_161 != 0x00)
					{
						ci8 * edx_200 = *(fp - 0x30);
						eax_177 = edx_200 + eax_161;
						do
						{
							edx_200 = edx_200 + 0x01;
							*(edx_200 - 0x01) = 0x5C;
						} while (edx_200 != eax_177);
					}
					else
						eax_177 = (ci8 *) *(fp - 0x30);
					if ((byte) edi_171 != 0x00 || ecx_112 == 0x7F)
					{
						*eax_177 = 0x7F;
						eax_177 = eax_177 + 0x01;
					}
					*eax_177 = bl_156;
					*(fp - 0x30) = eax_177 + 0x01;
					eax_161 = 0x00;
					al_157 = 0x00;
					goto l00401AC7;
				}
			}
		}
	}
	word32 edx_214 = *(fp - 0x34);
	edi_171 = DPB(edx_214, edx_214 != 0x00, 0);
	goto l00401BFB;
}

void fn00401D60(word32 ecx, word32 ebx)
{
	byte dh_10 = SLICE(SCZDOP, byte, 8);
	if (((SCZDOP ^ 0x00200000 ^ SCZDOP) & 0x00200000) != 0x00)
	{
		word32 eax_49;
		word32 ebx_50;
		word32 ecx_51;
		word32 edx_52;
		__cpuid(0x00, ecx, &eax_49, &ebx_50, &ecx_51, &edx_52);
		if (eax_49 != 0x00)
		{
			word32 eax_70;
			word32 ebx_71;
			word32 ecx_72;
			ui32 edx_73;
			__cpuid(0x01, ecx_51, &eax_70, &ebx_71, &ecx_72, &edx_73);
			if ((dh_10 & 0x01) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x01;
			if ((dh_10 & 0x80) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x02;
			if ((edx_73 & 0x00800000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x04;
			if ((edx_73 & 0x01000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x08;
			if ((edx_73 & 0x02000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x10;
			if ((edx_73 & 0x04000000) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x20;
			if ((cl & 0x01) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x40;
			word32 ecx_99 = DPB(ecx_72, ch & 0x20, 8);
			if ((ch & 0x20) != 0x00)
				globals->dw40D024 = globals->dw40D024 | 0x80;
			uint32 eax_106;
			word32 ebx_107;
			word32 ecx_108;
			word32 edx_109;
			__cpuid(0x80000000, ecx_99, &eax_106, &ebx_107, &ecx_108, &edx_109);
			if (eax_106 > 0x80000000)
			{
				word32 eax_113;
				word32 ebx_114;
				word32 ecx_115;
				int32 edx_116;
				__cpuid(0x80000001, ecx_108, &eax_113, &ebx_114, &ecx_115, &edx_116);
				if (edx_116 < 0x00)
					globals->dw40D024 = globals->dw40D024 | 0x0100;
				if ((edx_116 & 0x40000000) != 0x00)
					globals->dw40D024 = globals->dw40D024 | 0x0200;
			}
		}
	}
	return;
}

void fn00401E40()
{
fn00401E40_entry:
l00401E40:
fn00401E40_exit:
}

word32 fn00401E80(word32 esi)
{
	word32 * esp_24 = fp - 0x1C;
	ui32 ebx_14 = globals->dw4087D0;
	if (ebx_14 == ~0x00)
	{
		ebx_14 = 0x00;
		while (true)
		{
			ui32 eax_48 = ebx_14 + 0x01;
			if ((&globals->dw4087D0)[eax_48] == 0x00)
				break;
			ebx_14 = eax_48;
		}
	}
	if (ebx_14 != 0x00)
	{
		do
		{
			word32 ebx_32;
			byte SCZO_33;
			byte Z_34;
			byte SZO_35;
			byte C_36;
			word32 esi_37;
			word32 eax_38;
			word32 edx_39;
			(&globals->dw4087D0)[ebx_14]();
		} while (ebx_32 != 0x01);
	}
	*esp_24 = 4202064;
	return fn004012E0();
}

word32 fn00401ED0(word32 esi)
{
	if (globals->dw40D028 == 0x00)
	{
		globals->dw40D028 = 0x01;
		return fn00401E80(esi);
	}
	else
		return eax;
}

Eq_43 fn00402220(Eq_43 ecx, Eq_43 edx, word32 dwArg04, ptr32 & edxOut, Eq_1491 & bplOut, ptr32 & esiOut, ptr32 & ediOut)
{
	word32 esp_17;
	word32 esi_18;
	word32 ebx_19;
	byte SCZO_20;
	word32 eax_21;
	word32 ebp_22;
	word32 edi_23;
	word32 ecx_24;
	word32 edx_25;
	byte SZO_26;
	byte C_27;
	byte Z_28;
	byte bpl_29;
	msvcrt.dll!fwrite();
	word32 esp_35;
	word32 esi_36;
	word32 ebx_37;
	byte SCZO_38;
	Eq_43 eax_39;
	word32 ebp_40;
	word32 edi_41;
	Eq_43 ecx_42;
	Eq_43 edx_43;
	byte SZO_44;
	byte C_45;
	byte Z_46;
	byte bpl_47;
	msvcrt.dll!vfprintf();
	abort();
	byte bpl_52;
	*bplOut = (byte) (fp - 0x20);
	word32 edi_55;
	*ediOut = ecx_42;
	word32 esi_58;
	*esiOut = edx_43;
	if (VirtualQuery(eax_39, fp - 0x54, 0x1C) == 0x00)
	{
		word32 edx_90;
		word32 ebx_91;
		byte bpl_92;
		return fn0040233B(ecx_42, edx_43, eax_39, out edx_90, out ebx_91, out bpl_92);
	}
	else
	{
		word32 edx_84;
		word32 ebx_85;
		word32 ebp_86;
		word32 esi_87;
		word32 edi_88;
		return fn004022A1(eax_39, fp - 0x20, edx_43, ecx_42, out edx_84, out ebx_85, out ebp_86, out esi_87, out edi_88);
	}
}

Eq_43 fn00402270(Eq_43 eax, Eq_43 ecx, Eq_43 edx, ptr32 & edxOut, Eq_1588 * & ebxOut, Eq_1589 & bplOut)
{
	byte bpl_6;
	*bplOut = (byte) (fp - 0x04);
	if (VirtualQuery(eax, fp - 0x38, 0x1C) == 0x00)
	{
		word32 edx_55;
		word32 ebx_56;
		byte bpl_57;
		return fn0040233B(ecx, edx, eax, out edx_55, out ebx_56, out bpl_57);
	}
	else
	{
		word32 edx_43;
		Eq_43 ebx_44;
		word32 * ebp_45;
		Eq_43 esi_46;
		Eq_43 edi_47;
		return fn004022A1(eax, fp - 0x04, edx, ecx, out edx_43, out ebx_44, out ebp_45, out esi_46, out edi_47);
	}
}

word32 fn004022A1(Eq_43 ebx, word32 * ebp, Eq_43 esi, Eq_43 edi, ptr32 & edxOut, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut, ptr32 & ediOut)
{
	*edxOut = edx;
	word32 eax_4 = *(ebp - 0x20);
	if (eax_4 == 0x04 || eax_4 == 0x40)
	{
		v3->t0008 = edi;
		v3->t0004 = esi;
		v3->t0000 = ebx;
		memcpy(v3->t0000, v3->t0004, v3->t0008);
	}
	else
	{
		Eq_43 eax_49 = *(ebp - 0x28);
		v3->t000C = ebp - 0x38;
		v3->t0008.u0 = 0x40;
		*(ebp - 0x3C) = ebp - 0x38;
		v3->t0004 = eax_49;
		v3->t0000 = *(ebp - 0x34);
		VirtualProtect(v3->t0000, v3->t0004, v3->t0008, v3->t000C);
		*(ebp - 0x40) = *(ebp - 0x20);
		v3->t0008 = edi;
		v3->t0004 = esi;
		v3->t0000 = ebx;
		memcpy(v3->t0000, v3->t0004, v3->t0008);
		word32 edx_50;
		*edxOut = ebp - 0x38;
		ecx = *(ebp - 0x40);
		if (ecx != 0x04 && ecx != 0x40)
		{
			Eq_1707 edx_72 = *(ebp - 0x3C);
			*edxOut = edx_72;
			v3->t0008 = *(ebp - 0x38);
			Eq_43 eax_74 = *(ebp - 0x28);
			v3->t000C = edx_72;
			v3->t0004 = eax_74;
			v3->t0000 = *(ebp - 0x34);
			VirtualProtect(v3->t0000, v3->t0004, v3->t0008, v3->t000C);
			word32 ebx_84;
			*ebxOut = *(ebp - 0x0C);
			word32 esi_86;
			*esiOut = *(ebp - 0x08);
			word32 edi_88;
			*ediOut = *(ebp - 0x04);
			word32 ebp_90;
			*ebpOut = *ebp;
			return ecx;
		}
	}
	word32 ebx_28;
	*ebxOut = *(ebp - 0x0C);
	word32 esi_30;
	*esiOut = *(ebp - 0x08);
	word32 edi_32;
	*ediOut = *(ebp - 0x04);
	word32 ebp_34;
	*ebpOut = *ebp;
	return ecx;
}

Eq_43 fn0040233B(Eq_43 ecx, Eq_43 edx, Eq_43 ebx, ptr32 & edxOut, ptr32 & ebxOut, Eq_1556 & bplOut)
{
	*ebxOut = ebx;
	v3->t0008 = ebx;
	v3->dw0004 = 0x1C;
	v3->dw0000 = 0x0040A174;
	Eq_43 edx_9;
	byte bpl_10;
	word32 esi_11;
	word32 edi_12;
	Eq_43 ecx_13 = fn00402220(ecx, edx, dwArg00, out edx_9, out bpl_10, out esi_11, out edi_12);
	word32 edx_16;
	byte bpl_17;
	return fn00402360(ecx_13, edx_9, esi_11, edi_12, out edx_16, out bpl_17);
}

Eq_43 fn00402360(Eq_43 ecx, Eq_43 edx, word32 esi, word32 edi, ptr32 & edxOut, Eq_91 & bplOut)
{
	*edxOut = edx;
	*bplOut = bpl;
	if (globals->dw40D05C != 0x00)
		return ecx;
	globals->dw40D05C = 0x01;
	if (true)
		return ecx;
	struct Eq_1911 * ebx_106;
	if (false)
	{
		if ((word32 *) 0x0040A868 != 0x00 || (word32 *) 4237420 != 0x00)
		{
l00402430:
			ebx_106 = (struct Eq_1911 *) 0x0040A868;
			goto l00402435;
		}
		ecx = (union Eq_43 *) 4237424;
		ebx_106 = (struct Eq_1911 *) 0x0040A874;
		if (ecx != 0x00)
		{
			ebx_106 = (struct Eq_1911 *) 0x0040A868;
			goto l004023CC;
		}
	}
	else
		ebx_106 = (struct Eq_1911 *) 0x0040A868;
	edx = ebx_106->dw0000;
	*edxOut = edx;
	if (edx == 0x00)
	{
		if (ebx_106->dw0004 == 0x00)
		{
l004023CC:
			word32 eax_133 = ebx_106->dw0008;
			if (eax_133 != 0x01)
			{
				word32 edx_241;
				byte bpl_242;
				word32 esi_243;
				word32 edi_244;
				Eq_43 ecx_245 = fn00402220(ecx, edx, 0x0040A1A8, out edx_241, out bpl_242, out esi_243, out edi_244);
				word32 esp_246;
				word32 eax_247;
				byte SZO_248;
				byte C_249;
				byte Z_250;
				byte SCZO_251;
				word32 edi_252;
				word32 esi_253;
				word32 ebx_254;
				word32 ecx_255;
				word32 edx_256;
				byte dl_257;
				byte S_258;
				word16 si_259;
				byte bpl_260;
				_register_frame_info();
				return ecx_255;
			}
			else
			{
				while (true)
				{
					struct Eq_1964 * ebx_148 = ebx_106 + 0x01;
					if (ebx_148 >= (struct Eq_1964 *) 0x0040A868)
						return ecx;
					Eq_43 ecx_155 = ebx_148->t0000;
					Eq_43 edx_151 = (word32) ebx_148->b0008;
					struct Eq_1978 * esi_153 = ebx_148->ptr0004;
					Eq_1982 edi_159 = *ecx_155;
					if (edx_151 == 0x10)
					{
						ci16 si_214 = (word16) (word32) esi_153->w400000;
						ui32 edx_218 = (word32) si_214;
						if (si_214 < 0x00)
							edx_218 = edx_218 | 0xFFFF0000;
						*(fp - 0x10) = (word32) edi_159;
						word32 edx_231;
						byte bpl_233;
						ecx = fn00402270(&esi_153->w400000, 0x02, fp - 0x10, out edx_231, out ebx_106, out bpl_233);
						continue;
					}
					if (edx_151 != 0x20)
						break;
					*(fp - 0x10) = (union Eq_2006 *) (edi_159 - ecx_155);
					word32 edx_209;
					byte bpl_211;
					ecx = fn00402270(&esi_153->w400000, 0x04, fp - 0x10, out edx_209, out ebx_106, out bpl_211);
				}
				if (edx_151 == 0x08)
				{
					ci8 dl_174 = (byte) (word32) esi_153->w400000;
					ui32 esi_178 = (word32) dl_174;
					if (dl_174 < 0x00)
						esi_178 = esi_178 | ~0xFF;
					*(fp - 0x10) = (word32) edi_159;
					word32 edx_193;
					byte bpl_195;
					ecx = fn00402270(&esi_153->w400000, 0x01, fp - 0x10, out edx_193, out ebx_106, out bpl_195);
					continue;
				}
				else
				{
					*(fp - 0x28) = (union Eq_43 *) edx_151;
					*(fp - 44) = 0x0040A1DC;
					*(fp - 0x10) = 0x00;
					word32 edx_168;
					byte bpl_169;
					word32 esi_170;
					word32 edi_171;
					ecx = fn00402220(ecx_155, edx_151, dwArg00, out edx_168, out bpl_169, out esi_170, out edi_171);
					goto l00402430;
				}
			}
		}
	}
l00402435:
	if (ebx_106 < (struct Eq_1911 *) 0x0040A868)
	{
		do
		{
			struct Eq_2099 * edx_95 = ebx_106->dw0004;
			*(fp - 0x10) = edx_95->dw400000 + ebx_106->dw0000;
			word32 edx_105;
			byte bpl_107;
			ecx = fn00402270(&edx_95->dw400000, 0x04, fp - 0x10, out edx_105, out ebx_106, out bpl_107);
		} while (ebx_106 < (struct Eq_1911 *) 0x0040A868);
	}
	return ecx;
}

void fn00402550(uint32 eax)
{
	struct Eq_2151 * ecx_10 = fp + 0x04;
	if (eax >= 0x1000)
	{
		do
		{
			ecx_10 = ecx_10 - 0x1000;
			ecx_10->dw0000 = ecx_10->dw0000;
			eax = eax - 0x1000;
		} while (eax > 0x1000);
	}
	word32 * ecx_16 = ecx_10 - eax;
	*ecx_16 = *ecx_16;
	return;
}

void fn00402580(word32 dwArg04, ptr32 dwArg08)
{
	word32 ebx_15;
	word32 ebp_16;
	word32 esi_17;
	fn00405110(0x3000, iob + 0x20, 0x00, dwArg04, dwArg08, out ebx_15, out ebp_16, out esi_17);
	return;
}

Eq_43 fn004025C0(Eq_43 eax, word32 edx, ptr32 dwArg00, word32 dwArg04, word32 dwArg08)
{
	struct Eq_2209 * ebx_15 = eax;
	if (eax == 0x00)
		return 0x00;
	int32 ecx_62 = (int32) *eax;
	Eq_43 eax_129 = 0x00;
	struct Eq_2209 * edx_148 = eax;
	if (ecx_62 == 0x00)
		return 0x00;
l004025E0:
	if (true && ecx_62 == 0x7F)
	{
		edx_148 = ebx_15 + 0x01;
		if (ebx_15->b0000 == 0x00)
			return 0x00;
	}
	if (eax_129 == 0x00)
	{
		if (ecx_62 != 0x3F && ecx_62 != 0x2A)
		{
			eax_129 = (word32) (ecx_62 == 0x5B);
			goto l00402603;
		}
	}
	else if (ecx_62 != 0x5D || eax_129 <= 0x01)
	{
		eax_129 = eax_129;
l00402603:
		ebx_15 = edx_148;
		ecx_62 = (int32) edx_148->b0000;
		edx_148 = edx_148->b0000 + 0x01;
		if (ecx_62 != 0x00)
			goto l004025E0;
		return 0x00;
	}
	return eax_129;
	return 0x01;
}

Eq_2263 * fn00402650(Eq_2263 * eax, ui32 ecx, int32 edx, byte * esi)
{
fn00402650_entry:
	byte cl_116
	word32 ebx_17 = (word32) eax->b0000
	int32 edi_192 = (int32) (byte) ebx_17
	branch edi_192 == 0x5D l00402740
	goto l00402669
l00402650:
l00402669:
	cl_116 = (byte) ebx_17
	branch edi_192 != 0x2D l0040269E
	goto l00402740
l00402675:
	branch ebx_100 == 0x00 l00402730
l0040267D:
	branch ebx_100 == 0x5C l00402730
	branch ebx_100 == 0x5C l00402730
l00402686:
	branch ebx_100 == 0x2F l00402730
	branch ebx_100 == 0x2F l00402730
l0040268F:
	branch ebx_100 == edx l00402768
	edi_192 = ebx_100
	cl_116 = (byte) (word32) esi_104->b0000
	eax = esi_104
	branch ebx_100 == edx l00402768
l0040269E:
	branch (int32) cl_116 == 0x5D l00402730
	branch (int32) cl_116 == 0x5D l00402730
	int32 ebx_100 = (int32) cl_116
	struct Eq_2263 * esi_104 = eax + 0x01
	branch ebx_100 == 0x5D l00402730
l004026AD:
	branch ebx_100 != 0x2D l00402675
	branch ebx_100 != 0x2D l00402675
	branch ebx_100 != 0x2D l00402675
l004026B2:
	branch (byte) (word32) eax[0x01] == 0x5D l00402754
	branch (byte) (word32) eax[0x01] == 0x5D l00402754
	byte bl_208 = (byte) (word32) eax[0x01]
	branch bl_208 == 0x5D l00402754
l004026BF:
	int32 ebp_211 = (int32) bl_208
	byte bl_215 = (byte) ebp_211
	branch ebp_211 == 0x00 l00402730
	int32 ebp_216 = (int32) bl_215
	byte bl_220 = (byte) ebp_216
	branch ebp_216 == 0x00 l00402730
	int32 ebp_221 = (int32) bl_220
	ebx_100 = ebp_221
	branch ebp_221 == 0x00 l00402730
l004026C8:
	int32 eax_255
	branch edi_192 >= ebp_221 l00402858
	branch edi_192 >= ebp_221 l00402858
	esi_104 = eax + 0x02
	branch edi_192 >= ebp_221 l00402858
l004026D3:
	branch edi_192 != edx l004026EE
	branch edi_192 != edx l004026EE
	eax_255 = edi_192 + 0x01
	branch edi_192 != edx l004026EE
	goto l004027A0
l004026E0:
	eax_255 = eax_255 + 0x01
	branch edx == eax_255 - 0x01 l004027A0
l004026EE:
	branch ebp_221 > eax_255 l004026E0
	branch ebp_221 > eax_255 l004026E0
l004026F2:
	branch ebp_221 >= eax_255 l0040267D
	branch ebp_221 >= eax_255 l0040267D
l004026F6:
	branch edx == eax_255 l0040270F
	branch edx == eax_255 l0040270F
l00402700:
	branch eax_255 == ebp_221 + 0x02 l0040267D
l00402708:
	eax_255 = eax_255 - 0x01
	branch edx != eax_255 l00402700
l0040270F:
l00402715:
	byte al_281 = (byte) (word32) esi_104->b0000
	branch al_281 == 0x5D l004027C3
l00402720:
	branch al_281 == 0x7F l004027E5
l00402728:
	esi_104 = esi_104 + 0x01
	branch al_281 != 0x00 l00402715
l00402730:
	return null
l00402740:
	branch edi_192 == edx l00402800
l00402748:
	cl_116 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l0040269E
l00402754:
	edi_192 = 0x2D
	eax = esi_104
	cl_116 = 0x5D
	branch 0x2D != edx l0040269E
l00402768:
	goto l0040277A
l00402770:
	eax = eax + 0x01
	branch cl_116 == 0x00 l00402730
l00402777:
	cl_116 = (byte) (word32) eax->b0000
l0040277A:
	branch cl_116 == 0x5D l00402845
l00402783:
	branch cl_116 != 0x7F l00402770
l00402788:
	branch (ecx & 0x20) != 0x00 l00402850
l00402790:
	cl_116 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l00402770
l004027A0:
l004027A6:
	byte al_338 = (byte) (word32) esi_104->b0000
	branch al_338 == 0x5D l004027C3
l004027AD:
	branch al_338 == 0x7F l004027D0
l004027B1:
	esi_104 = esi_104 + 0x01
	branch al_338 == 0x00 l00402730
l004027BC:
	al_338 = (byte) (word32) esi_104->b0000
	branch al_338 != 0x5D l004027AD
l004027C3:
	return esi_104 + 0x01
l004027D0:
	branch (ecx & 0x20) != 0x00 l004027E0
l004027D4:
	al_338 = (byte) (word32) esi_104[0x01]
	esi_104 = esi_104 + 0x01
	goto l004027B1
l004027E0:
	esi_104 = esi_104 + 0x01
	goto l004027A6
l004027E5:
	branch (ecx & 0x20) != 0x00 l004027F5
l004027E9:
	al_281 = (byte) (word32) esi_104[0x01]
	esi_104 = esi_104 + 0x01
	goto l00402728
l004027F5:
	esi_104 = esi_104 + 0x01
	goto l00402715
l00402800:
	eax = eax + 0x01
l00402810:
	byte dl_419 = (byte) (word32) eax->b0000
	branch dl_419 == 0x5D l00402845
l00402818:
	branch dl_419 == 0x7F l00402830
l0040281D:
	eax = eax + 0x01
	branch dl_419 != 0x00 l00402810
	goto l00402730
l00402830:
	branch (ecx & 0x20) != 0x00 l00402840
l00402834:
	dl_419 = (byte) (word32) eax[0x01]
	eax = eax + 0x01
	goto l0040281D
l00402840:
	eax = eax + 0x01
	goto l00402810
l00402845:
	return eax + 0x01
l00402850:
	eax = eax + 0x01
	goto l00402777
l00402858:
	eax_255 = edi_192
	goto l004026F2
fn00402650_exit:
}

Eq_2516 * fn00402860(Eq_2516 * eax)
{
	struct Eq_2516 * eax_28;
	if (eax != null)
	{
		int32 eax_54 = eax->dw000C;
		Eq_43 ebp_56 = (eax_54 + 0x01) * 0x04;
		Eq_43 eax_58 = malloc(ebp_56);
		eax->t0008 = eax_58;
		Eq_43 ebx_59 = eax_58;
		eax_28 = (struct Eq_2516 *) 0x03;
		if (eax_58 == 0x00)
			return eax_28;
		eax->dw0004 = 0x00;
		ui32 edx_67 = eax_54 + 0x01;
		if (eax_54 > 0x01)
		{
			Eq_2550 ecx_69 = ebp_56 - 0x04;
			while (true)
			{
				Mem73[ebx_59 + ecx_69:word32] = 0x00;
				ecx_69 = ecx_69 - 0x04;
				edx_67 = edx_67 - 0x01;
				if (edx_67 == 0x00)
					break;
				ebx_59 = eax->t0008;
			}
		}
	}
	eax_28 = null;
	return eax_28;
}

Eq_2263 * fn004028C0(Eq_2263 * eax, ui32 ecx, byte * edx)
{
	byte cl_120;
	struct Eq_2263 * eax_151;
	struct Eq_2263 * edi_116 = eax;
	if (*edx != 0x2E)
		cl_120 = (byte) (word32) eax->b0000;
	else
	{
		int32 eax_376 = (int32) eax->b0000;
		if ((byte) eax_376 != 0x2E)
		{
			cl_120 = (byte) eax_376;
			eax_151 = eax_376 - 0x2E;
			if ((ecx & 0x00010000) == 0x00)
				return eax_151;
		}
		else
			cl_120 = 0x2E;
	}
	ptr32 ebp_121 = edx[0x01];
l004028F4:
	int32 edx_131 = (int32) cl_120;
	byte * esi_222 = ebp_121 - 0x01;
	struct Eq_2263 * eax_100 = edi_116[0x01];
	if (edx_131 != 0x00)
	{
		if (cl_120 == 0x3F)
		{
			if (*(ebp_121 - 0x01) == 0x00)
			{
				eax_151 = (struct Eq_2263 *) 0x3F;
				return eax_151;
			}
			edi_116 = eax_100;
			goto l004029E7;
		}
		if (cl_120 != 0x5B)
		{
			if (cl_120 == 0x2A)
			{
				byte dl_202 = (byte) (word32) edi_116[0x01];
				struct Eq_2263 * ebx_203 = eax_100;
				if (dl_202 == 0x2A)
				{
					do
					{
						ebx_203 = (struct Eq_2263 *) ebx_203[0x01];
						dl_202 = (byte) (word32) ebx_203->b0000;
					} while (dl_202 == 0x2A);
				}
				eax_151 = null;
				if (dl_202 == 0x00)
					return eax_151;
l004029A9:
				eax_151 = fn004028C0(ebx_203, ecx | 0x00010000, esi_222);
				if (eax_151 != null)
				{
					esi_222 = (byte *) esi_222[0x01];
					if (*(esi_222 - 0x01) != 0x00)
						goto l004029A9;
					return eax_151;
				}
				else
				{
					return null;
					return null;
				}
			}
			if ((ecx & 0x20) == 0x00 && edx_131 == 0x7F)
			{
				edx_131 = (int32) edi_116[0x01];
				edi_116 = (struct Eq_2263 *) edi_116[0x02];
				if (edx_131 != 0x00)
				{
l0040292A:
					int32 ebx_135 = (int32) *(ebp_121 - 0x01);
					if ((byte) ebx_135 == 0x00)
					{
						ebx_135 = 0x00;
						goto l00402966;
					}
					int32 esi_165;
					if ((ecx & 0x4000) == 0x00)
						esi_165 = tolower(edx_131) - tolower(ebx_135);
					else
						esi_165 = edx_131 - ebx_135;
					if (esi_165 != 0x00)
					{
l00402966:
						eax_151 = edx_131 - ebx_135;
						return eax_151;
					}
l004029E7:
					cl_120 = (byte) (word32) edi_116->b0000;
					ebp_121 = ebp_121 + 0x02;
					goto l004028F4;
				}
			}
			edi_116 = eax_100;
			goto l0040292A;
		}
		int32 edx_271 = (int32) *(ebp_121 - 0x01);
		if (edx_271 == 0x00)
		{
			eax_151 = (struct Eq_2263 *) 0x5B;
			return eax_151;
		}
		if (edi_116[0x01] != 33)
		{
			struct Eq_2263 * eax_291 = fn00402650(eax_100, ecx, edx_271, esi_222);
			edi_116 = eax_291;
			if (eax_291 == null)
			{
l00402ABE:
				eax_151 = (struct Eq_2263 *) 0x5D;
				return eax_151;
			}
			goto l004029E7;
		}
		struct Eq_2263 * ebx_297 = edi_116[0x02];
		if (fn00402650(ebx_297, ecx, edx_271, esi_222) != null)
		{
			edi_116 = ebx_297;
			goto l004029E7;
		}
		byte al_306 = (byte) (word32) edi_116[0x02];
		if (al_306 == 0x5D)
		{
			ebx_297 = (struct Eq_2263 *) edi_116[0x03];
			al_306 = (byte) (word32) edi_116[0x03];
		}
		if (al_306 == 0x5D)
		{
			edi_116 = (struct Eq_2263 *) ebx_297[0x01];
			goto l004029E7;
		}
		if (al_306 == 0x7F)
		{
			if ((ecx & 0x20) != 0x00)
			{
				ebx_297 = (struct Eq_2263 *) ebx_297[0x01];
l00402A97:
				al_306 = (byte) (word32) ebx_297->b0000;
				goto l00402A9A;
			}
			al_306 = (byte) (word32) ebx_297[0x01];
			ebx_297 = (struct Eq_2263 *) ebx_297[0x01];
		}
		ebx_297 = (struct Eq_2263 *) ebx_297[0x01];
		if (al_306 == 0x00)
			goto l00402ABE;
		goto l00402A97;
	}
	eax_151 = -(int32) *esi_222;
	return eax_151;
}

Eq_43 fn00402B40(Eq_43 eax, Eq_2516 * edx, ptr32 & ecxOut)
{
	*ecxOut = ecx;
	Eq_43 eax_23 = realloc(edx->t0008, (edx->dw0004 + edx->dw000C) * 0x04 + 0x08);
	if (eax_23 == 0x00)
		return 0x01;
	else
	{
		ui32 edi_39 = edx->dw0004;
		edx->t0008 = eax_23;
		int32 eax_41 = edx->dw000C;
		edx->dw0004 = edi_39 + 0x01;
		*eax_23 = eax;
		edx->t0008->u0 = 0x00;
		word32 ecx_42;
		*ecxOut = edi_39 + 0x01;
		return 0x00;
	}
}

void fn00402BB0(Eq_43 eax, Eq_2516 * edx)
{
	if (eax != 0x00 && edx != null)
	{
		word32 ecx_20;
		fn00402B40(eax, edx, out ecx_20);
		return;
	}
	else
		return;
}

void fn00402BD0(Eq_43 eax, Eq_2516 * edx)
{
	Eq_43 eax_14 = *eax;
	if (eax_14 != 0x00)
		fn00402BD0(eax_14, edx);
	fn00402BB0(*eax, edx);
	Eq_43 eax_20 = *eax;
	if (eax_20 != 0x00)
		fn00402BD0(eax_20, edx);
	free(eax);
	return;
}

Eq_43 fn00402C10(Eq_43 eax, word16 dx, ptr32 ebp)
{
fn00402C10_entry:
	Eq_43 eax_23 = strlen(eax)
	word32 eax_26 = eax_23 + 0x10 & ~0x0F
	fn00402550(eax_26)
	struct Eq_2910 * esp_29 = fp - 0x7C - eax_26
	Mem32[esp_29 + 0x08:word32] = eax_23 + 0x01
	esp_29->t0004 = eax
	esp_29->t0000 = &esp_29->t0008
	Eq_43 eax_35 = memcpy(esp_29->t0000, esp_29->t0004, esp_29->t0008)
	esp_29->t0000 = eax_35
	Eq_43 eax_38 = fn004032C0(eax_35, dwArg00)
	struct Eq_2950 * ebp_126 = fp - 0x04
	Eq_43 ebx_16 = eax
	Eq_43 eax_102 = fn00402860(fp - 44)
	branch eax_102 == 0x00 l00402C73
	goto l00402C6B
l00402C10:
l00402C6B:
	return eax_102
l00402C73:
	branch fn004025C0(eax_38, edx, ebp, dwArg00, dwArg04) == 0x00 l00402EE0
l00402C86:
	esp_29->t0000 = fp - 44
	eax_102 = fn00402C10(eax_38, DPB(dx, SLICE(edx, byte, 8) | 0x80, 8), fp - 0x04)
l00402C9D:
	struct Eq_2910 * esp_107 = esp_29
	branch eax_102 != 0x00 l00402C6B
l00402CA1:
	Eq_43 eax_121
	byte al_112 = (byte) (word32) *eax
	branch al_112 == 0x5C l00403008
l00402CAD:
	bool Z_835 = cond(al_112 - 0x2F)
	branch al_112 == 0x2F l00403008
l00402CB5:
	byte * esi_837 = *(fp - 0x4C)
	byte * edi_838 = &globals->b40A208
	word32 ecx_839 = 0x02
l00402CC2:
	branch ecx_839 == 0x00 l00402CC4
l00402CC2_1:
	Z_835 = cond(*esi_971 - *edi_972)
	esi_837 = esi_971 + 0x01
	edi_838 = edi_972 + 0x01
	ecx_839 = ecx_839 - 0x01
	byte * esi_971 = esi_837
	byte * edi_972 = edi_838
	branch *esi_971 != *edi_972 l00402CC2
l00402CC4:
	branch Z_835 l00403008
l00402CCA:
	*(fp - 0x61) = 0x5C
l00402CCE:
	*(fp - 0x44) = (union Eq_43 *) ebx_16
	*(fp - 0x4C) = 0x00
	branch (*(fp - 0x38) & 0x10) != 0x00 && fn004025C0(ebx_16, *(fp - 0x38), ebp, dwArg00, dwArg04) == 0x00 l00403115
l00402CE2:
	union Eq_43 * eax_150 = *(fp - 0x24)
	*(fp - 0x3C) = (union Eq_43 **) eax_150
	Eq_43 eax_152 = *eax_150
	branch eax_152 == 0x00 l00403163
l00402CF2:
	ui32 ecx_157 = *(fp - 0x38)
	*(fp - 0x40) = 0x02
	*(fp - 0x6C) = ecx_157 & 0x04
	*(fp - 0x34) = ecx_157 & 0x8000
l00402D10:
	branch *(ebp_126 - 0x3C) == 0x01 l00402F72
l00402D1A:
	esp_107->t0000 = eax_152
	word32 eax_208 = fn00403830(dwArg00)
	*(ebp_126 - 44) = eax_208
	branch eax_208 == 0x00 l004030A3
l00402D2D:
	branch *(ebp_126 - 0x48) == 0x00 l004030F5
l00402D38:
	esp_107->t0000 = **(ebp_126 - 0x38)
	*(ebp_126 - 0x4C) = (union Eq_43 *) strlen(esp_107->t0000)
l00402D48:
	ui32 eax_217 = *(ebp_126 - 0x34)
	*(ebp_126 - 0x44) = 0x00
	*(ebp_126 - 88) = eax_217 & 0x40
l00402D58:
	esp_107->t0000 = *(ebp_126 - 44)
	struct Eq_3268 * eax_238 = fn004039D0(dwArg00, out ebp_126)
	branch eax_238 == null l00402F55
l00402D6D:
	branch (*(ebp_126 - 0x30) == 0x00 || eax_238->dw0008 == 0x10) && fn004028C0(*(ebp_126 - 0x40), *(ebp_126 - 0x34), eax_238->dw0008 + 0x01) == null l00402D7A
	goto l00402D58
l00402D74:
l00402D7A:
l00402D8E:
	word32 edx_256 = (word32) eax_238->w0006
	word32 ecx_260 = *(ebp_126 - 0x4C)
	*(ebp_126 - 0x50) = (struct Eq_2910 **) esp_107
	ui32 eax_262 = ecx_260 + 0x11 + edx_256
	fn00402550(eax_262 & ~0x0F)
	struct Eq_3319 * esp_266 = esp_107 - (eax_262 & ~0x0F)
	*(ebp_126 - 0x54) = &esp_266->t0008
	word32 eax_267 = 0x00
	branch ecx_260 != 0x00 l00402FA4
l00402DB7:
	esp_266->t0008 = edx_256 + 0x01
	esp_266->t0004 = eax_238->dw0008[0x01]
	esp_266->t0000 = (&esp_266->t0008)[eax_267 / 0x0C]
	memcpy(esp_266->t0000, esp_266->t0004, esp_266->t0008)
	esp_266->t0000 = esp_266->t0008
	word32 eax_288 = strlen(esp_266->t0000) + 0x10 & ~0x0F
	fn00402550(eax_288)
	union Eq_43 * esp_292 = esp_266 - eax_288
	struct Eq_3432 * esi_291 = *(ebp_126 - 0x54)
	ptr32 edx_296 = esp_292
	goto l00402DFD
l00402DF0:
	edx_296 = edx_296 + 0x01
	*(edx_296 - 0x01) = al_312
	esi_291 = esi_291 + 0x01
	branch al_312 == 0x00 l00402E18
l00402DFD:
	branch (byte) (word32) esi_291->b0000 != 0x7F l00402DF0
	byte al_312 = (byte) (word32) esi_291->b0000
	branch al_312 != 0x7F l00402DF0
l00402E04:
	byte al_516 = (byte) (word32) esi_291[0x01]
	byte * edx_518 = edx_296 + 0x01
	*(edx_518 - 0x01) = al_516
	struct Eq_3496 * esi_517 = esi_291 + 0x01
	branch al_516 != 0x00 l00402DFD
	byte al_524 = (byte) (word32) esi_517->b0002
	*edx_518 = al_524
	edx_296 = edx_518 + 0x01
	esi_291 = (struct Eq_3432 *) (esi_517->b0002 + 0x01)
	branch al_524 != 0x00 l00402DFD
l00402E18:
	*esp_292 = esp_292
	branch _strdup(*esp_292) == 0x00 l00402FF2
	esp_266->t0000 = esp_292
	Eq_43 eax_326 = _strdup(esp_266->t0000)
	branch eax_326 == 0x00 l00402FF2
l00402E2C:
	*(ebp_126 - 0x3C) = *(ebp_126 - 0x3C) & (word32) (*(ebp_126 - 0x3C) == 0x02) - 0x01
	branch *(ebp_126 - 88) != 0x00 l00402FE3
	*(ebp_126 - 0x3C) = *(ebp_126 - 0x3C) & (word32) (*(ebp_126 - 0x3C) == 0x02) - 0x01
	branch *(ebp_126 - 88) != 0x00 l00402FE3
l00402E46:
	int32 ecx_384
	branch *(ebp_126 - 0x44) == 0x00 l0040310C
	Eq_43 ebx_375 = *(ebp_126 - 0x44)
	branch ebx_375 == 0x00 l0040310C
l00402E51:
	ui32 edi_422 = *(ebp_126 - 0x34)
	goto l00402E74
l00402E60:
	eax_444 = strcoll(esp_266->t0000, esp_266->t0004)
	ecx_466 = *ebx_375.u0
	edx_451 = *ebx_375.u0
	branch eax_444 <= 0x00 l00402E90
l00402E6E:
	branch edx_451 == 0x00 l00402E96
	branch edx_451 == 0x00 l00402E96
l00402E72:
	ebx_375 = edx_451
l00402E74:
	int32 eax_444
	Eq_43 edx_451
	Eq_43 ecx_466
	Eq_43 eax_434 = *ebx_375.u0
	esp_266->t0000 = eax_326
	esp_266->t0004 = eax_434
	branch (edi_422 & 0x4000) != 0x00 l00402E60
l00402E82:
	eax_444 = _stricoll(esp_266->t0000, esp_266->t0004)
	ecx_466 = *ebx_375.u0
	edx_451 = *ebx_375.u0
	branch eax_444 > 0x00 l00402E6E
l00402E90:
	edx_451 = ecx_466
	branch ecx_466 != 0x00 l00402E72
l00402E96:
	ecx_384 = eax_444
l00402E98:
	*(ebp_126 - 0x54) = ecx_384
	esp_266->t0000.u0 = 0x0C
	Eq_43 eax_389 = malloc(esp_266->t0000)
	branch eax_389 == 0x00 l00402ECD
l00402EAB:
	*eax_389 = eax_326
	eax_389->u0 = 0x00
	eax_389->u0 = 0x00
	branch ebx_375 == 0x00 l00402ECD
l00402EBF:
	branch *(ebp_126 - 0x54) <= 0x00 l004030E0
l00402ECA:
	*ebx_375.u0 = eax_389
l00402ECD:
	branch *(ebp_126 - 0x44) == 0x00 l004030ED
l00402ED8:
	esp_107 = (struct Eq_2910 *) *(ebp_126 - 0x50)
	goto l00402D58
l00402EE0:
	esp_29->t0000 = eax_38
	word32 eax_883 = strlen(esp_29->t0000) + 0x10 & ~0x0F
	fn00402550(eax_883)
	union Eq_43 * esp_890 = esp_29 - eax_883
	Eq_43 edx_886 = eax_38
	ptr32 ecx_893 = esp_890
	goto l00402F12
l00402F05:
	ecx_893 = ecx_893 + 0x01
	*(ecx_893 - 0x01) = al_908
	edx_886 = edx_886
	branch al_908 == 0x00 l00402F2D
l00402F12:
	branch (byte) (word32) *edx_886 != 0x7F l00402F05
	byte al_908 = (byte) (word32) *edx_886
	branch al_908 != 0x7F l00402F05
l00402F19:
	byte al_941 = (byte) (word32) *edx_886
	byte * ecx_943 = ecx_893 + 0x01
	*(ecx_943 - 0x01) = al_941
	struct Eq_3674 * edx_942 = edx_886
	branch al_941 != 0x00 l00402F12
	byte al_949 = (byte) (word32) edx_942->b0002
	*ecx_943 = al_949
	ecx_893 = ecx_943 + 0x01
	edx_886 = edx_942->b0002 + 0x01
	branch al_949 != 0x00 l00402F12
l00402F2D:
	*esp_890 = esp_890
	branch _strdup(*esp_890) == 0x00 l00402C6B
	esp_29->t0000 = esp_890
	Eq_43 eax_922 = _strdup(esp_29->t0000)
	eax_102.u0 = 0x01
	branch eax_922 == 0x00 l00402C6B
l00402F46:
	Eq_43 ecx_933
	fn00402B40(eax_922, fp - 44, out ecx_933)
	word32 ecx_937
	eax_102 = fn00402B40(ecx_933, fp - 44, out ecx_937)
	goto l00402C9D
l00402F55:
	esp_107->t0000 = *(ebp_126 - 44)
	fn00403A20(dwArg00)
	branch *(ebp_126 - 0x44) == 0x00 l00402F72
l00402F67:
	fn00402BD0(*(ebp_126 - 0x44), ebp_126->ptr0008)
l00402F72:
	*(ebp_126 - 0x38) = *(ebp_126 - 0x38) + 0x04
	union Eq_43 * edi_197 = *(ebp_126 - 0x38)
	esp_107->t0000 = *(edi_197 - 0x04)
	free(esp_107->t0000)
	eax_152 = *edi_197
	branch eax_152 != 0x00 l00402D10
l00402F8E:
	eax_121 = *(ebp_126 - 0x20)
l00402F91:
	esp_107->t0000 = eax_121
	free(esp_107->t0000)
	return *(ebp_126 - 0x3C)
l00402FA4:
	union Eq_43 * eax_544 = *(ebp_126 - 0x38)
	Eq_43 esi_545 = *(ebp_126 - 0x4C)
	*(ebp_126 - 100) = edx_256
	Eq_43 eax_547 = *eax_544
	esp_266->t0008 = esi_545
	esp_266->t0000 = &esp_266->t0008
	esp_266->t0004 = eax_547
	memcpy(esp_266->t0000, esp_266->t0004, esp_266->t0008)
	byte al_553 = (byte) (word32) Mem550[esp_266 + 11 + esi_545:byte]
	edx_256 = *(ebp_126 - 100)
	branch al_553 == 0x5C || al_553 == 0x2F l00403000
	goto l00402FCF
l00402FCB:
l00402FCF:
	int32 esi_566 = *(ebp_126 - 0x4C)
	(&esp_266->t0008)[esi_566 / 0x0C] = (struct Eq_3319) (byte) (word32) *(ebp_126 - 0x5D)
	eax_267 = esi_566 + 0x01
	goto l00402DB7
l00402FE3:
	fn00402BB0(eax_326, ebp_126->ptr0008)
	goto l00402ED8
l00402FF2:
	*(ebp_126 - 0x3C) = 0x03
	goto l00402ED8
l00403000:
	eax_267 = *(ebp_126 - 0x4C)
	goto l00402DB7
l00403008:
	esp_29->t0000 = *(fp - 0x4C)
	word32 eax_733 = strlen(esp_29->t0000) + eax
	branch eax >= eax_733 l004031B1
l0040301D:
	byte dl_795 = (byte) (word32) *eax_733
	branch dl_795 == 0x2F l004031A6
l00403029:
	branch dl_795 != 0x5C l0040304B
	goto l004031A6
l00403035:
	byte al_818 = (byte) (word32) (eax_733 - (struct <anonymous> *) 0x01)->b0000
	branch al_818 == 0x5C || al_818 == 0x2F l00403101
	goto l00403049
l00403041:
l00403049:
	eax_733 = edx_807
l0040304B:
	Eq_43 edx_807 = eax_733 - (struct <anonymous> *) 0x01
	branch edx_807 != eax l00403035
l00403052:
	byte al_814 = (byte) (word32) (eax_733 - (struct <anonymous> *) 0x01)->b0000
	*(fp - 0x44) = (union Eq_43 *) edx_807
	*(fp - 0x61) = al_814
l0040305C:
	branch *(fp - 0x61) != 0x5C && *(fp - 0x61) != 0x2F l00403172
l00403066:
	struct Eq_4138 * eax_759 = *(fp - 0x44)
	word32 edx_764 = (word32) eax_759->b0001
	byte cl_761 = (byte) (word32) *(fp - 0x61)
	byte * eax_762 = &eax_759->b0001
	byte dl_765 = (byte) edx_764
	branch dl_765 != 0x5C l00403085
l00403078:
	eax_762 = eax_762 + 0x01
	edx_764 = (word32) *eax_762
	cl_761 = (byte) edx_764
	dl_765 = (byte) edx_764
	branch dl_765 == 0x5C l00403078
l00403085:
	branch dl_765 == 0x2F l00403078
l0040308A:
	*(fp - 0x44) = (byte **) eax_762
	*(fp - 0x61) = cl_761
l00403090:
	branch *(fp - 0x4C) != 0x00 l00402CE2
l0040309B:
	ebx_16 = *(fp - 0x44)
	goto l00402CCE
l004030A3:
	word32 ebx_590 = *(ebp_126 - 0x68)
	branch ebx_590 != 0x00 l004030D2
l004030AA:
	<anonymous> * edi_612 = *(ebp_126 - 0x5C)
	branch edi_612 == null l00402F72
l004030B5:
	esp_107->t0004 = *_errno()
	Eq_43 eax_620 = **(ebp_126 - 0x38)
	esp_107->t0000 = eax_620
	word32 edi_624
	word32 esi_625
	word32 ebx_626
	word32 eax_627
	byte SCZO_628
	word32 edx_629
	word32 ecx_630
	byte SZO_631
	byte C_632
	byte Z_633
	byte dh_634
	byte al_635
	byte cl_636
	byte dl_637
	word16 dx_638
	edi_612()
	branch eax_627 == 0x00 l00402F72
l004030D2:
	*(ebp_126 - 0x3C) = 0x01
	goto l00402F72
l004030E0:
	word32 edi_415 = *(ebp_126 - 0x44)
	*ebx_375.u0 = eax_389
	branch edi_415 != 0x00 l00402ED8
l004030ED:
	*(ebp_126 - 0x44) = (union Eq_43 *) eax_389
	goto l00402ED8
l004030F5:
	*(ebp_126 - 0x4C) = 0x00
	goto l00402D48
l00403101:
	*(fp - 0x44) = (union Eq_43 *) edx_807
	*(fp - 0x61) = al_818
	goto l0040305C
l0040310C:
	ebx_375.u0 = 0x00
	ecx_384 = 0x00
	goto l00402E98
l00403115:
l00403127:
	esp_29->t0000 = ebx_16
	word32 eax_672 = strlen(esp_29->t0000) + 0x10 & ~0x0F
	fn00402550(eax_672)
	union Eq_43 * esp_675 = esp_29 - eax_672
	ptr32 edx_679 = esp_675
	goto l00403153
l00403146:
	edx_679 = edx_679 + 0x01
	*(edx_679 - 0x01) = al_695
	ebx_16 = ebx_16
	branch al_695 == 0x00 l00403185
l00403153:
	branch (byte) (word32) *ebx_16 != 0x7F l00403146
	byte al_695 = (byte) (word32) *ebx_16
	branch al_695 != 0x7F l00403146
l0040315A:
	struct Eq_4021 * ebx_719 = ebx_16
	al_695 = (byte) (word32) ebx_719->b0001
	ebx_16 = &ebx_719->b0001
	goto l00403146
l00403163:
	eax_121 = *(fp - 0x3C)
	*(fp - 0x40) = 0x02
	goto l00402F91
l00403172:
l0040317C:
	*(fp - 0x61) = 0x5C
	goto l00403090
l00403185:
	*esp_675 = esp_675
	fn00402BB0(_strdup(*esp_675), fp->ptr0004)
	eax_121 = *(fp - 0x24)
	*(fp - 0x40) = 0x00
	esp_107 = esp_29
	goto l00402F91
l004031A6:
	*(fp - 0x61) = dl_795
	*(fp - 0x44) = (union Eq_43 *) eax_733
	goto l0040305C
l004031B1:
	byte cl_830 = (byte) (word32) *eax_733
	*(fp - 0x44) = (union Eq_43 *) eax_733
	*(fp - 0x61) = cl_830
	goto l0040305C
fn00402C10_exit:
}

Eq_43 fn004031C0(word32 dwArg04, word32 dwArg08, word32 dwArg0C, word32 dwArg10)
{
	Eq_43 ebx_148 = dwArg04;
	if (dwArg10 != null && (dwArg08 & 0x02) == 0x00)
		dwArg10->dw000C = 0x00;
	if (dwArg10->dw0000 != 0x0040A20A)
	{
		fn00402860(dwArg10);
		dwArg10->dw0000 = 0x0040A20A;
	}
	Eq_43 eax_36 = fn00402C10(dwArg04, (word16) dwArg08, fp - 0x04);
	if (eax_36 == 0x02 && (dwArg08 & 0x10) != 0x00)
	{
		*(fp - 0x24) = (union Eq_43 *) eax_36;
		*(fp - 0x20) = fp - 44;
		*(fp - 44) = (union Eq_43 *) dwArg04;
		word32 eax_77 = strlen(*(fp - 44)) + 0x10 & ~0x0F;
		fn00402550(eax_77);
		union Eq_43 * esp_81 = fp - 44 - eax_77;
		word32 ecx_80 = *(fp - 0x24);
		ptr32 edx_146 = esp_81;
		do
		{
			byte al_96 = (byte) (word32) *ebx_148;
			if (al_96 == 0x7F)
			{
				byte al_136 = (byte) (word32) *ebx_148;
				byte * edx_138 = edx_146 + 0x01;
				*(edx_138 - 0x01) = al_136;
				struct Eq_4355 * ebx_137 = ebx_148;
				byte al_144 = (byte) (word32) ebx_137->b0002;
				*edx_138 = al_144;
				edx_146 = edx_138 + 0x01;
				ebx_148 = ebx_137->b0002 + 0x01;
				if (al_144 == 0x00)
					break;
				continue;
			}
			edx_146 = edx_146 + 0x01;
			*(edx_146 - 0x01) = al_96;
			ebx_148 = ebx_148;
		} while (al_96 == 0x00);
		*(fp - 0x24) = ecx_80;
		*esp_81 = esp_81;
		fn00402BB0(_strdup(*esp_81), dwArg10);
		Eq_43 ecx_109 = *(fp - 0x24);
		struct Eq_2516 * esi_113 = *(fp - 0x0C);
		Eq_43 edi_115 = *(fp - 0x08);
		ptr32 ebp_117 = *(fp - 0x04);
		return ecx_109;
		*(ebp_117 - 0x20) = (union Eq_43 *) ecx_109;
		*fp = (union Eq_43 *) edi_115;
		fn00402BB0(_strdup(*fp), esi_113);
		return *(ebp_117 - 0x20);
	}
	else
		return eax_36;
}

Eq_43 fn004032C0(Eq_43 eax, word32 dwArg04)
{
fn004032C0_entry:
	struct Eq_4435 * esp_21
	word32 ebp_22
	word32 edi_23
	word32 esi_24
	word32 ebx_25
	byte SCZO_26
	Eq_43 eax_27
	byte SZO_28
	byte C_29
	byte Z_30
	word32 edx_31
	word32 ecx_32
	word16 cx_33
	word16 ax_34
	byte CZ_35
	word16 dx_36
	word16 di_37
	msvcrt.dll!setlocale()
	branch eax_27 == 0x00 l004032F0
	goto l004032E6
l004032C0:
l004032E6:
	esp_21->t0000 = eax_27
	_strdup(esp_21->t0000)
l004032F0:
	esp_21->dw0004 = 0x0040A21C
	esp_21->t0000.u0 = 0x02
	struct Eq_4463 * esp_44
	word32 ebp_45
	word32 edi_46
	Eq_43 esi_47
	Eq_43 ebx_48
	byte SCZO_49
	word32 eax_50
	byte SZO_51
	byte C_52
	byte Z_53
	word32 edx_54
	word32 ecx_55
	word16 cx_56
	word16 ax_57
	byte CZ_58
	word16 dx_59
	word16 di_60
	msvcrt.dll!setlocale()
	branch esi_47 == 0x00 || *esi_47 == 0x00 l0040330D
	goto l00403380
l00403308:
l0040330D:
	esp_44->t0008.u0 = 0x00
	esp_44->t0004.u0 = 0x0040A21E
	esp_44->t0000.u0 = 0x00
	Eq_43 eax_103 = wcstombs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	Mem105[esp_44 + 0x04:word32] = eax_103 + 0x01
	esp_44->t0000 = globals->t40D068
	Eq_43 eax_108 = realloc(esp_44->t0000, esp_44->t0004)
	globals->t40D068 = eax_108
	Mem110[esp_44 + 0x08:word32] = eax_103 + 0x01
	esp_44->t0004.u0 = 0x0040A21E
	esp_44->t0000 = eax_108
	Eq_43 eax_113 = wcstombs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	esp_44->t0004 = ebx_48
	esp_44->t0000.u0 = 0x02
	union Eq_43 * esp_116
	word32 ebp_117
	word32 edi_118
	word32 esi_119
	Eq_43 ebx_120
	byte SCZO_121
	word32 eax_122
	byte SZO_123
	byte C_124
	byte Z_125
	word32 edx_126
	word32 ecx_127
	word16 cx_128
	word16 ax_129
	byte CZ_130
	word16 dx_131
	word16 di_132
	msvcrt.dll!setlocale()
	*esp_116 = (union Eq_43 *) ebx_120
	free(*esp_116)
	return globals->t40D068
l00403380:
	Eq_4603 dwLoc28_215
	esp_44->t0008.u0 = 0x00
	esp_44->t0004 = esi_47
	esp_44->t0000.u0 = 0x00
	Eq_43 eax_151 = mbstowcs(esp_44->t0000, esp_44->t0004, esp_44->t0008)
	word32 eax_153 = eax_151 + 0x12 + eax_151
	fn00402550(eax_153 & ~0x0F)
	struct Eq_4639 * esp_157 = esp_44 - (eax_153 & ~0x0F)
	esp_157->t0008 = eax_151
	esp_157->t0004 = esi_47
	word32 v13_160 = esp_157 + 0x0D >>u 0x01
	esp_157->t0000 = v13_160 * 0x02
	Eq_43 eax_169 = mbstowcs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	(eax_169 * 0x02)[v13_160] = 0x00
	word32 eax_177 = (word32) null[v13_160]
	word16 ax_178 = (word16) eax_177
	word16 wLoc2A_179 = ax_178
	branch eax_169 <= 0x01 l004034DE
l004033EC:
	branch ax_178 == 0x5C || ax_178 == 0x2F l004033FC
	goto l00403506
l004033F2:
l004033FC:
	dwLoc28_215 = v13_160 * 0x02
	branch ax_178 == Mem172[(v13_160 + 0x02) + v13_160:word16] && Mem172[(v13_160 + 0x04) + v13_160:word16] == 0x00 l0040365F
l00403410:
	word16 ax_220 = (word16) (word32) wLoc2A_179
	branch ax_220 == 0x00 l00403617
l0040341D:
	Eq_4603 edx_224 = dwLoc28_215
	Eq_4603 edi_226 = dwLoc28_215
	goto l00403438
l00403424:
	branch ax_220 == 0x2F l0040344A
l0040342A:
	ax_220 = (word16) (word32) *edx_224
	ecx_484 = *edx_224
	branch ax_220 == 0x00 l0040346C
l00403436:
	edx_224 = ecx_484
l00403438:
	word16 ax_497
	Eq_4603 ecx_484
	branch ax_220 != 0x5C l00403424
l0040343E:
	ax_497 = (word16) (word32) *edx_224
	branch ax_497 != 0x5C l00403453
l00403447:
	edx_224 = edx_224
l0040344A:
	ax_497 = (word16) (word32) *edx_224
	branch ax_497 == 0x5C l00403447
l00403453:
	branch ax_497 == 0x2F l00403447
l00403459:
	branch ax_497 == 0x00 l0040346C
l0040345E:
	ax_220 = (word16) (word32) *edx_224
	edi_226 = edx_224
	ecx_484 = edx_224
	branch ax_220 != 0x00 l00403436
l0040346C:
	branch dwLoc28_215 < edi_226 l004034F1
l00403473:
	word16 * eax_258
	branch wLoc2A_179 == 0x5C || wLoc2A_179 == 0x2F l00403485
	goto l0040363F
l0040347A:
l00403485:
	eax_258 = (word16 *) dwLoc28_215
l0040348B:
	*eax_258 = 0x00
	esp_157->t0008.u0 = 0x00
	esp_157->t0000.u0 = 0x00
	esp_157->t0004 = v13_160 * 0x02
	Eq_43 eax_269 = wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	Mem271[esp_157 + 0x04:word32] = eax_269 + 0x01
	esp_157->t0000 = globals->t40D068
	Eq_43 eax_274 = realloc(esp_157->t0000, esp_157->t0004)
	globals->t40D068 = eax_274
	Mem277[esp_157 + 0x08:word32] = eax_269 + 0x01
	esp_157->t0000 = eax_274
	esp_157->t0004 = v13_160 * 0x02
	wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	goto l004035C7
l004034DE:
	dwLoc28_215 = v13_160 * 0x02
	goto l00403410
l004034E9:
	branch dx_473 != 0x2F l00403535
l004034EF:
	edi_226 = eax_302
l004034F1:
	Eq_4603 eax_302 = edi_226 - 0x02
	branch dwLoc28_215 >= eax_302 l00403535
l004034F8:
	word16 dx_473 = (word16) (word32) *(edi_226 - 0x02)
	branch dx_473 != 0x5C l004034E9
l00403502:
	edi_226 = eax_302
	goto l004034F1
l00403506:
	dwLoc28_215 = v13_160 * 0x02
	branch Mem172[v13_160 + 0x02 + v13_160:word16] != 0x3A l00403410
l0040351B:
	dwLoc28_215 = v13_160 * 0x02 + 0x04
	wLoc2A_179 = (word16) (word32) Mem172[v13_160 + 0x04 + v13_160:word16]
	goto l00403410
l00403535:
	branch dwLoc28_215 == eax_302 l00403675
l0040353E:
	*eax_302 = 0x00
	word16 dx_318 = (word16) (word32) null[v13_160]
	struct Eq_4893 * eax_319 = v13_160 * 0x02
	branch dx_318 != 0x5C && dx_318 != 0x2F l0040361F
l00403558:
	eax_319 = eax_319 + 0x01
	word16 cx_439 = (word16) (word32) eax_319->w0000
	branch cx_439 == 0x5C || cx_439 == 0x2F l00403558
	goto l0040356A
l00403564:
l0040356A:
	branch eax_319 - v13_160 * 0x02 <= 0x05 l00403629
l00403578:
	eax_319 = v13_160 * 0x02
l0040357B:
	struct Eq_4893 * ecx_331 = eax_319
l0040357D:
	branch dx_318 == 0x00 l004035A3
l00403582:
	ecx_331 = ecx_331 + 0x01
	*(ecx_331 - 0x02) = dx_318
	branch dx_318 == 0x2F l004035F2
l0040358F:
	word32 edi_402 = eax_319 + 0x02
	branch eax_319->w0000 == 0x5C l004035F0
l00403598:
	dx_318 = (word16) (word32) eax_319[0x01]
	eax_319 = edi_402
	branch dx_318 != 0x00 l00403582
l004035A3:
	ecx_331->w0000 = 0x00
	esp_157->t0008 = eax_169
	esp_157->t0000 = esi_47
	esp_157->t0004 = v13_160 * 0x02
	Eq_43 eax_360 = wcstombs(esp_157->t0000, esp_157->t0004, esp_157->t0008)
	branch eax_360 == ~0x00 l004035C7
l004035C3:
	Mem364[esi_47 + eax_360:byte] = 0x00
l004035C7:
	esp_157->t0004 = ebx_48
	esp_157->t0000.u0 = 0x02
	union Eq_43 * esp_184
	word32 ebp_185
	word32 edi_186
	Eq_43 esi_187
	Eq_43 ebx_188
	byte SCZO_189
	word32 eax_190
	byte SZO_191
	byte C_192
	byte Z_193
	word32 edx_194
	word32 ecx_195
	word16 cx_196
	word16 ax_197
	byte CZ_198
	word16 dx_199
	word16 di_200
	msvcrt.dll!setlocale()
	*esp_184 = (union Eq_43 *) ebx_188
	free(*esp_184)
	return esi_187
l004035F0:
	eax_319 = edi_402
l004035F2:
	dx_318 = (word16) (word32) eax_319->w0000
	branch dx_318 != 0x2F l00403654
l00403600:
	eax_319 = eax_319 + 0x02
	dx_318 = (word16) (word32) eax_319->w0000
	branch dx_318 == 0x5C || dx_318 == 0x2F l00403600
	goto l0040357D
l0040360C:
l0040361F:
l00403629:
	branch Mem315[v13_160 + 0x02 + v13_160:word16] != dx_318 l00403578
	branch Mem315[v13_160 + 0x02 + v13_160:word16] != dx_318 l00403578
l00403637:
	dx_318 = (word16) (word32) eax_319->w0000
	goto l0040357B
l0040363F:
	*dwLoc28_215 = 0x2E
	eax_258 = (word16 *) dwLoc28_215
	goto l0040348B
l00403654:
	branch dx_318 == 0x5C l00403600
	goto l0040357D
l0040365F:
l00403675:
	branch wLoc2A_179 == 0x5C l0040368A
l0040367C:
	eax_302 = dwLoc28_215
	branch wLoc2A_179 != 0x2F l0040353E
l0040368A:
	eax_302 = dwLoc28_215
	branch *dwLoc28_215 != (word16) ((word32) wLoc2A_179) l0040353E
l0040369B:
	word16 dx_459 = (word16) (word32) *dwLoc28_215
	branch dx_459 == 0x2F l0040353E
l004036A9:
	eax_302 = edi_226
	branch dx_459 != 0x5C l0040353E
l004036B5:
	eax_302 = dwLoc28_215
	goto l0040353E
fn004032C0_exit:
}

Eq_43 fn004036C0(Eq_43 eax, word16 dx)
{
	if (FindNextFileA(eax, fp + 4294966964) != 0x00)
	{
		Eq_43 ebx_65;
		struct Eq_5065 * ebp_66;
		struct Eq_5066 * esi_67;
		word16 ax_68 = fn00405A80(edx + 0x0C, 0x0104, 0x0040A224, out ebx_65, out ebp_66, out esi_67);
		esi_67->w0006 = ax_68;
		word32 eax_70 = ebp_66->dwFFFFFEB8;
		uint32 eax_73 = DPB(eax_70, (byte) eax_70 & 88, 0);
		if (eax_73 <= 0x10)
		{
			esi_67->dw0008 = eax_73;
			return ebx_65;
		}
		else
		{
			esi_67->dw0008 = 0x18;
			return ebx_65;
		}
	}
	else
	{
		if (GetLastError() != 0x12)
			*_errno() = 0x02;
		return 0x00;
	}
}

Eq_43 fn00403760(Eq_43 eax, Eq_43 edx)
{
	Eq_43 eax_19 = FindFirstFileA(eax, fp + 4294966964);
	Eq_43 esi_24 = eax_19;
	if (eax_19 != ~0x00)
	{
		struct Eq_5143 * ebx_52;
		struct Eq_5144 * ebp_53;
		word16 ax_55 = fn00405A80(edx, 0x0104, 0x0040A224, out ebx_52, out ebp_53, out esi_24);
		word32 ecx_56 = ebp_53->dwFFFFFEB8;
		ebx_52->w0006 = ax_55;
		uint32 ecx_59 = DPB(ecx_56, (byte) ecx_56 & 88, 0);
		ebx_52->dw0008 = ecx_59;
		if (ecx_59 > 0x10)
			ebx_52->dw0008 = 0x18;
	}
	else
	{
		Eq_43 eax_65 = _errno();
		Eq_43 eax_67 = GetLastError();
		*eax_65 = eax_67;
		if (eax_67 != 0x03)
		{
			if (*_errno() != 0x010B)
			{
				if (*_errno() != 0x02)
				{
					*_errno() = 22;
					esi_24 = eax_19;
				}
			}
			else
				*_errno() = 0x14;
		}
		else
			*_errno() = 0x02;
	}
	return esi_24;
}

Eq_43 fn00403830(word32 dwArg04)
{
	esp = fp;
	esp = fp - 0x04;
	dwLoc04 = ebp;
	esp = fp - 0x08;
	dwLoc08 = edi;
	esp = fp - 0x0C;
	dwLoc0C = esi;
	esp = fp - 0x10;
	dwLoc10 = ebx;
	esp = fp - 0x013C;
	eax = dwArg04;
	SZO = cond(eax & eax);
	Z = SZO;
	C.u0 = false;
	if (Test(EQ,Z))
	{
		eax = _errno();
		*eax = 22;
		eax.u0 = 0x00;
		SZO = cond(0x00);
		C.u0 = false;
		goto l0040395D;
	}
	SCZO = cond(*eax.u0 - 0x00);
	if (Test(EQ,Z))
	{
		eax = _errno();
		*eax.u0 = 0x02;
		eax.u0 = 0x00;
		SZO = cond(0x00);
		C.u0 = false;
		goto l0040395D;
	}
	edi = fp - 288;
	dwLoc0134.u0 = 0x0104;
	ebx = fp - 288;
	dwLoc0138 = eax;
	dwLoc013C = fp - 288;
	eax = _fullpath(dwLoc013C, dwLoc0138, 0x0104);
	SCZO = cond(bLoc0120 - 0x00);
	if (Test(NE,Z))
	{
		do
		{
			edx = *ebx;
			ebx = ebx;
			eax = edx;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
		SZO = cond(eax & 0x8080);
		C.u0 = false;
		if (Test(NE,Z))
		{
			al = al + al;
			SCZO = cond(al);
			ebx = ebx - 0x03 - C;
			ebx = ebx - (fp - 288);
			eax = (word32) Mem0[fp - 0x0121 + ebx:byte];
			SCZO = cond(al - 0x5C);
			if (Test(EQ,Z))
				goto l004038F4;
		}
		else
		{
			eax = eax >> 0x10;
			ebx = ebx;
			al = al + al;
			SCZO = cond(al);
			ebx = ebx - 0x03 - C;
			ebx = ebx - (fp - 288);
			eax = (word32) Mem0[fp - 0x0121 + ebx:byte];
			SCZO = cond(al - 0x5C);
			if (Test(EQ,Z))
				goto l004038F4;
		}
		SCZO = cond(al - 0x2F);
		if (Test(EQ,Z))
		{
l004038F4:
			edx.u0 = 0x2A;
			eax = *ebx;
			Mem0[fp - 288 + ebx:word16] = dx;
			dwLoc013C = eax;
			eax = malloc(dwLoc013C);
			SZO = cond(eax & eax);
			C.u0 = false;
			esi = eax;
			if (Test(NE,Z))
			{
				ebp = *eax.u0;
				ebx = *ebx;
				SCZO = cond(ebx);
				dwLoc0134 = ebx;
				dwLoc0138 = fp - 288;
				dwLoc013C = ebp;
				eax = memcpy(dwLoc013C, dwLoc0138, dwLoc0134);
				edx = esi;
				eax = ebp;
				eax = fn00403760(eax, edx);
				SCZO = cond(eax - ~0x00);
				*esi = eax;
				if (Test(NE,Z))
				{
					eax.u0 = 0x0110;
					esi->u1 = ax;
					eax = esi;
					*esi = 0x00;
					*esi = 0x00;
				}
				else
				{
					*esp = esi;
					free(*esp);
					eax.u0 = 0x00;
					SZO = cond(0x00);
					C.u0 = false;
				}
			}
			else
			{
				eax = _errno();
				*eax.u0 = 0x0C;
				eax.u0 = 0x00;
				SZO = cond(0x00);
				C.u0 = false;
			}
l0040395D:
			esp = *esp;
			SCZO = cond(esp);
			ebx = *esp;
			esp = *esp;
			esi = *esp;
			esp = *esp;
			edi = *esp;
			esp = *esp;
			ebp = *esp;
			esp = *esp;
			return eax;
		}
		ecx = 0x5C;
		Mem0[fp - 288 + ebx:word16] = cx;
		ebx = fp - 288;
		do
		{
			edx = *ebx;
			ebx = *ebx;
			eax = *edx.u0;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
	}
	else
	{
		do
		{
			edx = *ebx;
			ebx = ebx;
			eax = edx;
			edx = ~edx;
			eax = eax & edx;
			eax = eax & 0x80808080;
			SZO = cond(eax);
			C.u0 = false;
		} while (Test(EQ,Z));
	}
	SZO = cond(eax & 0x8080);
	SZO = cond(eax & 0x8080);
	C.u0 = false;
	if (Test(EQ,Z))
	{
		eax = eax >> 0x10;
		ebx = *ebx;
		SCZO = cond(ebx);
	}
	al = al + al;
	SCZO = cond(al);
	ebx = ebx - 0x03 - C;
	ebx = ebx - (fp - 288);
	al = al + al;
	SCZO = cond(al);
	ebx = ebx - 0x03 - C;
	ebx = ebx - (fp - 288);
	SCZO = cond(ebx);
	goto l004038F4;
}

Eq_5499 * fn004039D0(word32 dwArg04, ptr32 & ebpOut)
{
	*ebpOut = ebp;
	struct Eq_5499 * eax_16;
	if (dwArg04 == null)
	{
		*_errno() = 0x09;
		eax_16 = null;
		return eax_16;
	}
	int32 eax_24 = dwArg04->dw0114;
	dwArg04->dw0114 = eax_24 + 0x01;
	if (eax_24 > 0x00)
	{
		eax_16 = fn004036C0(dwArg04->t0110, (word16) dwArg04);
		if (eax_16 == null)
			return eax_16;
	}
	eax_16 = dwArg04;
	return eax_16;
}

void fn00403A20(word32 dwArg04)
{
	if (dwArg04 != 0x00 && FindClose(*dwArg04) != 0x00)
		free(dwArg04);
	else
		*_errno() = 0x09;
	return;
}

void fn00403C70(Eq_5553 al, Eq_5554 * edx)
{
	int32 ebx_33;
	byte ch_9 = edx->b0005;
	if ((ch_9 & 0x20) == 0x00)
	{
		ebx_33 = edx->dw0018;
		if (edx->dw001C <= ebx_33)
			goto l00403C94;
	}
	if ((ch_9 & 0x10) != 0x00)
	{
		word32 esp_59;
		word32 ebx_60;
		byte SCZO_61;
		word32 ecx_62;
		word32 edx_63;
		byte ch_64;
		byte SZO_65;
		byte C_66;
		byte Z_67;
		byte al_68;
		word32 eax_69;
		msvcrt.dll!fputc();
		edx->dw0018 = edx->dw0018 + 0x01;
		return;
	}
	edx->ptr0000[edx->dw0018].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00].a0000[0x00] = al;
	ebx_33 = edx->dw0018;
l00403C94:
	edx->dw0018 = ebx_33 + 0x01;
	return;
}

word32 fn00405110(word32 dwArg04, ptr32 dwArg08, word32 dwArg0C, word32 dwArg10, word32 dwArg14, ptr32 & ebxOut, ptr32 & ebpOut, ptr32 & esiOut)
{
	*ebpOut = ebp;
	*esiOut = esi;
	*ebxOut = ebx;
	struct Eq_5618 * esi_145 = dwArg10;
	char * eax_39 = getenv("PRINTF_EXPONENT_DIGITS");
l004051A0:
	int32 eax_143 = (int32) esi_145->b0000;
	struct Eq_5618 * ebx_144 = esi_145[0x01];
	Eq_5553 al_134 = (byte) eax_143;
	struct Eq_5618 * ecx_137 = ebx_144;
	if (eax_143 != 0x00)
	{
		do
		{
			if (eax_143 != 0x25)
			{
				fn00403C70(al_134, fp - 0x40);
				esi_145 = ebx_144;
				goto l004051A0;
			}
			word32 eax_149 = fp->dw0004;
			*(fp - 0x34) = ~0x00;
			*(fp - 0x38) = ~0x00;
			*(fp - 88) = 0x00;
			*(fp - 0x3C) = eax_149;
			word32 edx_154 = (word32) esi_145[0x01];
			*(fp - 0x54) = fp - 0x38;
			*(fp - 0x5C) = 0x00;
			byte dl_155 = (byte) edx_154;
			while (dl_155 != 0x00)
			{
				cu8 al_176 = (byte) (edx_154 - 0x20);
				int32 edi_177 = (int32) dl_155;
				struct Eq_5618 * esi_180 = ecx_137[0x01];
				if (al_176 <= 0x5A)
				{
					ui32 eax_181 = (word32) al_176;
					word32 esp_185;
					word32 ebp_186;
					word32 edi_187;
					word32 esi_188;
					word32 ebx_189;
					byte SCZO_190;
					word32 eax_191;
					byte SZO_192;
					byte C_193;
					word16 ax_194;
					byte Z_195;
					byte CZ_196;
					byte ah_197;
					word32 ecx_198;
					word32 edx_199;
					byte dl_200;
					byte al_201;
					byte S_202;
					(*globals->a40A25C)();
					return eax_191;
				}
				word32 eax_203 = *(fp - 0x5C);
				if (eax_203 == 0x04 || (byte) (edx_154 - 0x30) > 0x09)
				{
					fn00403C70(0x25, fp - 0x40);
					esi_145 = ebx_144;
					goto l004051A0;
				}
				if (eax_203 != 0x00)
				{
					if (eax_203 == 0x02)
						*(fp - 0x5C) = 0x03;
				}
				else
					*(fp - 0x5C) = 0x01;
				if (*(fp - 0x54) != 0x00)
				{
					int32 eax_240 = **(fp - 0x54);
					if (eax_240 < 0x00)
					{
						**(fp - 0x54) = edi_177 - 0x30;
						edx_154 = (word32) ecx_137[0x01];
						dl_155 = (byte) edx_154;
						ecx_137 = esi_180;
						continue;
					}
					**(fp - 0x54) = edi_177 - 0x30 + (eax_240 * 0x05) * 0x02;
				}
				edx_154 = (word32) ecx_137[0x01];
				dl_155 = (byte) edx_154;
				ecx_137 = esi_180;
			}
			eax_143 = (int32) ecx_137->b0000;
			ebx_144 = (struct Eq_5618 *) ecx_137[0x01];
			esi_145 = ecx_137;
			al_134 = (byte) eax_143;
			ecx_137 = ebx_144;
		} while (eax_143 != 0x00);
	}
	return *(fp - 0x28);
	word32 ebx_125;
	*ebxOut = fp->dw005C;
	word32 esi_127;
	*esiOut = fp->dw0060;
	word32 ebp_131;
	*ebpOut = fp->dw0068;
	return fp->dw0044;
}

word16 fn00405A80(word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 & ebxOut, ptr32 & ebpOut, HANDLE & esiOut)
{
	*ebxOut = ebx;
	*esiOut = esi;
	word32 ebp_15;
	return fn00405AB0(dwArg04, dwArg08, dwArg0C, fp + 0x10, out ebp_15);
}

word16 fn00405AB0(word32 dwArg04, word32 dwArg08, word32 dwArg0C, ptr32 dwArg10, ptr32 & ebpOut)
{
	if (dwArg08 == 0x00)
	{
		word32 ebx_64;
		word32 ebp_65;
		word32 esi_66;
		return (word16) fn00405110(0x00, dwArg04, 0x00, dwArg0C, dwArg10, out ebx_64, out ebp_65, out esi_66);
	}
	else
	{
		Eq_5919 (* ebx_42)[];
		word32 ebp_43;
		Eq_2203 esi_44;
		Eq_2203 eax_45 = fn00405110(0x00, dwArg04, dwArg08 - 0x01, dwArg0C, dwArg10, out ebx_42, out ebp_43, out esi_44);
		word16 ax_46 = (word16) eax_45;
		Eq_2203 edx_49 = eax_45;
		if (eax_45 > esi_44)
			edx_49 = esi_44;
		Mem51[ebx_42 + edx_49:byte] = 0x00;
		return ax_46;
	}
}

void fn00408778(word32 dwArg04)
{
	fn00402580(dwArg04, fp + 0x08);
	return;
}

